export const TERRAIN_CONFIG_VERSION='1.0.0';
export const TERRAIN_CRITICAL_FIELDS=Object.freeze(['support_id','photo_principale_url','photo_miniature_url','visuel_actuel_cadre']);
export const CANONICAL_TERRAIN_ROLES=Object.freeze(['Administrateur','Coordonnateur','Installateur']);
export const CANONICAL_TERRAIN_SECTIONS=Object.freeze(['Identification','Intervention','Inspection','Enjeu','Photos']);
export const EMPTY_TERRAIN_CONFIG=Object.freeze({visibleOnTerrain:null,readonlyOnTerrain:null,terrainRoles:null,terrainSection:null,terrainDisplayOrder:null,criticalFields:TERRAIN_CRITICAL_FIELDS});
const object=v=>Boolean(v)&&typeof v==='object'&&!Array.isArray(v),own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
export function terrainProtectionReasons(field){const n=String(field?.technicalName||field?.field_name||'').toLowerCase(),r=[];if(TERRAIN_CRITICAL_FIELDS.includes(n))r.push('Champ Terrain critique non masquable');if(['id','created_at','updated_at','deleted_at','auth_user_id'].includes(n))r.push('Champ système protégé');if(n.endsWith('_id'))r.push('Référence protégée');if(field?.primaryKey||field?.physical_is_primary_key)r.push('Clé primaire');if(field?.foreignKey||field?.physical_is_foreign_key)r.push('Clé étrangère');if(field?.generated||field?.physical_is_generated)r.push('Colonne générée');if(field?.physical?.identity||field?.physical_is_identity)r.push('Colonne identity');if(field?.system||field?.functionalType==='calculated'||field?.field_type==='calculated')r.push('Champ système ou calculé');if(field?.is_virtual||String(field?.id||'').startsWith('physical:'))r.push('Champ virtuel');if(field?.terrain_configurable===false)r.push('Champ non configurable');return[...new Set(r)];}
export function normalizeTerrainConfig(candidate={},field=null){const errors={},warnings=[];if(!object(candidate))return{valid:false,normalized:null,errors:{contract:'Objet TerrainConfig attendu.'},warnings,unknownRoles:[],unknownSection:null};const keys=Object.keys(EMPTY_TERRAIN_CONFIG),unknown=Object.keys(candidate).filter(k=>!keys.includes(k));if(unknown.length)errors[unknown[0]]='Propriété TerrainConfig inconnue.';const normalized={...EMPTY_TERRAIN_CONFIG,criticalFields:[...TERRAIN_CRITICAL_FIELDS]};for(const key of['visibleOnTerrain','readonlyOnTerrain']){const v=own(candidate,key)?candidate[key]:null;if(v!==null&&typeof v!=='boolean')errors[key]='Valeur booléenne ou null attendue.';else normalized[key]=v;}
const roles=own(candidate,'terrainRoles')?candidate.terrainRoles:null,unknownRoles=[];if(roles!==null){if(!Array.isArray(roles))errors.terrainRoles='Liste de rôles ou null attendue.';else{const seen=new Set();for(const role of roles){if(typeof role!=='string'||!role.trim()){errors.terrainRoles='Nom de rôle invalide.';break;}if(seen.has(role)){errors.terrainRoles='Les rôles en doublon sont interdits.';break;}seen.add(role);if(!CANONICAL_TERRAIN_ROLES.includes(role)){unknownRoles.push(role);warnings.push(`Rôle Terrain inconnu conservé : ${role}.`);}}normalized.terrainRoles=[...roles].sort((a,b)=>a.localeCompare(b,'fr-CA'));}}
const section=own(candidate,'terrainSection')?candidate.terrainSection:null;let unknownSection=null;if(section!==null){if(typeof section!=='string'||!section.trim())errors.terrainSection='Section non vide attendue.';else if(Array.from(section).length>100)errors.terrainSection='Maximum 100 caractères.';else{normalized.terrainSection=section.trim();if(!CANONICAL_TERRAIN_SECTIONS.includes(normalized.terrainSection)){unknownSection=normalized.terrainSection;warnings.push(`Section Terrain inconnue conservée : ${unknownSection}.`);}}}
const order=own(candidate,'terrainDisplayOrder')?candidate.terrainDisplayOrder:null;if(order!==null&&(!Number.isInteger(order)||order<0||order>100000))errors.terrainDisplayOrder='Entier entre 0 et 100000 ou null attendu.';else normalized.terrainDisplayOrder=order;
if(own(candidate,'criticalFields')&&JSON.stringify(candidate.criticalFields)!==JSON.stringify(TERRAIN_CRITICAL_FIELDS))errors.criticalFields='La liste gelée des champs critiques est immuable.';
const critical=TERRAIN_CRITICAL_FIELDS.includes(String(field?.technicalName||field?.field_name||'').toLowerCase());if(critical&&normalized.visibleOnTerrain===false)errors.visibleOnTerrain='Un champ Terrain critique ne peut pas être masqué.';
return{valid:Object.keys(errors).length===0,normalized,errors,warnings,unknownRoles,unknownSection};}
export function terrainConfigFromField(field){const stored=object(field?.terrain_config)?field.terrain_config:{};const r=normalizeTerrainConfig(stored,field);return r.valid?r.normalized:{...EMPTY_TERRAIN_CONFIG,criticalFields:[...TERRAIN_CRITICAL_FIELDS]};}
export function stableTerrainConfig(value,field=null){const r=normalizeTerrainConfig(value,field);return r.valid?JSON.stringify(r.normalized):null;}export function terrainConfigChanged(a,b,field=null){const x=stableTerrainConfig(a,field),y=stableTerrainConfig(b,field);return x!==null&&y!==null&&x!==y;}export function terrainNoChange(a,b,field=null){return!terrainConfigChanged(a,b,field);}
export function terrainContradictions(config,field=null){const r=normalizeTerrainConfig(config,field),out=Object.keys(r.errors);if(r.valid&&r.normalized.visibleOnTerrain===false&&r.normalized.readonlyOnTerrain===false)out.push('Champ masqué déclaré modifiable');return out;}
export function findTerrainOrderCollisions(fields=[],field,draft){const order=draft?.terrainDisplayOrder;if(order===null||order===undefined)return[];return fields.filter(x=>x.fieldId!==field?.fieldId&&(x.terrain_config?.terrainDisplayOrder??null)===order).map(x=>x.technicalName);}
export function projectTerrainPreview({config,field,role='Installateur'}={}){const r=normalizeTerrainConfig(config,field),protectedField=terrainProtectionReasons(field).length>0;if(!r.valid)return{visible:false,readonly:true,section:null,order:null,roleTargeted:false,reasonCodes:['invalid_configuration']};const c=r.normalized,roleTargeted=c.terrainRoles===null?null:c.terrainRoles.includes(role);return{visible:protectedField?true:c.visibleOnTerrain,readonly:protectedField?true:c.readonlyOnTerrain,section:c.terrainSection,order:c.terrainDisplayOrder,roleTargeted,reasonCodes:[protectedField?'protected_field':c.visibleOnTerrain===null?'inherited_visibility':c.visibleOnTerrain?'future_visible':'future_hidden',c.readonlyOnTerrain===null?'inherited_readonly':c.readonlyOnTerrain?'future_readonly':'no_added_readonly',roleTargeted===null?'inherited_roles':roleTargeted?'role_targeted':'role_not_targeted']};}
