-- TOS Display Manager — Bloc 9
-- Rapports finaux d'installation et communications clients.
-- Le rapport PDF est toujours joint. Aucune photo n'est intégrée au PDF.

create table if not exists public.communications_finales (
  id bigint generated by default as identity primary key,
  edt_id text,
  numero_edt text,
  campagne text,
  client text,
  destinataires text[] not null default '{}',
  cc text[] not null default '{}',
  objet text not null,
  statut text not null default 'En attente',
  report_path text not null,
  report_snapshot jsonb not null default '{}'::jsonb,
  provider_message_id text,
  erreur text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid()
);

create index if not exists communications_finales_edt_idx
on public.communications_finales(numero_edt);

create index if not exists communications_finales_created_at_idx
on public.communications_finales(created_at desc);

alter table public.communications_finales enable row level security;

drop policy if exists "communications_finales_read" on public.communications_finales;
create policy "communications_finales_read"
on public.communications_finales
for select
to authenticated
using (
  public.current_app_role() in ('Administrateur','Coordonnateur','Client-Admin','Client')
);

drop policy if exists "communications_finales_write" on public.communications_finales;
create policy "communications_finales_write"
on public.communications_finales
for insert
to authenticated
with check (
  public.current_app_role() in ('Administrateur','Coordonnateur')
);

drop policy if exists "communications_finales_update" on public.communications_finales;
create policy "communications_finales_update"
on public.communications_finales
for update
to authenticated
using (
  public.current_app_role() in ('Administrateur','Coordonnateur')
)
with check (
  public.current_app_role() in ('Administrateur','Coordonnateur')
);

grant select, insert, update on public.communications_finales to authenticated;
grant usage, select on sequence public.communications_finales_id_seq to authenticated;

insert into storage.buckets(id, name, public)
values ('final-reports', 'final-reports', false)
on conflict(id) do update set public = false;

drop policy if exists "final_reports_authenticated_read" on storage.objects;
create policy "final_reports_authenticated_read"
on storage.objects
for select
to authenticated
using (bucket_id = 'final-reports');

drop policy if exists "final_reports_staff_insert" on storage.objects;
create policy "final_reports_staff_insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'final-reports'
  and public.current_app_role() in ('Administrateur','Coordonnateur')
);

drop policy if exists "final_reports_staff_update" on storage.objects;
create policy "final_reports_staff_update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'final-reports'
  and public.current_app_role() in ('Administrateur','Coordonnateur')
)
with check (
  bucket_id = 'final-reports'
  and public.current_app_role() in ('Administrateur','Coordonnateur')
);

alter table public.suivi_des_edt
add column if not exists rapport_final_envoye boolean not null default false;

alter table public.suivi_des_edt
add column if not exists rapport_final_path text;

alter table public.clients
add column if not exists courriels_rapport text;

alter table public.clients
add column if not exists courriels_cc text;

alter table public.clients
add column if not exists logo_url text;

alter table public.clients
add column if not exists couleur_rapport text default '#4c1d95';

alter table public.clients
add column if not exists mention_legale text;

create or replace function public.diagnostic_rapports_v09()
returns table(
  communications_total bigint,
  communications_envoyees bigint,
  communications_echec bigint,
  edt_avec_rapport bigint
)
language sql
security definer
set search_path = public
as $$
  select
    (select count(*) from public.communications_finales),
    (select count(*) from public.communications_finales where statut = 'Envoyé'),
    (select count(*) from public.communications_finales where statut = 'Échec'),
    (select count(*) from public.suivi_des_edt where rapport_final_envoye = true);
$$;

grant execute on function public.diagnostic_rapports_v09()
to authenticated;
