-- TOS Display Manager — Bloc 10
-- Édition universelle, audit des changements, photos et inventaire.

create table if not exists public.admin_change_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_key text,
  field_name text not null,
  old_value jsonb,
  new_value jsonb,
  changed_by uuid default auth.uid(),
  changed_by_email text,
  changed_at timestamptz not null default now()
);

create index if not exists admin_change_log_table_idx
on public.admin_change_log(table_name, changed_at desc);

alter table public.admin_change_log enable row level security;

drop policy if exists "admin_change_log_admin_read" on public.admin_change_log;
create policy "admin_change_log_admin_read"
on public.admin_change_log
for select
to authenticated
using (public.current_app_role() = 'Administrateur');

grant select on public.admin_change_log to authenticated;
grant usage, select on sequence public.admin_change_log_id_seq to authenticated;

create or replace function public.tdm_audit_row_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  old_json jsonb := to_jsonb(old);
  new_json jsonb := to_jsonb(new);
  key_name text;
  key_value text;
  field_record record;
  caller_email text;
begin
  if tg_table_name = 'admin_change_log' then
    return new;
  end if;

  key_name :=
    case
      when new_json ? 'id' then 'id'
      when new_json ? 'support_id' then 'support_id'
      when new_json ? 'no_arret' then 'no_arret'
      when new_json ? 'uuid' then 'uuid'
      else null
    end;

  key_value := case when key_name is null then null else new_json ->> key_name end;

  select email into caller_email
  from auth.users
  where id = auth.uid();

  for field_record in
    select n.key, o.value as old_value, n.value as new_value
    from jsonb_each(new_json) n
    left join jsonb_each(old_json) o on o.key = n.key
    where n.value is distinct from o.value
      and n.key not in ('updated_at', 'created_at')
  loop
    insert into public.admin_change_log(
      table_name,
      record_key,
      field_name,
      old_value,
      new_value,
      changed_by,
      changed_by_email
    )
    values(
      tg_table_name,
      key_value,
      field_record.key,
      field_record.old_value,
      field_record.new_value,
      auth.uid(),
      caller_email
    );
  end loop;

  return new;
end;
$$;

do $$
declare
  table_record record;
begin
  for table_record in
    select c.relname as table_name
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relkind in ('r','p')
      and c.relname not in (
        'admin_change_log',
        'spatial_ref_sys',
        'schema_migrations'
      )
  loop
    execute format(
      'grant update on table public.%I to authenticated',
      table_record.table_name
    );

    if (
      select relrowsecurity
      from pg_class
      where oid = format('public.%I', table_record.table_name)::regclass
    ) then
      execute format(
        'drop policy if exists "tdm_admin_universal_update" on public.%I',
        table_record.table_name
      );
      execute format(
        'create policy "tdm_admin_universal_update" on public.%I for update to authenticated using (public.current_app_role() = ''Administrateur'') with check (public.current_app_role() = ''Administrateur'')',
        table_record.table_name
      );
    end if;

    execute format(
      'drop trigger if exists tdm_audit_row_changes on public.%I',
      table_record.table_name
    );
    execute format(
      'create trigger tdm_audit_row_changes after update on public.%I for each row execute function public.tdm_audit_row_changes()',
      table_record.table_name
    );
  end loop;
end $$;

alter table public.support_photos
add column if not exists est_principale boolean not null default false;

alter table public.support_photos
add column if not exists commentaire_validation text;

alter table public.support_photos
add column if not exists validee_le timestamptz;

alter table public.support_photos
add column if not exists validee_par uuid;

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  visual_id bigint,
  item_reference text,
  movement_type text not null check (
    movement_type in ('Entrée','Installation','Retrait','Retour','Ajustement')
  ),
  quantity numeric not null default 0,
  edt_number text,
  support_id text,
  notes text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

alter table public.inventory_movements enable row level security;

drop policy if exists "inventory_movements_read" on public.inventory_movements;
create policy "inventory_movements_read"
on public.inventory_movements
for select
to authenticated
using (true);

drop policy if exists "inventory_movements_staff_write" on public.inventory_movements;
create policy "inventory_movements_staff_write"
on public.inventory_movements
for insert
to authenticated
with check (
  public.current_app_role() in ('Administrateur','Coordonnateur')
);

grant select, insert on public.inventory_movements to authenticated;
grant usage, select on sequence public.inventory_movements_id_seq to authenticated;

create or replace function public.sync_infrastructure_photo_thumbnail()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.est_principale = true then
    update public.support_photos
    set est_principale = false
    where support_id = new.support_id
      and id <> new.id
      and est_principale = true;
  end if;

  if new.support_id is not null
     and new.statut_validation = 'Validée'
     and coalesce(new.thumbnail_url, new.photo_url) is not null
     and (
       new.est_principale = true
       or not exists (
         select 1
         from public.support_photos p
         where p.support_id = new.support_id
           and p.est_principale = true
           and p.id <> new.id
       )
     )
  then
    update public.infrastructures
    set
      photo_miniature_url = coalesce(new.thumbnail_url, new.photo_url),
      photo_principale_url = coalesce(new.photo_url, new.thumbnail_url),
      visuel_actuel_cadre = coalesce(new.thumbnail_url, new.photo_url),
      updated_at = now()
    where support_id = new.support_id;
  end if;

  return new;
end;
$$;

drop trigger if exists support_photos_sync_infrastructure_thumbnail
on public.support_photos;

create trigger support_photos_sync_infrastructure_thumbnail
after insert or update of
  thumbnail_url,
  photo_url,
  statut_validation,
  est_principale
on public.support_photos
for each row
execute function public.sync_infrastructure_photo_thumbnail();

create or replace function public.diagnostic_bloc10()
returns table(
  modifications_journalisees bigint,
  photos_a_valider bigint,
  photos_principales bigint,
  mouvements_inventaire bigint
)
language sql
security definer
set search_path = public
as $$
  select
    (select count(*) from public.admin_change_log),
    (select count(*) from public.support_photos where statut_validation = 'À valider'),
    (select count(*) from public.support_photos where est_principale = true),
    (select count(*) from public.inventory_movements);
$$;

grant execute on function public.diagnostic_bloc10() to authenticated;
