-- TOS Display Manager — Bloc 11
-- EDT complets, requêtes clients, phases, assignations, bons de travail et historique.

create table if not exists public.requetes_clients (
  id bigint generated by default as identity primary key,
  client text,
  demandeur_nom text,
  demandeur_courriel text,
  type_requete text not null default 'Installation',
  priorite text not null default 'Normale',
  support_id text,
  description text,
  statut text not null default 'Nouvelle',
  bon_de_travail_id bigint,
  converted_at timestamptz,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.edt_phases (
  id bigint generated by default as identity primary key,
  edt_id bigint not null references public.suivi_des_edt(id) on delete cascade,
  nom text not null,
  ordre integer not null default 1,
  statut text not null default 'À faire',
  date_debut_prevue date,
  date_fin_prevue date,
  date_debut_reelle timestamptz,
  date_fin_reelle timestamptz,
  progression integer not null default 0 check (progression between 0 and 100),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.edt_assignments (
  id bigint generated by default as identity primary key,
  edt_id bigint not null references public.suivi_des_edt(id) on delete cascade,
  user_id bigint,
  user_email text not null,
  role_assignment text not null default 'Installateur',
  date_debut date,
  date_fin date,
  statut text not null default 'Assigné',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(edt_id, user_email, role_assignment)
);

create table if not exists public.operations_history (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text,
  entity_reference text,
  action text not null,
  old_data jsonb,
  new_data jsonb,
  details text,
  user_id uuid default auth.uid(),
  user_email text,
  created_at timestamptz not null default now()
);

alter table public.suivi_des_edt add column if not exists nom text;
alter table public.suivi_des_edt add column if not exists campagne text;
alter table public.suivi_des_edt add column if not exists client text;
alter table public.suivi_des_edt add column if not exists statut text default 'Planifié';
alter table public.suivi_des_edt add column if not exists priorite text default 'Normale';
alter table public.suivi_des_edt add column if not exists date_debut date;
alter table public.suivi_des_edt add column if not exists date_fin_prevue date;
alter table public.suivi_des_edt add column if not exists date_fin date;
alter table public.suivi_des_edt add column if not exists coordonnateur text;
alter table public.suivi_des_edt add column if not exists supports_prevus integer default 0;
alter table public.suivi_des_edt add column if not exists supports_installes integer default 0;
alter table public.suivi_des_edt add column if not exists progression integer default 0;
alter table public.suivi_des_edt add column if not exists description text;
alter table public.suivi_des_edt add column if not exists updated_at timestamptz default now();

alter table public.bons_de_travail add column if not exists edt_id bigint references public.suivi_des_edt(id) on delete set null;
alter table public.bons_de_travail add column if not exists phase_id bigint references public.edt_phases(id) on delete set null;
alter table public.bons_de_travail add column if not exists requete_client_id bigint references public.requetes_clients(id) on delete set null;
alter table public.bons_de_travail add column if not exists progression integer default 0;
alter table public.bons_de_travail add column if not exists date_debut_reelle timestamptz;
alter table public.bons_de_travail add column if not exists date_fin_reelle timestamptz;
alter table public.bons_de_travail add column if not exists validation_statut text default 'Non validé';
alter table public.bons_de_travail add column if not exists validation_par text;
alter table public.bons_de_travail add column if not exists validation_le timestamptz;

create index if not exists requetes_clients_statut_idx on public.requetes_clients(statut, created_at desc);
create index if not exists edt_phases_edt_idx on public.edt_phases(edt_id, ordre);
create index if not exists edt_assignments_edt_idx on public.edt_assignments(edt_id);
create index if not exists bons_de_travail_edt_idx on public.bons_de_travail(edt_id, statut);
create index if not exists operations_history_entity_idx on public.operations_history(entity_type, entity_id, created_at desc);

alter table public.requetes_clients enable row level security;
alter table public.edt_phases enable row level security;
alter table public.edt_assignments enable row level security;
alter table public.operations_history enable row level security;

drop policy if exists "requetes_clients_read" on public.requetes_clients;
create policy "requetes_clients_read" on public.requetes_clients
for select to authenticated using (true);

drop policy if exists "requetes_clients_create" on public.requetes_clients;
create policy "requetes_clients_create" on public.requetes_clients
for insert to authenticated with check (
  public.current_app_role() in ('Administrateur','Coordonnateur','Client-Admin','Client')
);

drop policy if exists "requetes_clients_manage" on public.requetes_clients;
create policy "requetes_clients_manage" on public.requetes_clients
for update to authenticated
using (public.current_app_role() in ('Administrateur','Coordonnateur'))
with check (public.current_app_role() in ('Administrateur','Coordonnateur'));

drop policy if exists "edt_phases_read" on public.edt_phases;
create policy "edt_phases_read" on public.edt_phases
for select to authenticated using (true);

drop policy if exists "edt_phases_manage" on public.edt_phases;
create policy "edt_phases_manage" on public.edt_phases
for all to authenticated
using (public.current_app_role() in ('Administrateur','Coordonnateur'))
with check (public.current_app_role() in ('Administrateur','Coordonnateur'));

drop policy if exists "edt_assignments_read" on public.edt_assignments;
create policy "edt_assignments_read" on public.edt_assignments
for select to authenticated using (true);

drop policy if exists "edt_assignments_manage" on public.edt_assignments;
create policy "edt_assignments_manage" on public.edt_assignments
for all to authenticated
using (public.current_app_role() in ('Administrateur','Coordonnateur'))
with check (public.current_app_role() in ('Administrateur','Coordonnateur'));

drop policy if exists "operations_history_read" on public.operations_history;
create policy "operations_history_read" on public.operations_history
for select to authenticated using (
  public.current_app_role() in ('Administrateur','Coordonnateur')
);

grant select, insert, update on public.requetes_clients to authenticated;
grant select, insert, update, delete on public.edt_phases to authenticated;
grant select, insert, update, delete on public.edt_assignments to authenticated;
grant select on public.operations_history to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.tdm_operations_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  ref text;
  email_value text;
begin
  select email into email_value from auth.users where id = auth.uid();

  ref := coalesce(
    to_jsonb(new)->>'no_edt',
    to_jsonb(new)->>'no_bt',
    to_jsonb(new)->>'id',
    to_jsonb(old)->>'no_edt',
    to_jsonb(old)->>'no_bt',
    to_jsonb(old)->>'id'
  );

  insert into public.operations_history(
    entity_type,
    entity_id,
    entity_reference,
    action,
    old_data,
    new_data,
    details,
    user_id,
    user_email
  )
  values(
    tg_table_name,
    coalesce(to_jsonb(new)->>'id', to_jsonb(old)->>'id'),
    ref,
    tg_op,
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    case when tg_op = 'DELETE' then null else to_jsonb(new) end,
    null,
    auth.uid(),
    email_value
  );

  return coalesce(new, old);
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'suivi_des_edt',
    'bons_de_travail',
    'requetes_clients',
    'edt_phases',
    'edt_assignments'
  ]
  loop
    execute format('drop trigger if exists tdm_operations_audit on public.%I', table_name);
    execute format(
      'create trigger tdm_operations_audit after insert or update or delete on public.%I for each row execute function public.tdm_operations_audit()',
      table_name
    );
  end loop;
end $$;

create or replace function public.refresh_edt_progress(p_edt_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  computed integer;
  installed integer;
begin
  select coalesce(round(avg(
    case
      when statut = 'Terminée' then 100
      else coalesce(progression, 0)
    end
  )), 0)::integer,
  count(*) filter (where statut = 'Terminée')
  into computed, installed
  from public.bons_de_travail
  where edt_id = p_edt_id;

  update public.suivi_des_edt
  set
    progression = computed,
    supports_installes = installed,
    updated_at = now()
  where id = p_edt_id;

  return computed;
end;
$$;

create or replace function public.sync_edt_progress_from_work_order()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.edt_id is not null then
    perform public.refresh_edt_progress(new.edt_id);
  end if;
  if tg_op = 'UPDATE' and old.edt_id is distinct from new.edt_id and old.edt_id is not null then
    perform public.refresh_edt_progress(old.edt_id);
  end if;
  return new;
end;
$$;

drop trigger if exists sync_edt_progress_from_work_order on public.bons_de_travail;
create trigger sync_edt_progress_from_work_order
after insert or update of statut, progression, edt_id
on public.bons_de_travail
for each row execute function public.sync_edt_progress_from_work_order();

create or replace function public.diagnostic_bloc11()
returns table(
  edt_total bigint,
  edt_actifs bigint,
  bt_ouverts bigint,
  requetes_nouvelles bigint,
  assignations_actives bigint
)
language sql
security definer
set search_path = public
as $$
  select
    (select count(*) from public.suivi_des_edt),
    (select count(*) from public.suivi_des_edt where statut not in ('Terminé','Annulé')),
    (select count(*) from public.bons_de_travail where statut not in ('Terminée','Annulée')),
    (select count(*) from public.requetes_clients where statut = 'Nouvelle'),
    (select count(*) from public.edt_assignments where statut <> 'Retiré');
$$;

grant execute on function public.diagnostic_bloc11() to authenticated;
