create table if not exists public.terrain_sync_diagnostics(id uuid primary key default gen_random_uuid(),reference text not null,support_id text,visuel_id bigint,utilisateur text,etape text not null,statut text not null,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.terrain_sync_diagnostics enable row level security;
drop policy if exists "terrain_sync_diagnostics_read" on public.terrain_sync_diagnostics;
create policy "terrain_sync_diagnostics_read" on public.terrain_sync_diagnostics for select to authenticated using(public.current_app_role() in ('Administrateur','Coordonnateur','Installateur'));
grant select on public.terrain_sync_diagnostics to authenticated;

create or replace function public.finaliser_installation_terrain_v0127(p_support_id text,p_visuel_id bigint,p_nom_fichier text,p_storage_path text,p_photo_url text,p_utilisateur text default null,p_commentaires text default null,p_idempotency_key text default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare v public.campagne_visuels_formats%rowtype;c public.campagnes_maitres%rowtype;i public.infrastructures%rowtype;p public.support_photos%rowtype;reference text:=coalesce(nullif(trim(p_idempotency_key),''),'TERRAIN-'||to_char(clock_timestamp(),'YYYYMMDD-HH24MISS-MS'));h_count bigint;begin
insert into public.terrain_sync_diagnostics(reference,support_id,visuel_id,utilisateur,etape,statut) values(reference,p_support_id,p_visuel_id,p_utilisateur,'Début','En cours');
select * into v from public.campagne_visuels_formats where id=p_visuel_id and actif=true;if not found then raise exception 'Visuel actif introuvable';end if;
select * into c from public.campagnes_maitres where id=v.campagne_id;if not found then raise exception 'Campagne introuvable';end if;
select * into i from public.infrastructures where support_id=p_support_id for update;if not found then raise exception 'Support % introuvable',p_support_id;end if;
if exists(select 1 from public.support_photos where support_id=p_support_id and storage_path=p_storage_path) then select * into p from public.support_photos where support_id=p_support_id and storage_path=p_storage_path order by id desc limit 1;else update public.support_photos set est_principale=false where support_id=p_support_id and est_principale=true;insert into public.support_photos(support_id,campagne_id,visuel_id,type_photo,nom_fichier,storage_path,photo_url,thumbnail_url,prise_le,utilisateur,statut_validation,est_principale,validee_le) values(p_support_id,c.id,v.id,'Installation',p_nom_fichier,p_storage_path,p_photo_url,p_photo_url,now(),p_utilisateur,'Validée',true,now()) returning * into p;end if;
update public.infrastructures set campagne_precedente=case when campagne_actuelle is distinct from c.nom_campagne then campagne_actuelle else campagne_precedente end,campagne_actuelle=c.nom_campagne,campagne_selon_visuel=c.nom_campagne,visuel_campagne=v.nom_visuel,visuel_en_expo=v.nom_visuel,visuel_actuel_cadre=p_photo_url,visuel_id=v.id,phase_campagne=v.phase,format_visuel=v.format_support,edt_associe=coalesce(c.no_edt,edt_associe),photo_principale_url=p_photo_url,photo_miniature_url=p_photo_url,commentaires=coalesce(p_commentaires,commentaires),updated_at=now() where support_id=p_support_id returning * into i;
if i.support_id is null or coalesce(i.campagne_actuelle,'')<>coalesce(c.nom_campagne,'') or coalesce(i.visuel_campagne,'')<>coalesce(v.nom_visuel,'') or coalesce(i.visuel_actuel_cadre,'')<>coalesce(p_photo_url,'') or coalesce(i.photo_principale_url,'')<>coalesce(p_photo_url,'') then raise exception 'Vérification Infrastructure échouée';end if;
insert into public.historique_des_campagnes(support_id,campagne,visuel,no_edt,date_installation,photo_installation,utilisateur,raw_data) values(p_support_id,c.nom_campagne,v.nom_visuel,c.no_edt,now()::text,p_photo_url,p_utilisateur,jsonb_build_object('reference',reference,'photo_id',p.id,'source','Application terrain v0.12.7'));
select count(*) into h_count from public.historique_des_campagnes where support_id=p_support_id and raw_data->>'reference'=reference;if h_count<>1 then raise exception 'Historique non confirmé';end if;
update public.terrain_sync_diagnostics set etape='Finalisation',statut='Réussi',details=jsonb_build_object('campagne',c.nom_campagne,'visuel',v.nom_visuel,'edt',c.no_edt,'photo_id',p.id),created_at=now() where id=(select id from public.terrain_sync_diagnostics d where d.reference=reference order by created_at desc limit 1);
return jsonb_build_object('ok',true,'reference',reference,'message','Installation confirmée','support_id',p_support_id,'campagne',c.nom_campagne,'visuel',v.nom_visuel,'edt',c.no_edt,'photo_id',p.id);
exception when others then update public.terrain_sync_diagnostics set etape='Finalisation',statut='Échec',details=jsonb_build_object('erreur',sqlerrm),created_at=now() where id=(select id from public.terrain_sync_diagnostics d where d.reference=reference order by created_at desc limit 1);raise exception 'Installation annulée [%] : %',reference,sqlerrm;end;$$;
grant execute on function public.finaliser_installation_terrain_v0127(text,bigint,text,text,text,text,text,text) to authenticated;
