-- TOS Display Manager v0.12.9 — Lot 2
-- Moteur exécutable du Studio des relations.
-- À exécuter APRÈS V0_12_9_LOT1_MOTEUR_EDT_ENTERPRISE.sql.

begin;

create table if not exists public.relation_execution_logs (
  id bigint generated by default as identity primary key,
  operation_id uuid not null default gen_random_uuid(),
  rule_id bigint references public.relation_rules(id) on delete set null,
  source_table text,
  source_field text,
  destination_table text,
  destination_field text,
  source_key_value text,
  status text not null,
  message text,
  old_value jsonb,
  new_value jsonb,
  context jsonb not null default '{}'::jsonb,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);
create index if not exists relation_execution_logs_rule_idx on public.relation_execution_logs(rule_id,created_at desc);
create index if not exists relation_execution_logs_operation_idx on public.relation_execution_logs(operation_id);
alter table public.relation_execution_logs enable row level security;
drop policy if exists relation_execution_logs_read on public.relation_execution_logs;
create policy relation_execution_logs_read on public.relation_execution_logs for select to authenticated using (true);
grant select on public.relation_execution_logs to authenticated;

alter table public.relation_rules add column if not exists propagation_mode text not null default 'automatique';
alter table public.relation_rules add column if not exists last_executed_at timestamptz;
alter table public.relation_rules add column if not exists execution_count bigint not null default 0;
alter table public.relation_rules add column if not exists last_error text;

create or replace function public.tdm_relation_column_exists(p_table text,p_column text)
returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from information_schema.columns where table_schema='public' and table_name=p_table and column_name=p_column)
$$;

create or replace function public.tdm_default_relation_key(p_table text)
returns text language plpgsql stable security definer set search_path=public as $$
begin
 if public.tdm_relation_column_exists(p_table,'support_id') then return 'support_id'; end if;
 if public.tdm_relation_column_exists(p_table,'id') then return 'id'; end if;
 return null;
end;$$;

create or replace function public.executer_relation_rule_v0129(
 p_rule_id bigint,
 p_source_record jsonb,
 p_dry_run boolean default false,
 p_operation_id uuid default gen_random_uuid()
) returns jsonb language plpgsql security definer set search_path=public as $$
declare
 r public.relation_rules%rowtype;
 v_source_key text;
 v_destination_key text;
 v_key_value text;
 v_source_value jsonb;
 v_old_value jsonb;
 v_count integer:=0;
 v_sql text;
 v_where jsonb;
begin
 select * into r from public.relation_rules where id=p_rule_id;
 if not found then raise exception 'Relation introuvable.'; end if;
 if not r.enabled then return jsonb_build_object('ok',false,'skipped',true,'message','Relation désactivée'); end if;
 if r.requires_confirmation and not p_dry_run then
   return jsonb_build_object('ok',false,'skipped',true,'message','Confirmation requise');
 end if;
 if not public.tdm_relation_column_exists(r.source_table,r.source_field) then raise exception 'Champ source inexistant: %.%',r.source_table,r.source_field; end if;
 if not public.tdm_relation_column_exists(r.destination_table,r.destination_field) then raise exception 'Champ destination inexistant: %.%',r.destination_table,r.destination_field; end if;

 v_source_key:=coalesce(nullif(r.condition_json->>'source_key',''),public.tdm_default_relation_key(r.source_table));
 v_destination_key:=coalesce(nullif(r.condition_json->>'destination_key',''),public.tdm_default_relation_key(r.destination_table));
 if v_source_key is null or v_destination_key is null then raise exception 'Clé de correspondance absente. Configure source_key et destination_key.'; end if;
 if not public.tdm_relation_column_exists(r.source_table,v_source_key) then raise exception 'Clé source inexistante: %.%',r.source_table,v_source_key; end if;
 if not public.tdm_relation_column_exists(r.destination_table,v_destination_key) then raise exception 'Clé destination inexistante: %.%',r.destination_table,v_destination_key; end if;

 v_key_value:=p_source_record->>v_source_key;
 v_source_value:=p_source_record->r.source_field;
 if v_key_value is null then raise exception 'Valeur de clé source absente (%).',v_source_key; end if;

 execute format('select to_jsonb(%1$I) from public.%2$I where %3$I::text=$1 limit 1',r.destination_field,r.destination_table,v_destination_key)
 into v_old_value using v_key_value;

 if p_dry_run then
   insert into public.relation_execution_logs(operation_id,rule_id,source_table,source_field,destination_table,destination_field,source_key_value,status,message,old_value,new_value,context)
   values(p_operation_id,r.id,r.source_table,r.source_field,r.destination_table,r.destination_field,v_key_value,'Simulation','Aucune donnée modifiée',v_old_value,v_source_value,jsonb_build_object('source_key',v_source_key,'destination_key',v_destination_key));
   return jsonb_build_object('ok',true,'dry_run',true,'matches',case when v_old_value is null then 0 else 1 end,'old_value',v_old_value,'new_value',v_source_value);
 end if;

 -- jsonb_populate_record assure la conversion vers le type réel de la colonne destination.
 v_sql:=format('update public.%1$I d set %2$I = (jsonb_populate_record(null::public.%1$I, jsonb_build_object(%3$L,$1))).%2$I where d.%4$I::text=$2',r.destination_table,r.destination_field,r.destination_field,v_destination_key);
 execute v_sql using v_source_value,v_key_value;
 get diagnostics v_count=row_count;

 update public.relation_rules set last_executed_at=now(),execution_count=execution_count+1,last_error=null,updated_at=now() where id=r.id;
 insert into public.relation_execution_logs(operation_id,rule_id,source_table,source_field,destination_table,destination_field,source_key_value,status,message,old_value,new_value,context)
 values(p_operation_id,r.id,r.source_table,r.source_field,r.destination_table,r.destination_field,v_key_value,case when v_count>0 then 'Réussi' else 'Sans correspondance' end,v_count||' ligne(s) mise(s) à jour',v_old_value,v_source_value,jsonb_build_object('source_key',v_source_key,'destination_key',v_destination_key));
 return jsonb_build_object('ok',true,'updated',v_count,'operation_id',p_operation_id);
exception when others then
 update public.relation_rules set last_error=sqlerrm,updated_at=now() where id=p_rule_id;
 insert into public.relation_execution_logs(operation_id,rule_id,status,message,context) values(p_operation_id,p_rule_id,'Erreur',sqlerrm,jsonb_build_object('source_record',p_source_record));
 raise;
end;$$;

grant execute on function public.executer_relation_rule_v0129(bigint,jsonb,boolean,uuid) to authenticated;

create or replace function public.tdm_relation_source_trigger_v0129()
returns trigger language plpgsql security definer set search_path=public as $$
declare r record; v_new jsonb:=to_jsonb(new); v_old jsonb:=case when tg_op='UPDATE' then to_jsonb(old) else '{}'::jsonb end;
begin
 if pg_trigger_depth()>1 then return new; end if;
 for r in select * from public.relation_rules where enabled=true and requires_confirmation=false and propagation_mode='automatique' and source_table=tg_table_name loop
   if tg_op='INSERT' or (v_new->r.source_field is distinct from v_old->r.source_field) then
     perform public.executer_relation_rule_v0129(r.id,v_new,false,gen_random_uuid());
   end if;
 end loop;
 return new;
end;$$;

create or replace function public.installer_declencheurs_relations_v0129()
returns jsonb language plpgsql security definer set search_path=public as $$
declare t text; n integer:=0;
begin
 if public.current_app_role()<>'Administrateur' then raise exception 'Permission administrateur requise.'; end if;
 for t in select distinct source_table from public.relation_rules where enabled=true and source_table not in ('relation_rules','relation_fields','relation_execution_logs','relation_test_logs') loop
   if to_regclass('public.'||quote_ident(t)) is not null then
     execute format('drop trigger if exists tdm_relation_auto_v0129 on public.%I',t);
     execute format('create trigger tdm_relation_auto_v0129 after insert or update on public.%I for each row execute function public.tdm_relation_source_trigger_v0129()',t);
     n:=n+1;
   end if;
 end loop;
 return jsonb_build_object('ok',true,'tables_equipees',n);
end;$$;
grant execute on function public.installer_declencheurs_relations_v0129() to authenticated;

create or replace function public.test_relation_rule(p_rule_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare r public.relation_rules%rowtype; sk text; dk text;
begin
 select * into r from public.relation_rules where id=p_rule_id;
 if not found then raise exception 'Relation introuvable.'; end if;
 sk:=coalesce(nullif(r.condition_json->>'source_key',''),public.tdm_default_relation_key(r.source_table));
 dk:=coalesce(nullif(r.condition_json->>'destination_key',''),public.tdm_default_relation_key(r.destination_table));
 if not public.tdm_relation_column_exists(r.source_table,r.source_field) then raise exception 'Champ source inexistant'; end if;
 if not public.tdm_relation_column_exists(r.destination_table,r.destination_field) then raise exception 'Champ destination inexistant'; end if;
 if sk is null or dk is null then raise exception 'Clés de correspondance non configurées'; end if;
 insert into public.relation_test_logs(rule_id,status,message,details) values(r.id,'Réussi','Relation exécutable.',jsonb_build_object('source_key',sk,'destination_key',dk));
 return jsonb_build_object('status','Réussi','message','Relation valide et exécutable.','source_key',sk,'destination_key',dk);
end;$$;

-- Relations métier préconfigurées avec clés explicites quand elles sont directement exécutables.
update public.relation_rules set condition_json=coalesce(condition_json,'{}'::jsonb)||jsonb_build_object('source_key','support_id','destination_key','support_id')
where source_table in ('infrastructures','historique_des_campagnes','support_photos','enjeux_terrain','edt_supports')
  and destination_table in ('infrastructures','historique_des_campagnes','support_photos','enjeux_terrain','edt_supports')
  and public.tdm_relation_column_exists(source_table,'support_id') and public.tdm_relation_column_exists(destination_table,'support_id');

commit;
