-- TOS Display Manager v0.12.9 — Lot 1
-- Moteur EDT Enterprise : ciblage des supports, génération des BT,
-- progression automatique, propagation Infrastructure et diagnostic.

begin;

-- Conversion tolérante des dates historiques stockées en TEXT.
create or replace function public.tdm_try_date(p_value text)
returns date language plpgsql immutable as $$
begin
  if p_value is null or btrim(p_value) = '' then return null; end if;
  begin return p_value::date; exception when others then return null; end;
end;$$;

create table if not exists public.edt_supports (
  id bigint generated by default as identity primary key,
  edt_id bigint not null references public.suivi_des_edt(id) on delete cascade,
  phase_id bigint references public.edt_phases(id) on delete set null,
  support_id text not null references public.infrastructures(support_id) on update cascade on delete restrict,
  statut text not null default 'Planifié',
  priorite text not null default 'Normale',
  assigne_a text,
  date_cible date,
  bon_de_travail_id bigint references public.bons_de_travail(id) on delete set null,
  progression integer not null default 0 check (progression between 0 and 100),
  bloque boolean not null default false,
  motif_blocage text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (edt_id, support_id)
);

create index if not exists edt_supports_edt_idx on public.edt_supports(edt_id, statut);
create index if not exists edt_supports_phase_idx on public.edt_supports(phase_id, statut);
create index if not exists edt_supports_support_idx on public.edt_supports(support_id);
create index if not exists edt_supports_bt_idx on public.edt_supports(bon_de_travail_id);

alter table public.suivi_des_edt add column if not exists supports_planifies integer default 0;
alter table public.suivi_des_edt add column if not exists supports_en_cours integer default 0;
alter table public.suivi_des_edt add column if not exists supports_bloques integer default 0;
alter table public.suivi_des_edt add column if not exists supports_termines integer default 0;
alter table public.suivi_des_edt add column if not exists derniere_synchro timestamptz;

alter table public.bons_de_travail add column if not exists edt_support_id bigint references public.edt_supports(id) on delete set null;
create unique index if not exists bons_de_travail_edt_support_unique
  on public.bons_de_travail(edt_support_id)
  where edt_support_id is not null;

alter table public.edt_supports enable row level security;

drop policy if exists "edt_supports_read" on public.edt_supports;
create policy "edt_supports_read" on public.edt_supports
for select to authenticated using (true);

drop policy if exists "edt_supports_manage" on public.edt_supports;
create policy "edt_supports_manage" on public.edt_supports
for all to authenticated
using (public.current_app_role() in ('Administrateur','Coordonnateur'))
with check (public.current_app_role() in ('Administrateur','Coordonnateur'));

grant select, insert, update, delete on public.edt_supports to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.refresh_edt_enterprise(p_edt_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total integer := 0;
  v_planifies integer := 0;
  v_en_cours integer := 0;
  v_bloques integer := 0;
  v_termines integer := 0;
  v_progression integer := 0;
  v_phase record;
begin
  select
    count(*)::integer,
    count(*) filter (where statut in ('Planifié','À faire'))::integer,
    count(*) filter (where statut in ('En cours','Démarré'))::integer,
    count(*) filter (where bloque = true or statut = 'Bloqué')::integer,
    count(*) filter (where statut in ('Terminé','Terminée','Complété','Complétée'))::integer,
    coalesce(round(avg(
      case
        when statut in ('Terminé','Terminée','Complété','Complétée') then 100
        else coalesce(progression,0)
      end
    )),0)::integer
  into v_total, v_planifies, v_en_cours, v_bloques, v_termines, v_progression
  from public.edt_supports
  where edt_id = p_edt_id;

  -- Recalcule chaque phase à partir des supports réellement affectés.
  for v_phase in select id from public.edt_phases where edt_id = p_edt_id loop
    update public.edt_phases p
       set progression = coalesce((
             select round(avg(case
               when es.statut in ('Terminé','Terminée','Complété','Complétée') then 100
               else coalesce(es.progression,0)
             end))::integer
             from public.edt_supports es
             where es.phase_id = p.id
           ),0),
           statut = case
             when not exists (select 1 from public.edt_supports es where es.phase_id = p.id) then p.statut
             when not exists (
               select 1 from public.edt_supports es
               where es.phase_id = p.id
                 and es.statut not in ('Terminé','Terminée','Complété','Complétée')
             ) then 'Terminée'
             when exists (
               select 1 from public.edt_supports es
               where es.phase_id = p.id and es.progression > 0
             ) then 'En cours'
             else 'À faire'
           end,
           updated_at = now()
     where p.id = v_phase.id;
  end loop;

  update public.suivi_des_edt
     set supports_prevus = v_total,
         supports_cibles = v_total,
         supports_planifies = v_planifies,
         supports_en_cours = v_en_cours,
         supports_bloques = v_bloques,
         supports_termines = v_termines,
         supports_installes = v_termines,
         supports_completes = v_termines,
         progression = v_progression,
         avancement = v_progression,
         statut = case
           when v_total > 0 and v_termines = v_total then 'Terminé'
           when v_en_cours > 0 or v_termines > 0 then 'En cours'
           else statut
         end,
         date_fin = case when v_total > 0 and v_termines = v_total then coalesce(date_fin, current_date) else date_fin end,
         derniere_synchro = now(),
         updated_at = now()
   where id = p_edt_id;

  return jsonb_build_object(
    'ok', true,
    'edt_id', p_edt_id,
    'supports_total', v_total,
    'planifies', v_planifies,
    'en_cours', v_en_cours,
    'bloques', v_bloques,
    'termines', v_termines,
    'progression', v_progression
  );
end;
$$;

create or replace function public.assigner_supports_edt_v0129(
  p_edt_id bigint,
  p_support_ids text[],
  p_phase_id bigint default null,
  p_priorite text default 'Normale',
  p_assigne_a text default null,
  p_date_cible date default null,
  p_generer_bt boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_edt public.suivi_des_edt%rowtype;
  v_support_id text;
  v_es public.edt_supports%rowtype;
  v_bt_id bigint;
  v_added integer := 0;
  v_skipped integer := 0;
  v_missing text[] := array[]::text[];
begin
  if public.current_app_role() not in ('Administrateur','Coordonnateur') then
    raise exception 'Permission insuffisante.';
  end if;

  select * into v_edt from public.suivi_des_edt where id = p_edt_id for update;
  if not found then raise exception 'EDT introuvable.'; end if;

  if p_phase_id is not null and not exists (
    select 1 from public.edt_phases where id = p_phase_id and edt_id = p_edt_id
  ) then
    raise exception 'La phase ne correspond pas à cet EDT.';
  end if;

  foreach v_support_id in array coalesce(p_support_ids, array[]::text[]) loop
    v_support_id := trim(v_support_id);
    if v_support_id = '' then continue; end if;

    if not exists (select 1 from public.infrastructures where support_id = v_support_id) then
      v_missing := array_append(v_missing, v_support_id);
      continue;
    end if;

    insert into public.edt_supports(
      edt_id, phase_id, support_id, statut, priorite, assigne_a, date_cible, updated_at
    ) values (
      p_edt_id, p_phase_id, v_support_id, 'Planifié', coalesce(p_priorite,'Normale'), p_assigne_a, p_date_cible, now()
    )
    on conflict (edt_id, support_id) do update
      set phase_id = coalesce(excluded.phase_id, edt_supports.phase_id),
          priorite = excluded.priorite,
          assigne_a = coalesce(excluded.assigne_a, edt_supports.assigne_a),
          date_cible = coalesce(excluded.date_cible, edt_supports.date_cible),
          updated_at = now()
    returning * into v_es;

    if p_generer_bt and v_es.bon_de_travail_id is null then
      insert into public.bons_de_travail(
        no_bt, type_bt, support_id, no_edt, edt_id, phase_id, edt_support_id,
        priorite, statut, assigne_a, date_cible, client, description, progression, updated_at
      ) values (
        'BT-' || regexp_replace(coalesce(v_edt.no_edt, p_edt_id::text), '[^A-Za-z0-9]', '', 'g') || '-' || v_support_id,
        'Installation', v_support_id, v_edt.no_edt, p_edt_id, p_phase_id, v_es.id,
        coalesce(p_priorite,'Normale'), 'À faire', p_assigne_a, p_date_cible, v_edt.client,
        'Travaux EDT ' || coalesce(v_edt.no_edt, p_edt_id::text) || ' — support ' || v_support_id,
        0, now()
      )
      on conflict (edt_support_id) where edt_support_id is not null do update
        set phase_id = excluded.phase_id,
            priorite = excluded.priorite,
            assigne_a = coalesce(excluded.assigne_a, bons_de_travail.assigne_a),
            date_cible = coalesce(excluded.date_cible, bons_de_travail.date_cible),
            updated_at = now()
      returning id into v_bt_id;

      update public.edt_supports set bon_de_travail_id = v_bt_id, updated_at = now() where id = v_es.id;
    end if;

    update public.infrastructures
       set prochain_edt_cible = v_edt.no_edt,
           updated_at = now()
     where support_id = v_support_id;

    v_added := v_added + 1;
  end loop;

  perform public.refresh_edt_enterprise(p_edt_id);

  return jsonb_build_object(
    'ok', true,
    'edt_id', p_edt_id,
    'supports_affectes', v_added,
    'supports_ignores', v_skipped,
    'supports_introuvables', to_jsonb(v_missing)
  );
end;
$$;

create or replace function public.retirer_support_edt_v0129(p_edt_id bigint, p_support_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_no_edt text;
  v_bt_id bigint;
begin
  if public.current_app_role() not in ('Administrateur','Coordonnateur') then
    raise exception 'Permission insuffisante.';
  end if;

  select no_edt into v_no_edt from public.suivi_des_edt where id = p_edt_id;
  select bon_de_travail_id into v_bt_id from public.edt_supports where edt_id=p_edt_id and support_id=p_support_id;

  delete from public.edt_supports where edt_id=p_edt_id and support_id=p_support_id;
  if v_bt_id is not null then delete from public.bons_de_travail where id=v_bt_id and statut in ('À faire','Planifié','Annulée'); end if;

  update public.infrastructures
     set prochain_edt_cible = nullif(prochain_edt_cible, v_no_edt), updated_at=now()
   where support_id=p_support_id;

  perform public.refresh_edt_enterprise(p_edt_id);
  return jsonb_build_object('ok',true,'edt_id',p_edt_id,'support_id',p_support_id);
end;
$$;

create or replace function public.sync_edt_support_from_bt_v0129()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.edt_support_id is not null then
    update public.edt_supports
       set statut = case
             when new.statut = 'Terminée' then 'Terminé'
             when new.statut = 'En cours' then 'En cours'
             when new.statut = 'Annulée' then 'Annulé'
             else 'Planifié'
           end,
           progression = case when new.statut='Terminée' then 100 else coalesce(new.progression,0) end,
           assigne_a = coalesce(new.assigne_a, assigne_a),
           date_cible = coalesce(public.tdm_try_date(new.date_cible::text), date_cible),
           completed_at = case when new.statut='Terminée' then coalesce(new.date_fin_reelle,now()) else null end,
           updated_at = now()
     where id = new.edt_support_id;
  end if;
  if new.edt_id is not null then perform public.refresh_edt_enterprise(new.edt_id); end if;
  return new;
end;
$$;

drop trigger if exists sync_edt_support_from_bt_v0129 on public.bons_de_travail;
create trigger sync_edt_support_from_bt_v0129
after insert or update of statut, progression, assigne_a, date_cible, date_fin_reelle
on public.bons_de_travail
for each row execute function public.sync_edt_support_from_bt_v0129();

create or replace function public.sync_bt_from_edt_support_v0129()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.bon_de_travail_id is not null then
    update public.bons_de_travail
       set phase_id = new.phase_id,
           assigne_a = new.assigne_a,
           priorite = new.priorite,
           date_cible = new.date_cible::text,
           progression = new.progression,
           statut = case
             when new.statut in ('Terminé','Terminée','Complété','Complétée') then 'Terminée'
             when new.statut='En cours' then 'En cours'
             when new.statut='Annulé' then 'Annulée'
             else 'À faire'
           end,
           updated_at = now()
     where id = new.bon_de_travail_id;
  end if;
  perform public.refresh_edt_enterprise(new.edt_id);
  return new;
end;
$$;

drop trigger if exists sync_bt_from_edt_support_v0129 on public.edt_supports;
create trigger sync_bt_from_edt_support_v0129
after update of phase_id, assigne_a, priorite, date_cible, progression, statut
on public.edt_supports
for each row execute function public.sync_bt_from_edt_support_v0129();

create or replace function public.tableau_bord_edt_v0129(p_edt_id bigint default null)
returns table(
  edt_id bigint, no_edt text, nom text, statut text, date_fin_prevue date,
  total integer, planifies integer, en_cours integer, bloques integer,
  termines integer, progression integer, en_retard boolean
)
language sql security definer set search_path = public as $$
  select e.id, e.no_edt::text, e.nom::text, e.statut::text,
         public.tdm_try_date(e.date_fin_prevue::text),
         coalesce(e.supports_prevus,0)::integer, coalesce(e.supports_planifies,0)::integer,
         coalesce(e.supports_en_cours,0)::integer, coalesce(e.supports_bloques,0)::integer,
         coalesce(e.supports_termines,0)::integer, coalesce(e.progression,0)::integer,
         (public.tdm_try_date(e.date_fin_prevue::text) < current_date and coalesce(e.progression,0) < 100)
  from public.suivi_des_edt e
  where p_edt_id is null or e.id = p_edt_id
  order by public.tdm_try_date(e.date_fin_prevue::text) nulls last, e.id desc;
$$;

grant execute on function public.refresh_edt_enterprise(bigint) to authenticated;
grant execute on function public.assigner_supports_edt_v0129(bigint,text[],bigint,text,text,date,boolean) to authenticated;
grant execute on function public.retirer_support_edt_v0129(bigint,text) to authenticated;
grant execute on function public.tableau_bord_edt_v0129(bigint) to authenticated;

-- Audit du nouveau registre EDT.
drop trigger if exists tdm_operations_audit on public.edt_supports;
create trigger tdm_operations_audit
after insert or update or delete on public.edt_supports
for each row execute function public.tdm_operations_audit();

commit;
