-- Phase 13.1-A7 — fichier local non exécuté. Aucun branchement à TerrainApp.
begin;
alter table public.relation_fields add column if not exists terrain_config jsonb not null default '{}'::jsonb;
comment on column public.relation_fields.terrain_config is 'Brouillon administratif TerrainConfig 1.0.0; aucune consommation Terrain réelle.';
do $$ begin
 if not exists(select 1 from pg_catalog.pg_constraint where conrelid='public.relation_fields'::pg_catalog.regclass and conname='relation_fields_terrain_config_object_v0131a7_check')then alter table public.relation_fields add constraint relation_fields_terrain_config_object_v0131a7_check check(pg_catalog.jsonb_typeof(terrain_config)='object')not valid;end if;
 if exists(select 1 from pg_catalog.pg_constraint where conrelid='public.relation_field_config_audit'::pg_catalog.regclass and conname='relation_field_config_audit_type_v0131a6_check')then alter table public.relation_field_config_audit drop constraint relation_field_config_audit_type_v0131a6_check;end if;
 if not exists(select 1 from pg_catalog.pg_constraint where conrelid='public.relation_field_config_audit'::pg_catalog.regclass and conname='relation_field_config_audit_type_v0131a7_check')then alter table public.relation_field_config_audit add constraint relation_field_config_audit_type_v0131a7_check check(configuration_type is null or configuration_type in('general','display','validation','permission','terrain'))not valid;end if;
end $$;
create or replace function public.normalize_terrain_config_v0131a7(p_config jsonb)returns jsonb language plpgsql immutable security invoker set search_path=pg_catalog as $$
declare v_key text;v_role text;v_roles jsonb;v_sections constant text[]:=array['Identification','Intervention','Inspection','Enjeu','Photos'];v_allowed_roles constant text[]:=array['Administrateur','Coordonnateur','Installateur'];v_critical constant jsonb:='["support_id","photo_principale_url","photo_miniature_url","visuel_actuel_cadre"]'::jsonb;v_section text;v_order integer;
begin
 if p_config is null or pg_catalog.jsonb_typeof(p_config)<>'object'then raise exception using message='TerrainConfig invalide.',detail='{"code":"invalid_payload"}';end if;
 for v_key in select pg_catalog.jsonb_object_keys(p_config)loop if v_key not in('visibleOnTerrain','readonlyOnTerrain','terrainRoles','terrainSection','terrainDisplayOrder','criticalFields')then raise exception using message='Propriété inconnue.',detail=pg_catalog.jsonb_build_object('code','unknown_property','field',v_key)::text;end if;end loop;
 foreach v_key in array array['visibleOnTerrain','readonlyOnTerrain']loop if p_config?v_key and p_config->v_key<>'null'::jsonb and pg_catalog.jsonb_typeof(p_config->v_key)<>'boolean'then raise exception using message='Booléen ou null attendu.',detail=pg_catalog.jsonb_build_object('code','invalid_boolean','field',v_key)::text;end if;end loop;
 v_roles:=coalesce(p_config->'terrainRoles','null'::jsonb);if v_roles<>'null'::jsonb then if pg_catalog.jsonb_typeof(v_roles)<>'array'then raise exception using message='Liste de rôles invalide.',detail='{"code":"invalid_roles"}';end if;if exists(select 1 from pg_catalog.jsonb_array_elements_text(v_roles)r group by r having count(*)>1)then raise exception using message='Rôle dupliqué.',detail='{"code":"duplicate_role"}';end if;for v_role in select value from pg_catalog.jsonb_array_elements_text(v_roles)loop if not(v_role=any(v_allowed_roles))then raise exception using message='Rôle Terrain inconnu.',detail=pg_catalog.jsonb_build_object('code','unknown_role','field',v_role)::text;end if;end loop;select coalesce(pg_catalog.jsonb_agg(value order by value),'[]'::jsonb)into v_roles from pg_catalog.jsonb_array_elements_text(v_roles);end if;
 v_section:=p_config->>'terrainSection';if v_section is not null and(v_section=''or pg_catalog.char_length(v_section)>100 or not(v_section=any(v_sections)))then raise exception using message='Section Terrain inconnue.',detail='{"code":"invalid_section","field":"terrainSection"}';end if;
 if p_config->'terrainDisplayOrder'<>'null'::jsonb then if pg_catalog.jsonb_typeof(p_config->'terrainDisplayOrder')<>'number'or(p_config->>'terrainDisplayOrder')!~'^[0-9]+$'then raise exception using message='Ordre Terrain invalide.',detail='{"code":"invalid_order","field":"terrainDisplayOrder"}';end if;v_order:=(p_config->>'terrainDisplayOrder')::integer;if v_order>100000 then raise exception using message='Ordre Terrain hors limites.',detail='{"code":"invalid_order","field":"terrainDisplayOrder"}';end if;end if;
 if p_config?'criticalFields'and p_config->'criticalFields'<>v_critical then raise exception using message='Champs critiques immuables.',detail='{"code":"critical_fields_immutable"}';end if;
 return pg_catalog.jsonb_build_object('visibleOnTerrain',coalesce(p_config->'visibleOnTerrain','null'::jsonb),'readonlyOnTerrain',coalesce(p_config->'readonlyOnTerrain','null'::jsonb),'terrainRoles',v_roles,'terrainSection',coalesce(p_config->'terrainSection','null'::jsonb),'terrainDisplayOrder',coalesce(p_config->'terrainDisplayOrder','null'::jsonb),'criticalFields',v_critical);
end $$;
alter function public.normalize_terrain_config_v0131a7(jsonb)owner to postgres;revoke all on function public.normalize_terrain_config_v0131a7(jsonb)from public,anon,authenticated;
create or replace function public.save_relation_field_terrain_draft_v0131a7(p_table_name text,p_field_name text,p_contract_version text,p_terrain_config jsonb,p_expected_updated_at timestamptz)returns jsonb language plpgsql security definer set search_path=pg_catalog as $$
declare v_old public.relation_fields%rowtype;v_old_config jsonb;v_new_config jsonb;v_changed text[]:=array[]::text[];v_key text;v_actor uuid:=auth.uid();v_role text;v_updated_at timestamptz;
begin v_role:=public.current_app_role();if v_actor is null then raise exception using message='Authentification requise.',detail='{"code":"unauthorized"}';end if;if v_role<>'Administrateur'then raise exception using message='Permission administrateur requise.',detail='{"code":"administrator_required"}';end if;if p_contract_version is distinct from'1.0.0'then raise exception using message='Version non supportée.',detail='{"code":"unsupported_contract_version"}';end if;if p_expected_updated_at is null then raise exception using message='Horodatage obligatoire.',detail='{"code":"invalid_payload","field":"expectedUpdatedAt"}';end if;
 select*into v_old from public.relation_fields where table_name=p_table_name and field_name=p_field_name for update;if not found then raise exception using message='Champ inconnu.',detail='{"code":"field_not_found"}';end if;if v_old.updated_at is distinct from p_expected_updated_at then raise exception using message='Brouillon obsolète.',detail='{"code":"stale_draft"}';end if;
 v_new_config:=public.normalize_terrain_config_v0131a7(p_terrain_config);v_old_config:=public.normalize_terrain_config_v0131a7(case when v_old.terrain_config='{}'::jsonb then'{}'::jsonb else v_old.terrain_config end);
 if lower(v_old.field_name)in('support_id','photo_principale_url','photo_miniature_url','visuel_actuel_cadre')and v_new_config->'visibleOnTerrain'='false'::jsonb then raise exception using message='Champ critique non masquable.',detail='{"code":"critical_field_hidden"}';end if;
 if coalesce(v_old.physical_is_primary_key,false)or coalesce(v_old.physical_is_foreign_key,false)or coalesce(v_old.physical_is_generated,false)or coalesce(v_old.physical_is_identity,false)or v_old.field_type='calculated'or lower(v_old.field_name)in('id','created_at','updated_at','deleted_at','auth_user_id')or lower(v_old.field_name)like'%\_id'escape'\'then raise exception using message='Champ protégé.',detail='{"code":"field_protected"}';end if;
 if v_old_config=v_new_config and v_old.configuration_status='draft'then return pg_catalog.jsonb_build_object('ok',true,'changed',false,'code','no_change','terrainConfig',v_old_config,'contractVersion','1.0.0','updatedAt',v_old.updated_at);end if;
 foreach v_key in array array['visibleOnTerrain','readonlyOnTerrain','terrainRoles','terrainSection','terrainDisplayOrder','criticalFields']loop if v_old_config->v_key is distinct from v_new_config->v_key then v_changed:=pg_catalog.array_append(v_changed,v_key);end if;end loop;
 update public.relation_fields set terrain_config=v_new_config,configuration_status='draft',updated_at=pg_catalog.now()where id=v_old.id returning updated_at into v_updated_at;
 insert into public.relation_field_config_audit(relation_field_id,table_name,field_name,old_values,new_values,changed_by,changed_at,configuration_status,audit_schema_version,configuration_type,contract_name,contract_version,changed_properties,actor_user_id,occurred_at,transaction_id,actor_app_role,event_type)values(v_old.id,v_old.table_name,v_old.field_name,pg_catalog.jsonb_build_object('terrainConfig',v_old_config,'configuration_status',v_old.configuration_status),pg_catalog.jsonb_build_object('terrainConfig',v_new_config,'configuration_status','draft'),v_actor,pg_catalog.now(),'draft','1.0.0','terrain','TerrainConfig','1.0.0',v_changed,v_actor,pg_catalog.now(),pg_catalog.txid_current()::text,v_role,'terrain_draft_saved');return pg_catalog.jsonb_build_object('ok',true,'changed',true,'code','saved','terrainConfig',v_new_config,'contractVersion','1.0.0','updatedAt',v_updated_at,'changedProperties',pg_catalog.to_jsonb(v_changed));end $$;
alter function public.save_relation_field_terrain_draft_v0131a7(text,text,text,jsonb,timestamptz)owner to postgres;revoke all on function public.save_relation_field_terrain_draft_v0131a7(text,text,text,jsonb,timestamptz)from public,anon;grant execute on function public.save_relation_field_terrain_draft_v0131a7(text,text,text,jsonb,timestamptz)to authenticated;comment on function public.save_relation_field_terrain_draft_v0131a7(text,text,text,jsonb,timestamptz)is'Brouillon TerrainConfig 1.0.0 sans activation ni consommation Terrain.';
commit;
