-- Bloc 13.2-P1 — cycle EDT Installation/Retrait. Additif, transactionnel.
-- Prérequis : migrations Bloc 11, v0.12.9 Lot 1, Bloc 9 et P0 photo.
begin;

alter table public.suivi_des_edt
  add column if not exists campagne_id bigint references public.campagnes_maitres(id) on delete restrict,
  add column if not exists lifecycle_status text not null default 'brouillon',
  add column if not exists retrait_date_proposee date,
  add column if not exists lifecycle_closed_at timestamptz,
  add column if not exists lifecycle_closed_by uuid,
  add column if not exists lifecycle_exception text;

alter table public.edt_phases
  add column if not exists phase_type text,
  add column if not exists closed_at timestamptz,
  add column if not exists closed_by uuid,
  add column if not exists report_ready_at timestamptz,
  add column if not exists commentaire text,
  add column if not exists anomalies jsonb not null default '[]'::jsonb,
  add column if not exists photo_exception text,
  add column if not exists reopened_at timestamptz,
  add column if not exists reopened_by uuid,
  add column if not exists reopen_reason text;

create unique index if not exists edt_phases_type_uq on public.edt_phases(edt_id,phase_type) where phase_type is not null;
create index if not exists suivi_des_edt_campaign_idx on public.suivi_des_edt(campagne_id,lifecycle_status);

create table if not exists public.edt_phase_reports (
  id bigint generated by default as identity primary key,
  edt_id bigint not null references public.suivi_des_edt(id) on delete restrict,
  phase_id bigint not null references public.edt_phases(id) on delete restrict,
  phase_type text not null check(phase_type in ('installation','retrait')),
  version integer not null,
  status text not null default 'brouillon' check(status in ('brouillon','genere','envoye','echec')),
  report_path text,
  report_snapshot jsonb not null default '{}'::jsonb,
  generated_at timestamptz,
  generated_by uuid,
  recipient text,
  sent_at timestamptz,
  sent_by uuid,
  provider_message_id text,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  unique(phase_id,version)
);
create index if not exists edt_phase_reports_edt_idx on public.edt_phase_reports(edt_id,phase_type,version desc);

alter table public.edt_phase_reports enable row level security;
drop policy if exists "edt_phase_reports_read" on public.edt_phase_reports;
create policy "edt_phase_reports_read" on public.edt_phase_reports for select to authenticated
using(public.current_app_role() in ('Administrateur','Coordonnateur','Installateur','Client-Admin','Client'));
drop policy if exists "edt_phase_reports_manage" on public.edt_phase_reports;
create policy "edt_phase_reports_manage" on public.edt_phase_reports for all to authenticated
using(public.current_app_role() in ('Administrateur','Coordonnateur'))
with check(public.current_app_role() in ('Administrateur','Coordonnateur'));
grant select,insert,update on public.edt_phase_reports to authenticated;
grant usage,select on sequence public.edt_phase_reports_id_seq to authenticated;

create or replace function public.tdm_edt_audit_v132p1(p_edt_id bigint,p_phase_id bigint,p_action text,p_old jsonb,p_new jsonb,p_details text default null)
returns void language plpgsql security definer set search_path=public as $$
declare v_ref text;
begin
  select no_edt into v_ref from public.suivi_des_edt where id=p_edt_id;
  insert into public.operations_history(entity_type,entity_id,entity_reference,action,old_data,new_data,details,user_id)
  values('edt_lifecycle',coalesce(p_phase_id,p_edt_id)::text,v_ref,p_action,p_old,p_new,p_details,auth.uid());
end $$;

create or replace function public.initialiser_cycle_edt_v132p1(p_edt_id bigint,p_campagne_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare e public.suivi_des_edt%rowtype;c public.campagnes_maitres%rowtype;i public.edt_phases%rowtype;r public.edt_phases%rowtype;
begin
  if public.current_app_role() not in ('Administrateur','Coordonnateur') then raise exception 'Permission insuffisante.' using errcode='42501'; end if;
  select * into e from public.suivi_des_edt where id=p_edt_id for update;if not found then raise exception 'EDT introuvable.';end if;
  select * into c from public.campagnes_maitres where id=p_campagne_id;if not found then raise exception 'Campagne introuvable.';end if;
  if c.date_fin is null then raise exception 'La campagne doit avoir une date de fin.';end if;
  update public.suivi_des_edt set campagne_id=c.id,campagne=c.nom_campagne,retrait_date_proposee=coalesce(retrait_date_proposee,c.date_fin),lifecycle_status=case when lifecycle_status='brouillon' then 'planifie' else lifecycle_status end,updated_at=now() where id=p_edt_id;
  insert into public.edt_phases(edt_id,nom,ordre,phase_type,statut,date_debut_prevue,progression) values(p_edt_id,'Installation',1,'installation','planifiee',coalesce(e.date_debut,public.tdm_try_date(e.date_debut_prevue::text)),0) on conflict(edt_id,phase_type) where phase_type is not null do nothing returning * into i;
  insert into public.edt_phases(edt_id,nom,ordre,phase_type,statut,date_debut_prevue,progression) values(p_edt_id,'Retrait',2,'retrait','planifie',null,0) on conflict(edt_id,phase_type) where phase_type is not null do nothing returning * into r;
  perform public.tdm_edt_audit_v132p1(p_edt_id,null,'INITIALISATION',to_jsonb(e),jsonb_build_object('campagne_id',c.id,'retrait_date_proposee',c.date_fin),'Deux phases garanties; date de retrait proposée, non imposée.');
  return jsonb_build_object('ok',true,'edt_id',p_edt_id,'campagne_id',c.id,'retrait_date_proposee',c.date_fin);
end $$;

create or replace function public.transition_phase_edt_v132p1(p_phase_id bigint,p_action text,p_commentaire text default null,p_anomalies jsonb default '[]'::jsonb,p_photo_exception text default null,p_exception_date text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare p public.edt_phases%rowtype;e public.suivi_des_edt%rowtype;c public.campagnes_maitres%rowtype;oldp jsonb;open_count int;blocked_count int;photo_count int;next_status text;
begin
  if public.current_app_role() not in ('Administrateur','Coordonnateur') then raise exception 'Permission insuffisante.' using errcode='42501';end if;
  select * into p from public.edt_phases where id=p_phase_id for update;if not found or p.phase_type not in ('installation','retrait') then raise exception 'Phase EDT P1 introuvable.';end if;
  select * into e from public.suivi_des_edt where id=p.edt_id for update;select * into c from public.campagnes_maitres where id=e.campagne_id;
  oldp:=to_jsonb(p);
  if p_action='demarrer' then
    if p.phase_type='retrait' and not exists(select 1 from public.edt_phases where edt_id=p.edt_id and phase_type='installation' and statut='fermee') then raise exception 'Installation non fermée.';end if;
    next_status:='en_cours';update public.edt_phases set statut=next_status,date_debut_reelle=coalesce(date_debut_reelle,now()),updated_at=now() where id=p.id;
  elsif p_action='terminer' then
    next_status:=case when p.phase_type='installation' then 'terminee' else 'termine' end;update public.edt_phases set statut=next_status,progression=100,date_fin_reelle=coalesce(date_fin_reelle,now()),commentaire=p_commentaire,anomalies=coalesce(p_anomalies,'[]'),updated_at=now() where id=p.id;
  elsif p_action='fermer' then
    select count(*) into open_count from public.edt_supports where edt_id=p.edt_id and phase_id=p.id and statut not in ('Terminé','Terminée','Complété','Complétée','Annulé');
    select count(*) into blocked_count from public.edt_supports where edt_id=p.edt_id and phase_id=p.id and (bloque or statut='Bloqué');
    select count(*) into photo_count from public.support_photos where edt_id=p.edt_id::text and lower(type_photo)=p.phase_type and coalesce(status,'active')='active';
    if p.progression<100 or open_count>0 then raise exception 'Éléments obligatoires incomplets.';end if;
    if photo_count=0 and coalesce(trim(p_photo_exception),'')='' then raise exception 'Photo requise ou exception documentée.';end if;
    if blocked_count>0 and jsonb_array_length(coalesce(p_anomalies,'[]'))=0 then raise exception 'Anomalies bloquantes non documentées.';end if;
    next_status:=case when p.phase_type='installation' then 'fermee' else 'ferme' end;
    update public.edt_phases set statut=next_status,closed_at=now(),closed_by=auth.uid(),report_ready_at=now(),commentaire=p_commentaire,anomalies=coalesce(p_anomalies,'[]'),photo_exception=p_photo_exception,updated_at=now() where id=p.id;
    insert into public.edt_phase_reports(edt_id,phase_id,phase_type,version,status,report_snapshot,generated_at,generated_by)
    select p.edt_id,p.id,p.phase_type,coalesce(max(version),0)+1,'brouillon',jsonb_build_object('edt_id',p.edt_id,'phase',p.phase_type,'closed_at',now()),now(),auth.uid() from public.edt_phase_reports where phase_id=p.id;
  elsif p_action='rouvrir' then
    if coalesce(trim(p_commentaire),'')='' then raise exception 'Motif de réouverture obligatoire.';end if;
    if p.closed_at is null then raise exception 'La phase n’est pas fermée.';end if;
    next_status:=case when p.phase_type='installation' then 'terminee' else 'termine' end;
    update public.edt_phases set statut=next_status,reopened_at=now(),reopened_by=auth.uid(),reopen_reason=p_commentaire,closed_at=null,closed_by=null,updated_at=now() where id=p.id;
    update public.edt_phase_reports set archived=true where phase_id=p.id and archived=false;
    update public.suivi_des_edt set lifecycle_status=case when p.phase_type='installation' then 'installation_terminee' else 'retrait_termine' end,lifecycle_closed_at=null,lifecycle_closed_by=null,updated_at=now() where id=p.edt_id;
  else raise exception 'Action de phase invalide.';end if;
  update public.suivi_des_edt set lifecycle_status=case when p.phase_type='installation' then case next_status when 'en_cours' then 'installation_en_cours' when 'terminee' then 'installation_terminee' when 'fermee' then 'attente_fin_campagne' else lifecycle_status end else case next_status when 'en_cours' then 'retrait_en_cours' when 'termine' then 'retrait_termine' when 'ferme' then 'retrait_termine' else lifecycle_status end end,updated_at=now() where id=p.edt_id;
  perform public.tdm_edt_audit_v132p1(p.edt_id,p.id,upper(p_action),oldp,(select to_jsonb(x) from public.edt_phases x where x.id=p.id),coalesce(p_commentaire,p_exception_date));
  return jsonb_build_object('ok',true,'phase_id',p.id,'statut',next_status);
end $$;

create or replace function public.planifier_retrait_edt_v132p1(p_phase_id bigint,p_date date,p_justification text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare p public.edt_phases%rowtype;e public.suivi_des_edt%rowtype;c public.campagnes_maitres%rowtype;i public.edt_phases%rowtype;
begin
  if public.current_app_role() not in ('Administrateur','Coordonnateur') then raise exception 'Permission insuffisante.' using errcode='42501';end if;
  select * into p from public.edt_phases where id=p_phase_id and phase_type='retrait' for update;if not found then raise exception 'Phase Retrait introuvable.';end if;
  select * into e from public.suivi_des_edt where id=p.edt_id;select * into c from public.campagnes_maitres where id=e.campagne_id;select * into i from public.edt_phases where edt_id=p.edt_id and phase_type='installation';
  if i.closed_at is not null and p_date<i.closed_at::date then raise exception 'Retrait avant fermeture Installation interdit.';end if;
  if p_date<c.date_fin and coalesce(trim(p_justification),'')='' then raise exception 'Justification obligatoire avant la fin de campagne.';end if;
  update public.edt_phases set date_debut_prevue=p_date,statut=case when p_date<c.date_fin then 'planifie' else 'planifie' end,commentaire=coalesce(p_justification,commentaire),updated_at=now() where id=p.id;
  update public.suivi_des_edt set lifecycle_status='retrait_planifie',lifecycle_exception=case when p_date<c.date_fin then p_justification else lifecycle_exception end,updated_at=now() where id=p.edt_id;
  perform public.tdm_edt_audit_v132p1(p.edt_id,p.id,'PLANIFICATION_RETRAIT',to_jsonb(p),(select to_jsonb(x) from public.edt_phases x where x.id=p.id),p_justification);
  return jsonb_build_object('ok',true,'date',p_date,'avant_fin_campagne',p_date<c.date_fin);
end $$;

create or replace function public.fermer_edt_v132p1(p_edt_id bigint,p_motif text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare e public.suivi_des_edt%rowtype;
begin
  if public.current_app_role() not in ('Administrateur','Coordonnateur') then raise exception 'Permission insuffisante.' using errcode='42501';end if;
  select * into e from public.suivi_des_edt where id=p_edt_id for update;if not found then raise exception 'EDT introuvable.';end if;
  if not exists(select 1 from public.edt_phases where edt_id=p_edt_id and phase_type='installation' and statut='fermee') or not exists(select 1 from public.edt_phases where edt_id=p_edt_id and phase_type='retrait' and statut='ferme') then raise exception 'Les deux phases doivent être fermées.';end if;
  if exists(select 1 from public.edt_supports where edt_id=p_edt_id and (bloque or statut='Bloqué')) and coalesce(trim(p_motif),'')='' then raise exception 'Blocage critique non documenté.';end if;
  update public.suivi_des_edt set lifecycle_status='ferme',statut='Fermé',lifecycle_closed_at=now(),lifecycle_closed_by=auth.uid(),lifecycle_exception=p_motif,date_fin=current_date,progression=100,updated_at=now() where id=p_edt_id;
  perform public.tdm_edt_audit_v132p1(p_edt_id,null,'FERMETURE_EDT',to_jsonb(e),(select to_jsonb(x) from public.suivi_des_edt x where x.id=p_edt_id),p_motif);
  return jsonb_build_object('ok',true,'edt_id',p_edt_id,'statut','ferme');
end $$;

create or replace function public.marquer_rapport_phase_envoye_v132p1(p_report_id bigint,p_recipient text,p_provider_message_id text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare r public.edt_phase_reports%rowtype;
begin
  if public.current_app_role() not in ('Administrateur','Coordonnateur') then raise exception 'Permission insuffisante.' using errcode='42501';end if;
  if coalesce(trim(p_recipient),'')='' then raise exception 'Destinataire obligatoire.';end if;
  select * into r from public.edt_phase_reports where id=p_report_id for update;if not found then raise exception 'Rapport introuvable.';end if;
  update public.edt_phase_reports set status='envoye',recipient=p_recipient,sent_at=now(),sent_by=auth.uid(),provider_message_id=p_provider_message_id where id=r.id;
  perform public.tdm_edt_audit_v132p1(r.edt_id,r.phase_id,'ENVOI_RAPPORT',to_jsonb(r),(select to_jsonb(x) from public.edt_phase_reports x where x.id=r.id),p_recipient);
  return jsonb_build_object('ok',true,'report_id',r.id,'sent_at',now());
end $$;

grant execute on function public.initialiser_cycle_edt_v132p1(bigint,bigint) to authenticated;
grant execute on function public.transition_phase_edt_v132p1(bigint,text,text,jsonb,text,text) to authenticated;
grant execute on function public.planifier_retrait_edt_v132p1(bigint,date,text) to authenticated;
grant execute on function public.fermer_edt_v132p1(bigint,text) to authenticated;
grant execute on function public.marquer_rapport_phase_envoye_v132p1(bigint,text,text) to authenticated;
commit;
