-- V1.1.3 — structure additive uniquement. Ne réalise aucun backfill.
create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null,
  actor_id uuid,
  actor_email text,
  actor_role text,
  action text not null,
  module text not null,
  entity_type text,
  entity_id text,
  old_value jsonb,
  new_value jsonb,
  campaign_id text,
  edt_id text,
  support_id text,
  client_id text,
  source text not null,
  status text,
  metadata jsonb not null default '{}'::jsonb,
  source_system text not null,
  source_record_id text not null,
  source_occurred_at timestamptz not null,
  reconstruction_method text not null check (reconstruction_method in ('direct','derived')),
  confidence text not null check (confidence in ('exact','derived')),
  application_version text,
  created_at timestamptz not null default now(),
  unique(source_system, source_record_id)
);
create index if not exists activity_events_occurred_idx on public.activity_events(occurred_at desc,id desc);
create index if not exists activity_events_actor_idx on public.activity_events(actor_email,occurred_at desc);
create index if not exists activity_events_module_idx on public.activity_events(module,action,status,occurred_at desc);
create index if not exists activity_events_entities_idx on public.activity_events(entity_type,entity_id,support_id,edt_id,campaign_id);
alter table public.activity_events enable row level security;
drop policy if exists "activity_events_read" on public.activity_events;
create policy "activity_events_read" on public.activity_events for select to authenticated
  using(public.current_app_role() in ('Administrateur','Coordonnateur'));
drop policy if exists "activity_events_insert_exact" on public.activity_events;
create policy "activity_events_insert_exact" on public.activity_events for insert to authenticated
  with check(actor_id=auth.uid() and confidence='exact' and reconstruction_method='direct');
revoke all on public.activity_events from public,anon,authenticated;
grant select,insert on public.activity_events to authenticated;

create or replace function public.capture_activity_source_v113()
returns trigger language plpgsql security definer set search_path=public as $$
declare j jsonb:=to_jsonb(new);v_time timestamptz;v_action text;v_module text;v_entity text;v_actor uuid;v_email text;v_confidence text:='exact';v_source_record text;
begin
  v_time=coalesce((j->>'created_at')::timestamptz,(j->>'changed_at')::timestamptz,(j->>'prise_le')::timestamptz,now());
  if tg_table_name='operations_history' then v_action=j->>'action';v_module='Opérations';v_entity=j->>'entity_type';v_actor=nullif(j->>'user_id','')::uuid;v_email=j->>'user_email';
  elsif tg_table_name='terrain_sync_diagnostics' then v_action=j->>'etape';v_module='Terrain';v_entity='terrain_sync';v_email=j->>'utilisateur';
  elsif tg_table_name='terrain_operations' then v_action=j->>'type_operation';v_module='Terrain';v_entity='terrain_operation';v_email=j->>'utilisateur';
  elsif tg_table_name='photo_action_log' then v_action=j->>'action';v_module='Photos';v_entity='photo';v_actor=nullif(j->>'user_id','')::uuid;
  elsif tg_table_name='journal_propagations' then v_action=j->>'declencheur';v_module='Campagnes';v_entity='propagation';v_email=j->>'utilisateur';
  elsif tg_table_name='relation_field_config_audit' then v_action='configuration_modifiee';v_module='Gestionnaire des champs';v_entity='relation_field';v_actor=nullif(j->>'changed_by','')::uuid;
  elsif tg_table_name='support_photos' then v_action='photo_ajoutee';v_module='Photos';v_entity='photo';v_email=j->>'utilisateur';v_confidence='derived';
  else return new; end if;
  if nullif(v_action,'') is null or nullif(j->>'id','') is null then return new; end if;
  v_source_record=j->>'id';
  if tg_table_name in('terrain_sync_diagnostics','terrain_operations') then v_source_record=concat_ws(':',v_source_record,coalesce(j->>'statut','unknown'),coalesce(j->>'etape','unknown'),coalesce(j->>'attempt','1')); end if;
  insert into public.activity_events(occurred_at,actor_id,actor_email,action,module,entity_type,entity_id,old_value,new_value,campaign_id,edt_id,support_id,client_id,source,status,metadata,source_system,source_record_id,source_occurred_at,reconstruction_method,confidence)
  values(v_time,v_actor,v_email,v_action,v_module,v_entity,coalesce(j->>'entity_id',j->>'entity_reference',j->>'reference',j->>'photo_id',j->>'relation_field_id',j->>'id'),j->'old_data',coalesce(j->'new_data',j),j->>'campagne_id',j->>'edt_id',j->>'support_id',j->>'client_id',tg_table_name,coalesce(j->>'statut',j->>'status',j->>'configuration_status'),j,tg_table_name,v_source_record,v_time,case when v_confidence='exact' then'direct'else'derived'end,v_confidence)
  on conflict(source_system,source_record_id) do nothing;
  return new;
end $$;
revoke all on function public.capture_activity_source_v113() from public,anon,authenticated;
drop trigger if exists activity_capture_operations_history_v113 on public.operations_history;
create trigger activity_capture_operations_history_v113 after insert on public.operations_history for each row execute function public.capture_activity_source_v113();
drop trigger if exists activity_capture_terrain_diagnostics_v113 on public.terrain_sync_diagnostics;
create trigger activity_capture_terrain_diagnostics_v113 after insert or update on public.terrain_sync_diagnostics for each row execute function public.capture_activity_source_v113();
drop trigger if exists activity_capture_terrain_operations_v113 on public.terrain_operations;
create trigger activity_capture_terrain_operations_v113 after insert or update on public.terrain_operations for each row execute function public.capture_activity_source_v113();
drop trigger if exists activity_capture_photo_log_v113 on public.photo_action_log;
create trigger activity_capture_photo_log_v113 after insert on public.photo_action_log for each row execute function public.capture_activity_source_v113();
drop trigger if exists activity_capture_propagations_v113 on public.journal_propagations;
create trigger activity_capture_propagations_v113 after insert on public.journal_propagations for each row execute function public.capture_activity_source_v113();
drop trigger if exists activity_capture_field_audit_v113 on public.relation_field_config_audit;
create trigger activity_capture_field_audit_v113 after insert on public.relation_field_config_audit for each row execute function public.capture_activity_source_v113();
drop trigger if exists activity_capture_support_photos_v113 on public.support_photos;
create trigger activity_capture_support_photos_v113 after insert on public.support_photos for each row execute function public.capture_activity_source_v113();

alter table public.terrain_sync_diagnostics add column if not exists device_id text;
alter table public.terrain_sync_diagnostics add column if not exists operation text;
alter table public.terrain_sync_diagnostics add column if not exists campagne_id bigint;
alter table public.terrain_sync_diagnostics add column if not exists edt_id bigint;
alter table public.terrain_sync_diagnostics add column if not exists attempt integer not null default 1;
alter table public.terrain_sync_diagnostics add column if not exists last_attempt_at timestamptz;
alter table public.terrain_sync_diagnostics add column if not exists resolved_at timestamptz;
alter table public.terrain_sync_diagnostics add column if not exists resolved_by uuid;
alter table public.terrain_sync_diagnostics add column if not exists resolution text;
alter table public.terrain_sync_diagnostics add column if not exists source text not null default 'terrain_sync_diagnostics';
create index if not exists terrain_sync_history_idx on public.terrain_sync_diagnostics(created_at desc,id);
create index if not exists terrain_sync_reference_idx on public.terrain_sync_diagnostics(reference,created_at desc);

create or replace view public.terrain_sync_history_v113 with(security_invoker=true) as
select 'terrain_sync_diagnostics'::text source_system,id::text source_record_id,id diagnostic_id,reference,support_id,utilisateur,device_id,coalesce(operation,etape) operation,campagne_id,edt_id,statut,details->>'erreur' error,attempt,last_attempt_at,resolved_at,resolved_by,resolution,source,created_at
from public.terrain_sync_diagnostics
union all
select 'terrain_operations',id::text,null::uuid,reference,support_id,utilisateur,null::text,type_operation,null::bigint,null::bigint,statut,erreur,1,completed_at,null::timestamptz,null::uuid,null::text,'terrain_operations',created_at
from public.terrain_operations;
grant select on public.terrain_sync_history_v113 to authenticated;

create or replace function public.resolve_terrain_sync_v113(p_id uuid,p_resolution text)
returns public.terrain_sync_diagnostics language plpgsql security definer set search_path=public as $$
declare result public.terrain_sync_diagnostics;
begin
  if public.current_app_role() not in ('Administrateur','Coordonnateur') then raise exception 'Permission insuffisante.' using errcode='42501'; end if;
  update public.terrain_sync_diagnostics set statut='resolved',resolved_at=now(),resolved_by=auth.uid(),resolution=nullif(trim(p_resolution),'')
  where id=p_id and lower(statut) in ('échec','echec','error','erreur','failed') returning * into result;
  if result.id is null then raise exception 'Diagnostic introuvable ou non résoluble.'; end if;
  return result;
end $$;

create or replace function public.request_terrain_sync_retry_v113(p_id uuid)
returns public.terrain_sync_diagnostics language plpgsql security definer set search_path=public as $$
declare original public.terrain_sync_diagnostics;result public.terrain_sync_diagnostics;
begin
  if public.current_app_role() not in ('Administrateur','Coordonnateur') then raise exception 'Permission insuffisante.' using errcode='42501'; end if;
  select * into original from public.terrain_sync_diagnostics where id=p_id;
  if original.id is null then raise exception 'Diagnostic introuvable.'; end if;
  insert into public.terrain_sync_diagnostics(reference,support_id,visuel_id,utilisateur,etape,statut,details,device_id,operation,campagne_id,edt_id,attempt,last_attempt_at,source)
  values(original.reference,original.support_id,original.visuel_id,(select email from auth.users where id=auth.uid()),'Nouvelle tentative demandée','pending',jsonb_build_object('retry_of',original.id),original.device_id,original.operation,original.campagne_id,original.edt_id,original.attempt+1,now(),'manual_retry_request') returning * into result;
  return result;
end $$;
revoke all on function public.resolve_terrain_sync_v113(uuid,text),public.request_terrain_sync_retry_v113(uuid) from public,anon;
grant execute on function public.resolve_terrain_sync_v113(uuid,text),public.request_terrain_sync_retry_v113(uuid) to authenticated;

-- Rollback structurel: supprimer la vue, les deux fonctions, puis la table activity_events.
-- Les colonnes Terrain sont volontairement conservées afin de ne perdre aucune résolution/tentative.
