-- PREPARATION UNIQUEMENT — NE PAS EXECUTER SANS VALIDATION EN PREPRODUCTION.
-- Additive, non destructive pour les données. Les anciennes lectures globales citées
-- ci-dessous sont remplacées car des politiques permissives se combinent par OR.
begin;

alter table public.campagnes_maitres add column if not exists client_id bigint references public.clients(id) on delete restrict;
alter table public.campagnes_maitres add column if not exists client_published boolean not null default false;
alter table public.campagnes_supports add column if not exists client_visible boolean not null default false;
alter table public.campagne_visuels_formats add column if not exists client_visible boolean not null default false;
alter table public.support_photos add column if not exists client_visible boolean not null default false;
alter table public.suivi_des_edt add column if not exists client_visible boolean not null default false;
alter table public.edt_phase_reports add column if not exists client_visible boolean not null default false;
alter table public.enjeux_terrain add column if not exists client_visible boolean not null default false;
alter table public.activity_events add column if not exists client_visible boolean not null default false;
alter table public.communications_finales add column if not exists client_id bigint references public.clients(id) on delete restrict;
alter table public.communications_finales add column if not exists client_published boolean not null default false;

create table if not exists public.client_campaign_access (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete restrict,
  campaign_id bigint not null references public.campagnes_maitres(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  granted_by uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  unique nulls not distinct (client_id,campaign_id,user_id)
);
create table if not exists public.client_member_invitations (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete restrict,
  email text not null,
  display_name text,
  requested_role text not null default 'Client' check(requested_role='Client'),
  status text not null default 'pending' check(status in ('pending','accepted','cancelled','expired')),
  requested_by uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  unique(client_id,email,status)
);

create index if not exists campagnes_maitres_client_context_idx on public.campagnes_maitres(client_id,business_context,client_published);
create index if not exists client_campaign_access_user_idx on public.client_campaign_access(user_id,client_id,campaign_id);
create index if not exists support_photos_client_visible_idx on public.support_photos(campagne_id,client_visible,prise_le desc);
create index if not exists activity_events_client_visible_idx on public.activity_events(client_id,client_visible,occurred_at desc);

create or replace function public.client_portal_identity_v120()
returns jsonb language sql stable security definer set search_path=public,auth as $$
  select case when u.role in ('Client','Client-Admin') and u.statut='Actif' and u.client_id is not null
    then jsonb_build_object('user_id',auth.uid(),'role',u.role,'organization_id',u.client_id,'name',u.nom)
    else null end
  from public.utilisateurs u where u.auth_user_id=auth.uid() limit 1;
$$;
revoke all on function public.client_portal_identity_v120() from public,anon;
grant execute on function public.client_portal_identity_v120() to authenticated;

create or replace function public.client_can_access_campaign_v120(p_campaign_id bigint)
returns boolean language sql stable security definer set search_path=public,auth as $$
  select exists(
    select 1 from public.utilisateurs u join public.campagnes_maitres c on c.client_id=u.client_id
    where u.auth_user_id=auth.uid() and u.statut='Actif' and u.role in ('Client','Client-Admin')
      and c.id=p_campaign_id and c.client_published
      and (u.role='Client-Admin' or exists(select 1 from public.client_campaign_access a
        where a.client_id=u.client_id and a.campaign_id=c.id and (a.user_id is null or a.user_id=auth.uid())))
  );
$$;
revoke all on function public.client_can_access_campaign_v120(bigint) from public,anon;
grant execute on function public.client_can_access_campaign_v120(bigint) to authenticated;

-- Les colonnes sont explicitement sélectionnées : notes, diagnostics, instructions,
-- erreurs, snapshots privés, coûts et métadonnées techniques ne quittent jamais la fonction.
create or replace function public.client_portal_list_v120(p_section text,p_page integer default 1,p_page_size integer default 25,p_filters jsonb default '{}'::jsonb)
returns jsonb language plpgsql stable security definer set search_path=public,auth as $$
declare v_uid uuid:=auth.uid();v_client bigint;v_role text;v_offset integer;v_limit integer;v_rows jsonb:='[]';v_total bigint:=0;
begin
  select client_id,role into v_client,v_role from public.utilisateurs
   where auth_user_id=v_uid and statut='Actif' and role in ('Client','Client-Admin');
  if v_client is null then raise exception 'client_scope_denied' using errcode='42501'; end if;
  if p_section not in ('dashboard','campaigns','communications','supports','photos','reports','edt','issues','history','members') then raise exception 'invalid_section'; end if;
  if p_section='members' and v_role<>'Client-Admin' then raise exception 'client_admin_required' using errcode='42501'; end if;
  v_limit:=least(case when p_section='photos' then 50 else 100 end,greatest(1,coalesce(p_page_size,25)));
  v_offset:=(greatest(1,coalesce(p_page,1))-1)*v_limit;

  if p_section in ('campaigns','communications') then
    select count(*),coalesce(jsonb_agg(to_jsonb(q)),'[]') into v_total,v_rows from (
      select c.id,c.nom_campagne,c.business_context,c.date_debut,c.date_fin,c.statut
      from public.campagnes_maitres c where c.client_id=v_client and c.client_published
       and c.business_context=case when p_section='campaigns' then 'marketing' else 'operational_communication' end
       and (v_role='Client-Admin' or public.client_can_access_campaign_v120(c.id))
      order by c.date_fin desc nulls last,c.id desc limit v_limit offset v_offset) q;
  elsif p_section='supports' then
    select count(*),coalesce(jsonb_agg(to_jsonb(q)),'[]') into v_total,v_rows from (
      select i.site,i.support_id,i.type_support,i.emplacement_visibilite,cs.statut,cs.no_edt,c.id campaign_id,c.nom_campagne,c.business_context,cs.visuel_attendu visual
      from public.campagnes_supports cs join public.campagnes_maitres c on c.id=cs.campagne_id
      join public.infrastructures i on i.support_id=cs.support_id
      where c.client_id=v_client and c.client_published and cs.client_visible and public.client_can_access_campaign_v120(c.id)
      order by i.site,i.support_id,c.id limit v_limit offset v_offset) q;
  elsif p_section='photos' then
    select count(*),coalesce(jsonb_agg(to_jsonb(q)),'[]') into v_total,v_rows from (
      select p.id,p.support_id,p.campagne_id,p.visuel_id,p.type_photo,p.nom_fichier,p.storage_bucket,p.storage_path,p.prise_le,p.statut_validation
      from public.support_photos p join public.campagnes_maitres c on c.id=p.campagne_id
      where c.client_id=v_client and c.client_published and p.client_visible and public.client_can_access_campaign_v120(c.id)
      order by p.prise_le desc,p.id desc limit v_limit offset v_offset) q;
  elsif p_section='reports' then
    select count(*),coalesce(jsonb_agg(to_jsonb(q)),'[]') into v_total,v_rows from (
      select r.id,r.numero_edt,r.campagne,r.objet,r.report_path,r.sent_at,r.created_at
      from public.communications_finales r where r.client_id=v_client and r.client_published and r.statut in ('Envoyé','Publié')
      order by r.created_at desc limit v_limit offset v_offset) q;
  elsif p_section='edt' then
    select count(*),coalesce(jsonb_agg(to_jsonb(q)),'[]') into v_total,v_rows from (
      select e.id,e.no_edt,e.statut,e.date_debut_prevue,e.date_fin_prevue,e.rapport_final_envoye,e.rapport_final_path,e.campagne_id
      from public.suivi_des_edt e join public.campagnes_maitres c on c.id=e.campagne_id
      where c.client_id=v_client and c.client_published and e.client_visible and public.client_can_access_campaign_v120(c.id)
      order by e.date_fin_prevue desc nulls last,e.id desc limit v_limit offset v_offset) q;
  elsif p_section='issues' then
    select count(*),coalesce(jsonb_agg(to_jsonb(q)),'[]') into v_total,v_rows from (
      select e.id,e.reference,e.support_id,e.type_enjeu,e.description,e.statut,e.priorite,e.created_at
      from public.enjeux_terrain e where e.client_visible and exists(select 1 from public.campagnes_supports cs join public.campagnes_maitres c on c.id=cs.campagne_id where cs.support_id=e.support_id and c.client_id=v_client and c.client_published and public.client_can_access_campaign_v120(c.id))
      order by e.created_at desc limit v_limit offset v_offset) q;
  elsif p_section='history' then
    select count(*),coalesce(jsonb_agg(to_jsonb(q)),'[]') into v_total,v_rows from (
      select a.id,a.occurred_at,a.action,a.module,a.entity_type,a.entity_id,a.campaign_id,a.edt_id,a.support_id,a.status
      from public.activity_events a where a.client_visible and a.client_id=v_client::text
       and a.action in ('campagne_publiee','photo_ajoutee','edt_termine','rapport_disponible','enjeu_ouvert','communication_publiee')
      order by a.occurred_at desc,a.id desc limit v_limit offset v_offset) q;
  elsif p_section='members' then
    select count(*),coalesce(jsonb_agg(to_jsonb(q)),'[]') into v_total,v_rows from (
      select u.id,u.nom,u.courriel,u.role,u.statut,u.updated_at from public.utilisateurs u
      where u.client_id=v_client and u.role in ('Client','Client-Admin') order by u.nom,u.id limit v_limit offset v_offset) q;
  else
    return jsonb_build_object('section','dashboard','organization_id',v_client,'role',v_role);
  end if;
  return jsonb_build_object('section',p_section,'page',greatest(1,coalesce(p_page,1)),'page_size',v_limit,'total',v_total,'rows',v_rows);
end;$$;
revoke all on function public.client_portal_list_v120(text,integer,integer,jsonb) from public,anon;
grant execute on function public.client_portal_list_v120(text,integer,integer,jsonb) to authenticated;

create or replace function public.client_admin_invite_member_v120(p_email text,p_name text default null)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
declare v_client bigint;v_id bigint;
begin
 select client_id into v_client from public.utilisateurs where auth_user_id=auth.uid() and statut='Actif' and role='Client-Admin';
 if v_client is null then raise exception 'client_admin_required' using errcode='42501'; end if;
 if p_email is null or p_email !~* '^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$' then raise exception 'invalid_email'; end if;
 insert into public.client_member_invitations(client_id,email,display_name) values(v_client,lower(trim(p_email)),nullif(trim(p_name),'')) returning id into v_id;
 return jsonb_build_object('invitation_id',v_id,'status','pending');
end;$$;
create or replace function public.client_admin_deactivate_member_v120(p_member_id bigint)
returns boolean language plpgsql security definer set search_path=public,auth as $$
declare v_client bigint;
begin
 select client_id into v_client from public.utilisateurs where auth_user_id=auth.uid() and statut='Actif' and role='Client-Admin';
 if v_client is null then raise exception 'client_admin_required' using errcode='42501'; end if;
 update public.utilisateurs set statut='Inactif',updated_at=now() where id=p_member_id and client_id=v_client and role='Client';
 return found;
end;$$;
create or replace function public.client_admin_set_campaign_access_v120(p_member_id bigint,p_campaign_id bigint,p_allowed boolean)
returns boolean language plpgsql security definer set search_path=public,auth as $$
declare v_client bigint;v_member_uid uuid;
begin
 select client_id into v_client from public.utilisateurs where auth_user_id=auth.uid() and statut='Actif' and role='Client-Admin';
 if v_client is null then raise exception 'client_admin_required' using errcode='42501'; end if;
 select auth_user_id into v_member_uid from public.utilisateurs where id=p_member_id and client_id=v_client and role='Client';
 if v_member_uid is null or not exists(select 1 from public.campagnes_maitres where id=p_campaign_id and client_id=v_client) then raise exception 'cross_client_denied' using errcode='42501'; end if;
 if p_allowed then insert into public.client_campaign_access(client_id,campaign_id,user_id) values(v_client,p_campaign_id,v_member_uid) on conflict do nothing;
 else delete from public.client_campaign_access where client_id=v_client and campaign_id=p_campaign_id and user_id=v_member_uid; end if;
 return true;
end;$$;
revoke all on function public.client_admin_invite_member_v120(text,text),public.client_admin_deactivate_member_v120(bigint),public.client_admin_set_campaign_access_v120(bigint,bigint,boolean) from public,anon;
grant execute on function public.client_admin_invite_member_v120(text,text),public.client_admin_deactivate_member_v120(bigint),public.client_admin_set_campaign_access_v120(bigint,bigint,boolean) to authenticated;

alter table public.client_campaign_access enable row level security;
alter table public.client_member_invitations enable row level security;
create policy client_campaign_access_staff_all_v120 on public.client_campaign_access for all to authenticated using(public.current_app_role() in ('Administrateur','Coordonnateur')) with check(public.current_app_role() in ('Administrateur','Coordonnateur'));
create policy client_campaign_access_own_read_v120 on public.client_campaign_access for select to authenticated using(client_id=(select u.client_id from public.utilisateurs u where u.auth_user_id=auth.uid()) and (user_id is null or user_id=auth.uid() or public.current_app_role()='Client-Admin'));
create policy client_member_invitations_staff_all_v120 on public.client_member_invitations for all to authenticated using(public.current_app_role() in ('Administrateur','Coordonnateur')) with check(public.current_app_role() in ('Administrateur','Coordonnateur'));
create policy client_member_invitations_own_admin_read_v120 on public.client_member_invitations for select to authenticated using(public.current_app_role()='Client-Admin' and client_id=(select u.client_id from public.utilisateurs u where u.auth_user_id=auth.uid()));

-- Remplacements minimaux nécessaires des lectures globales historiques.
drop policy if exists "clients_authenticated_read" on public.clients;
create policy clients_scoped_read_v120 on public.clients for select to authenticated using(public.current_app_role() in ('Administrateur','Coordonnateur') or id=(select u.client_id from public.utilisateurs u where u.auth_user_id=auth.uid() and u.role in ('Client','Client-Admin')));
drop policy if exists "campagnes_maitres_authenticated_read" on public.campagnes_maitres;
drop policy if exists "campagnes_maitres_authenticated_read_v075" on public.campagnes_maitres;
create policy campagnes_maitres_scoped_read_v120 on public.campagnes_maitres for select to authenticated using(public.current_app_role() in ('Administrateur','Coordonnateur','Installateur') or public.client_can_access_campaign_v120(id));
drop policy if exists "campagnes_supports_authenticated_read" on public.campagnes_supports;
create policy campagnes_supports_scoped_read_v120 on public.campagnes_supports for select to authenticated using(public.current_app_role() in ('Administrateur','Coordonnateur','Installateur') or (client_visible and public.client_can_access_campaign_v120(campagne_id)));
drop policy if exists cvf_dev on public.campagne_visuels_formats;
drop policy if exists "visuals_authenticated_read_v075" on public.campagne_visuels_formats;
create policy campagne_visuals_scoped_read_v120 on public.campagne_visuels_formats for select to authenticated using(public.current_app_role() in ('Administrateur','Coordonnateur','Installateur') or (client_visible and public.client_can_access_campaign_v120(campagne_id)));
drop policy if exists sp_dev on public.support_photos;
drop policy if exists "support_photos_authenticated_read_v075" on public.support_photos;
create policy support_photos_scoped_read_v120 on public.support_photos for select to authenticated using(public.current_app_role() in ('Administrateur','Coordonnateur','Installateur') or (client_visible and public.client_can_access_campaign_v120(campagne_id)));
drop policy if exists "communications_finales_read" on public.communications_finales;
create policy communications_finales_scoped_read_v120 on public.communications_finales for select to authenticated using(public.current_app_role() in ('Administrateur','Coordonnateur') or (client_published and client_id=(select u.client_id from public.utilisateurs u where u.auth_user_id=auth.uid() and u.role in ('Client','Client-Admin'))));
drop policy if exists "final_reports_authenticated_read" on storage.objects;
create policy final_reports_scoped_read_v120 on storage.objects for select to authenticated using(bucket_id='final-reports' and (public.current_app_role() in ('Administrateur','Coordonnateur') or exists(select 1 from public.communications_finales r where r.report_path=name and r.client_published and r.client_id=(select u.client_id from public.utilisateurs u where u.auth_user_id=auth.uid()))));

-- support-photos devient privé. Aucun fichier ni objet Storage n'est supprimé.
update storage.buckets set public=false where id='support-photos';
drop policy if exists sp_storage_read on storage.objects;
drop policy if exists sp_storage_insert on storage.objects;
drop policy if exists support_photos_storage_scoped_read_v120 on storage.objects;
create policy support_photos_storage_scoped_read_v120 on storage.objects
for select to authenticated using (
  bucket_id='support-photos' and (
    public.current_app_role() in ('Administrateur','Coordonnateur','Installateur')
    or exists (
      select 1 from public.support_photos p
      join public.campagnes_maitres c on c.id=p.campagne_id
      join public.utilisateurs u on u.auth_user_id=auth.uid()
      where p.storage_path=storage.objects.name
        and p.client_visible
        and c.client_published
        and c.client_id=u.client_id
        and u.statut='Actif'
        and u.role in ('Client','Client-Admin')
        and public.client_can_access_campaign_v120(c.id)
    )
  )
);

commit;
