-- V1.3.1 - PREPARATION SEULEMENT. NE PAS EXECUTER SANS VALIDATION MANUELLE.
-- Déclencheur: transition exacte de suivi_des_edt.statut vers « Complété ».
begin;

alter table public.suivi_des_edt
  add column if not exists requester_contact_id bigint references public.utilisateurs(id) on delete restrict;
create index if not exists suivi_des_edt_requester_idx on public.suivi_des_edt(requester_contact_id);

create table if not exists public.email_outbox (
  id bigint generated by default as identity primary key,
  event_type text not null check(event_type in ('edt_completed_report_sent')),
  edt_id bigint not null references public.suivi_des_edt(id) on delete restrict,
  idempotency_key text not null unique,
  report_id uuid references public.edt_reports(id) on delete restrict,
  report_version integer,
  status text not null default 'pending' check(status in ('pending','sending','sent','failed')),
  attempt_count integer not null default 0 check(attempt_count between 0 and 5),
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  last_error text,
  manual_resend boolean not null default false,
  requested_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists email_outbox_automatic_completion_uq
  on public.email_outbox(edt_id,event_type) where not manual_resend;
create index if not exists email_outbox_worker_idx on public.email_outbox(status,next_attempt_at);

create table if not exists public.email_delivery_log (
  id bigint generated by default as identity primary key,
  outbox_id bigint not null references public.email_outbox(id) on delete restrict,
  event_type text not null,
  edt_id bigint not null references public.suivi_des_edt(id) on delete restrict,
  report_id uuid references public.edt_reports(id) on delete restrict,
  report_version integer,
  recipient_email text,
  sender_email text not null default 'noreply@groupetos.com',
  provider text not null default 'microsoft_graph',
  provider_message_id text,
  status text not null check(status in ('sent','failed')),
  attempt_count integer not null,
  sent_at timestamptz,
  last_error text,
  manual_resend boolean not null default false,
  created_at timestamptz not null default now()
);
create unique index if not exists email_delivery_log_success_uq
  on public.email_delivery_log(edt_id,event_type,report_version) where status='sent' and not manual_resend;
create index if not exists email_delivery_log_edt_idx on public.email_delivery_log(edt_id,created_at desc);

alter table public.email_outbox enable row level security;
alter table public.email_delivery_log enable row level security;
revoke all on public.email_outbox,public.email_delivery_log from public,anon,authenticated;
grant select on public.email_outbox,public.email_delivery_log to authenticated;
create policy email_outbox_staff_read_v131 on public.email_outbox for select to authenticated
  using(public.current_app_role() in ('Administrateur','Coordonnateur'));
create policy email_delivery_staff_read_v131 on public.email_delivery_log for select to authenticated
  using(public.current_app_role() in ('Administrateur','Coordonnateur'));

create or replace function public.validate_edt_requester_v131() returns trigger
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_requester_client bigint;v_edt_client bigint;
begin
 if new.requester_contact_id is null then return new; end if;
 select client_id into v_requester_client from public.utilisateurs where id=new.requester_contact_id;
 select client_id into v_edt_client from public.campagnes_maitres where id=new.campagne_id;
 if v_requester_client is null or v_edt_client is null or v_requester_client<>v_edt_client then
   raise exception 'requester_client_mismatch' using errcode='23514';
 end if;
 return new;
end$$;
revoke all on function public.validate_edt_requester_v131() from public,anon,authenticated;
create trigger validate_edt_requester_v131 before insert or update of requester_contact_id,campagne_id
on public.suivi_des_edt for each row execute function public.validate_edt_requester_v131();

create or replace function public.enqueue_edt_completion_email_v131() returns trigger
language plpgsql security definer set search_path=public,pg_temp as $$
begin
 if old.statut is distinct from 'Complété' and new.statut='Complété' then
   insert into public.email_outbox(event_type,edt_id,idempotency_key,status,last_error)
   values('edt_completed_report_sent',new.id,'edt_completed_report_sent:'||new.id::text,'pending',
     case when new.requester_contact_id is null then 'Requérant sans adresse courriel' end)
   on conflict(edt_id,event_type) where not manual_resend do nothing;
 end if;
 return new;
end$$;
revoke all on function public.enqueue_edt_completion_email_v131() from public,anon,authenticated;
create trigger enqueue_edt_completion_email_v131 after update of statut on public.suivi_des_edt
for each row execute function public.enqueue_edt_completion_email_v131();

create or replace function public.request_edt_email_retry_v131(p_edt_id bigint,p_resend boolean default false)
returns bigint language plpgsql security definer set search_path=public,pg_temp as $$
declare v_id bigint;
begin
 if auth.uid() is null or public.current_app_role() not in ('Administrateur','Coordonnateur') then raise exception 'access_denied' using errcode='42501'; end if;
 if not exists(select 1 from public.suivi_des_edt where id=p_edt_id and statut='Complété') then raise exception 'edt_not_completed'; end if;
 if (select count(*) from public.email_outbox where edt_id=p_edt_id and requested_by=auth.uid() and created_at>now()-interval '1 hour')>=3 then raise exception 'email_rate_limit'; end if;
 if p_resend then
   insert into public.email_outbox(event_type,edt_id,idempotency_key,status,manual_resend,requested_by)
   values('edt_completed_report_sent',p_edt_id,'edt_completed_report_sent:'||p_edt_id::text||':manual:'||gen_random_uuid()::text,'pending',true,auth.uid()) returning id into v_id;
 else
   update public.email_outbox set status='pending',attempt_count=0,next_attempt_at=now(),last_error=null,requested_by=auth.uid(),updated_at=now()
   where edt_id=p_edt_id and event_type='edt_completed_report_sent' and not manual_resend and status='failed' returning id into v_id;
   if v_id is null and not exists(select 1 from public.email_outbox where edt_id=p_edt_id and event_type='edt_completed_report_sent') then
     insert into public.email_outbox(event_type,edt_id,idempotency_key,status,manual_resend,requested_by)
     values('edt_completed_report_sent',p_edt_id,'edt_completed_report_sent:'||p_edt_id::text||':manual:'||gen_random_uuid()::text,'pending',true,auth.uid()) returning id into v_id;
   end if;
 end if;
 if v_id is null then raise exception 'retry_not_available'; end if;
 return v_id;
end$$;
revoke all on function public.request_edt_email_retry_v131(bigint,boolean) from public,anon,authenticated;
grant execute on function public.request_edt_email_retry_v131(bigint,boolean) to authenticated;

create or replace function public.edt_email_status_v131(p_edt_id bigint)
returns table(status text,recipient_email text,sent_at timestamptz,last_error text,report_version integer)
language plpgsql stable security definer set search_path=public,pg_temp as $$
begin
 if auth.uid() is null or public.current_app_role() not in ('Administrateur','Coordonnateur') then raise exception 'access_denied' using errcode='42501'; end if;
 return query
 select o.status,l.recipient_email,l.sent_at,coalesce(o.last_error,l.last_error),coalesce(o.report_version,l.report_version)
 from public.email_outbox o left join lateral(select * from public.email_delivery_log d where d.outbox_id=o.id order by d.created_at desc limit 1)l on true
 where o.edt_id=p_edt_id order by o.created_at desc limit 1;
end
$$;
revoke all on function public.edt_email_status_v131(bigint) from public,anon,authenticated;
grant execute on function public.edt_email_status_v131(bigint) to authenticated;

-- Réclamation atomique réservée au worker serveur; récupère aussi les verrous expirés.
create or replace function public.claim_edt_completion_email_v131(p_edt_id bigint default null,p_limit integer default 20)
returns setof public.email_outbox language plpgsql security definer set search_path=public,pg_temp as $$
begin
 if auth.role()<>'service_role' then raise exception 'service_role_required' using errcode='42501'; end if;
 return query
 with candidates as (
  select o.id from public.email_outbox o
  where (p_edt_id is null or o.edt_id=p_edt_id)
    and o.attempt_count<5 and o.next_attempt_at<=now()
    and (o.status in ('pending','failed') or (o.status='sending' and o.locked_at<now()-interval '15 minutes'))
  order by o.created_at for update skip locked limit least(greatest(coalesce(p_limit,20),1),20)
 )
 update public.email_outbox o set status='sending',attempt_count=o.attempt_count+1,locked_at=now(),updated_at=now()
 from candidates c where o.id=c.id returning o.*;
end$$;
revoke all on function public.claim_edt_completion_email_v131(bigint,integer) from public,anon,authenticated;
grant execute on function public.claim_edt_completion_email_v131(bigint,integer) to service_role;

create or replace function public.edt_email_activity_v131() returns trigger
language plpgsql security definer set search_path=public,pg_temp as $$
begin
 insert into public.activity_events(occurred_at,actor_id,actor_email,action,module,entity_type,entity_id,edt_id,source,status,metadata,source_system,source_record_id,source_occurred_at,reconstruction_method,confidence)
 values(now(),null,null,case when new.status='sent' then 'rapport_envoye' else 'envoi_echoue' end,'Rapports EDT','edt_email',new.id::text,new.edt_id::text,'email_delivery_log',new.status,jsonb_build_object('event_type',new.event_type,'report_id',new.report_id,'report_version',new.report_version,'manual_resend',new.manual_resend),'email_delivery_log',new.id::text,now(),'direct','exact');
 return new;
end$$;
revoke all on function public.edt_email_activity_v131() from public,anon,authenticated;
create trigger edt_email_activity_v131 after insert on public.email_delivery_log for each row execute function public.edt_email_activity_v131();

commit;
