-- Recovery post-V1.3.1 : convergence additive/idempotente depuis un état hybride.
-- Ne rejoue pas V1_3_1_EDT_COMPLETION_EMAIL_WORKFLOW.sql et ne supprime aucune donnée.
begin;

alter table public.suivi_des_edt add column if not exists requester_contact_id bigint;
do $$ begin
 if not exists(select 1 from pg_constraint where conrelid='public.suivi_des_edt'::regclass and contype='f' and pg_get_constraintdef(oid) like 'FOREIGN KEY (requester_contact_id) REFERENCES utilisateurs(id)%') then
  alter table public.suivi_des_edt add constraint suivi_des_edt_requester_contact_id_fkey foreign key(requester_contact_id) references public.utilisateurs(id) on delete restrict;
 end if;
end$$;
create index if not exists suivi_des_edt_requester_idx on public.suivi_des_edt(requester_contact_id);

create table if not exists public.email_outbox(id bigint generated by default as identity primary key);
alter table public.email_outbox
 add column if not exists id bigint generated by default as identity,
 add column if not exists event_type text,
 add column if not exists edt_id bigint,
 add column if not exists idempotency_key text,
 add column if not exists report_id uuid,
 add column if not exists report_version integer,
 add column if not exists status text default 'pending',
 add column if not exists attempt_count integer default 0,
 add column if not exists next_attempt_at timestamptz default now(),
 add column if not exists locked_at timestamptz,
 add column if not exists last_error text,
 add column if not exists manual_resend boolean default false,
 add column if not exists requested_by uuid,
 add column if not exists created_at timestamptz default now(),
 add column if not exists updated_at timestamptz default now();

create table if not exists public.email_delivery_log(id bigint generated by default as identity primary key);
alter table public.email_delivery_log
 add column if not exists id bigint generated by default as identity,
 add column if not exists outbox_id bigint,
 add column if not exists event_type text,
 add column if not exists edt_id bigint,
 add column if not exists report_id uuid,
 add column if not exists report_version integer,
 add column if not exists recipient_email text,
 add column if not exists sender_email text default 'noreply@groupetos.com',
 add column if not exists provider text default 'microsoft_graph',
 add column if not exists provider_message_id text,
 add column if not exists status text,
 add column if not exists attempt_count integer,
 add column if not exists sent_at timestamptz,
 add column if not exists last_error text,
 add column if not exists manual_resend boolean default false,
 add column if not exists created_at timestamptz default now();

-- Refuse un schéma homonyme incompatible plutôt que de convertir ou perdre des données.
do $$
declare mismatch text;
begin
 select string_agg(format('%I.%I attendu=%s réel=%s',table_name,column_name,expected_type,data_type),', ')
 into mismatch from (values
  ('email_outbox','id','bigint'),('email_outbox','edt_id','bigint'),('email_outbox','report_id','uuid'),('email_outbox','attempt_count','integer'),
  ('email_delivery_log','id','bigint'),('email_delivery_log','outbox_id','bigint'),('email_delivery_log','edt_id','bigint'),('email_delivery_log','report_id','uuid'),
  ('suivi_des_edt','requester_contact_id','bigint')
 ) expected(table_name,column_name,expected_type)
 join information_schema.columns c using(table_name,column_name)
 where c.table_schema='public' and c.data_type<>expected.expected_type;
 if mismatch is not null then raise exception 'v1311_incompatible_column_types: %',mismatch; end if;
end$$;

-- Contraintes nommées ajoutées seulement lorsqu'aucune contrainte équivalente n'existe.
do $$ begin
 if not exists(select 1 from pg_constraint where conrelid='public.email_outbox'::regclass and contype='p') then alter table public.email_outbox add constraint email_outbox_pkey primary key(id); end if;
 if not exists(select 1 from pg_constraint where conrelid='public.email_delivery_log'::regclass and contype='p') then alter table public.email_delivery_log add constraint email_delivery_log_pkey primary key(id); end if;
 if not exists(select 1 from pg_constraint where conrelid='public.email_outbox'::regclass and contype='u' and pg_get_constraintdef(oid)='UNIQUE (idempotency_key)') then alter table public.email_outbox add constraint email_outbox_idempotency_key_key unique(idempotency_key); end if;
 if not exists(select 1 from pg_constraint where conrelid='public.email_outbox'::regclass and contype='f' and pg_get_constraintdef(oid) like 'FOREIGN KEY (edt_id) REFERENCES suivi_des_edt(id)%') then alter table public.email_outbox add constraint email_outbox_edt_id_fkey foreign key(edt_id) references public.suivi_des_edt(id) on delete restrict; end if;
 if not exists(select 1 from pg_constraint where conrelid='public.email_outbox'::regclass and contype='f' and pg_get_constraintdef(oid) like 'FOREIGN KEY (report_id) REFERENCES edt_reports(id)%') then alter table public.email_outbox add constraint email_outbox_report_id_fkey foreign key(report_id) references public.edt_reports(id) on delete restrict; end if;
 if not exists(select 1 from pg_constraint where conrelid='public.email_delivery_log'::regclass and contype='f' and pg_get_constraintdef(oid) like 'FOREIGN KEY (outbox_id) REFERENCES email_outbox(id)%') then alter table public.email_delivery_log add constraint email_delivery_log_outbox_id_fkey foreign key(outbox_id) references public.email_outbox(id) on delete restrict; end if;
 if not exists(select 1 from pg_constraint where conrelid='public.email_delivery_log'::regclass and contype='f' and pg_get_constraintdef(oid) like 'FOREIGN KEY (edt_id) REFERENCES suivi_des_edt(id)%') then alter table public.email_delivery_log add constraint email_delivery_log_edt_id_fkey foreign key(edt_id) references public.suivi_des_edt(id) on delete restrict; end if;
 if not exists(select 1 from pg_constraint where conrelid='public.email_delivery_log'::regclass and contype='f' and pg_get_constraintdef(oid) like 'FOREIGN KEY (report_id) REFERENCES edt_reports(id)%') then alter table public.email_delivery_log add constraint email_delivery_log_report_id_fkey foreign key(report_id) references public.edt_reports(id) on delete restrict; end if;
 if not exists(select 1 from pg_constraint where conrelid='public.email_outbox'::regclass and conname='email_outbox_event_type_check') then alter table public.email_outbox add constraint email_outbox_event_type_check check(event_type in ('edt_completed_report_sent')); end if;
 if not exists(select 1 from pg_constraint where conrelid='public.email_outbox'::regclass and conname='email_outbox_status_check') then alter table public.email_outbox add constraint email_outbox_status_check check(status in ('pending','sending','sent','failed')); end if;
 if not exists(select 1 from pg_constraint where conrelid='public.email_outbox'::regclass and conname='email_outbox_attempt_count_check') then alter table public.email_outbox add constraint email_outbox_attempt_count_check check(attempt_count between 0 and 5); end if;
 if not exists(select 1 from pg_constraint where conrelid='public.email_delivery_log'::regclass and conname='email_delivery_log_status_check') then alter table public.email_delivery_log add constraint email_delivery_log_status_check check(status in ('sent','failed')); end if;
end$$;

-- Les objets d'origine ont ces colonnes NOT NULL; un état hybride vide peut converger sans réécriture.
do $$ begin
 if exists(select 1 from public.email_outbox where event_type is null or edt_id is null or idempotency_key is null or status is null or attempt_count is null or next_attempt_at is null or manual_resend is null or created_at is null or updated_at is null) then raise exception 'v1311_outbox_required_values_missing'; end if;
 if exists(select 1 from public.email_delivery_log where outbox_id is null or event_type is null or edt_id is null or sender_email is null or provider is null or status is null or attempt_count is null or manual_resend is null or created_at is null) then raise exception 'v1311_delivery_required_values_missing'; end if;
 alter table public.email_outbox alter column event_type set not null,alter column edt_id set not null,alter column idempotency_key set not null,alter column status set not null,alter column attempt_count set not null,alter column next_attempt_at set not null,alter column manual_resend set not null,alter column created_at set not null,alter column updated_at set not null;
 alter table public.email_delivery_log alter column outbox_id set not null,alter column event_type set not null,alter column edt_id set not null,alter column sender_email set not null,alter column provider set not null,alter column status set not null,alter column attempt_count set not null,alter column manual_resend set not null,alter column created_at set not null;
end$$;

create unique index if not exists email_outbox_automatic_completion_uq on public.email_outbox(edt_id,event_type) where not manual_resend;
create index if not exists email_outbox_worker_idx on public.email_outbox(status,next_attempt_at);
create unique index if not exists email_delivery_log_success_uq on public.email_delivery_log(edt_id,event_type,report_version) where status='sent' and not manual_resend;
create index if not exists email_delivery_log_edt_idx on public.email_delivery_log(edt_id,created_at desc);

alter table public.email_outbox enable row level security;
alter table public.email_delivery_log enable row level security;
revoke all on public.email_outbox,public.email_delivery_log from public,anon,authenticated;
grant select on public.email_outbox,public.email_delivery_log to authenticated;
drop policy if exists email_outbox_staff_read_v131 on public.email_outbox;
create policy email_outbox_staff_read_v131 on public.email_outbox for select to authenticated using(public.current_app_role() in ('Administrateur','Coordonnateur'));
drop policy if exists email_delivery_staff_read_v131 on public.email_delivery_log;
create policy email_delivery_staff_read_v131 on public.email_delivery_log for select to authenticated using(public.current_app_role() in ('Administrateur','Coordonnateur'));

create or replace function public.validate_edt_requester_v131() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare v_requester_client bigint;v_edt_client bigint;
begin
 if new.requester_contact_id is null then return new; end if;
 select client_id into v_requester_client from public.utilisateurs where id=new.requester_contact_id;
 select client_id into v_edt_client from public.campagnes_maitres where id=new.campagne_id;
 if v_requester_client is null or v_edt_client is null or v_requester_client<>v_edt_client then raise exception 'requester_client_mismatch' using errcode='23514'; end if;
 return new;
end$$;
revoke all on function public.validate_edt_requester_v131() from public,anon,authenticated;

create or replace function public.enqueue_edt_completion_email_v131() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin
 if old.statut is distinct from 'Complété' and new.statut='Complété' then
  insert into public.email_outbox(event_type,edt_id,idempotency_key,status,last_error) values('edt_completed_report_sent',new.id,'edt_completed_report_sent:'||new.id::text,'pending',case when new.requester_contact_id is null then 'Requérant sans adresse courriel' end)
  on conflict(edt_id,event_type) where not manual_resend do nothing;
 end if;
 return new;
end$$;
revoke all on function public.enqueue_edt_completion_email_v131() from public,anon,authenticated;

create or replace function public.request_edt_email_retry_v131(p_edt_id bigint,p_resend boolean default false) returns bigint language plpgsql security definer set search_path=public,pg_temp as $$
declare v_id bigint;
begin
 if auth.uid() is null or public.current_app_role() not in ('Administrateur','Coordonnateur') then raise exception 'access_denied' using errcode='42501'; end if;
 if not exists(select 1 from public.suivi_des_edt where id=p_edt_id and statut='Complété') then raise exception 'edt_not_completed'; end if;
 if (select count(*) from public.email_outbox where edt_id=p_edt_id and requested_by=auth.uid() and created_at>now()-interval '1 hour')>=3 then raise exception 'email_rate_limit'; end if;
 if p_resend then
  insert into public.email_outbox(event_type,edt_id,idempotency_key,status,manual_resend,requested_by) values('edt_completed_report_sent',p_edt_id,'edt_completed_report_sent:'||p_edt_id::text||':manual:'||gen_random_uuid()::text,'pending',true,auth.uid()) returning id into v_id;
 else
  update public.email_outbox set status='pending',attempt_count=0,next_attempt_at=now(),last_error=null,requested_by=auth.uid(),updated_at=now() where edt_id=p_edt_id and event_type='edt_completed_report_sent' and not manual_resend and status='failed' returning id into v_id;
  if v_id is null and not exists(select 1 from public.email_outbox where edt_id=p_edt_id and event_type='edt_completed_report_sent') then insert into public.email_outbox(event_type,edt_id,idempotency_key,status,manual_resend,requested_by) values('edt_completed_report_sent',p_edt_id,'edt_completed_report_sent:'||p_edt_id::text||':manual:'||gen_random_uuid()::text,'pending',true,auth.uid()) returning id into v_id; end if;
 end if;
 if v_id is null then raise exception 'retry_not_available'; end if;
 return v_id;
end$$;
revoke all on function public.request_edt_email_retry_v131(bigint,boolean) from public,anon,authenticated;
grant execute on function public.request_edt_email_retry_v131(bigint,boolean) to authenticated;

create or replace function public.edt_email_status_v131(p_edt_id bigint) returns table(status text,recipient_email text,sent_at timestamptz,last_error text,report_version integer) language plpgsql stable security definer set search_path=public,pg_temp as $$
begin
 if auth.uid() is null or public.current_app_role() not in ('Administrateur','Coordonnateur') then raise exception 'access_denied' using errcode='42501'; end if;
 return query select o.status,l.recipient_email,l.sent_at,coalesce(o.last_error,l.last_error),coalesce(o.report_version,l.report_version) from public.email_outbox o left join lateral(select * from public.email_delivery_log d where d.outbox_id=o.id order by d.created_at desc limit 1)l on true where o.edt_id=p_edt_id order by o.created_at desc limit 1;
end$$;
revoke all on function public.edt_email_status_v131(bigint) from public,anon,authenticated;
grant execute on function public.edt_email_status_v131(bigint) to authenticated;

create or replace function public.claim_edt_completion_email_v131(p_edt_id bigint default null,p_limit integer default 20) returns setof public.email_outbox language plpgsql security definer set search_path=public,pg_temp as $$
begin
 if auth.role()<>'service_role' then raise exception 'service_role_required' using errcode='42501'; end if;
 return query with candidates as (select o.id from public.email_outbox o where (p_edt_id is null or o.edt_id=p_edt_id) and o.attempt_count<5 and o.next_attempt_at<=now() and (o.status in ('pending','failed') or (o.status='sending' and o.locked_at<now()-interval '15 minutes')) order by o.created_at for update skip locked limit least(greatest(coalesce(p_limit,20),1),20)) update public.email_outbox o set status='sending',attempt_count=o.attempt_count+1,locked_at=now(),updated_at=now() from candidates c where o.id=c.id returning o.*;
end$$;
revoke all on function public.claim_edt_completion_email_v131(bigint,integer) from public,anon,authenticated;
grant execute on function public.claim_edt_completion_email_v131(bigint,integer) to service_role;

create or replace function public.edt_email_activity_v131() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin
 insert into public.activity_events(occurred_at,actor_id,actor_email,action,module,entity_type,entity_id,edt_id,source,status,metadata,source_system,source_record_id,source_occurred_at,reconstruction_method,confidence) values(now(),null,null,case when new.status='sent' then 'rapport_envoye' else 'envoi_echoue' end,'Rapports EDT','edt_email',new.id::text,new.edt_id::text,'email_delivery_log',new.status,jsonb_build_object('event_type',new.event_type,'report_id',new.report_id,'report_version',new.report_version,'manual_resend',new.manual_resend),'email_delivery_log',new.id::text,now(),'direct','exact');
 return new;
end$$;
revoke all on function public.edt_email_activity_v131() from public,anon,authenticated;

-- Seuls les triggers V1.3.1 nommés sont remplacés, dans la même transaction.
drop trigger if exists validate_edt_requester_v131 on public.suivi_des_edt;
create trigger validate_edt_requester_v131 before insert or update of requester_contact_id,campagne_id on public.suivi_des_edt for each row execute function public.validate_edt_requester_v131();
drop trigger if exists enqueue_edt_completion_email_v131 on public.suivi_des_edt;
create trigger enqueue_edt_completion_email_v131 after update of statut on public.suivi_des_edt for each row execute function public.enqueue_edt_completion_email_v131();
drop trigger if exists edt_email_activity_v131 on public.email_delivery_log;
create trigger edt_email_activity_v131 after insert on public.email_delivery_log for each row execute function public.edt_email_activity_v131();

commit;
