-- STRICTEMENT READ ONLY. À exécuter séparément après la migration, jamais avant approbation.
select table_name,column_name,data_type from information_schema.columns where table_schema='public' and ((table_name='campagnes_maitres' and column_name in ('client_id','client_published')) or column_name='client_visible') order by table_name,column_name;
select table_name from information_schema.tables where table_schema='public' and table_name in ('client_campaign_access','client_member_invitations') order by table_name;
select routine_name,security_type from information_schema.routines where routine_schema='public' and routine_name like '%client%v120' order by routine_name;
select schemaname,tablename,policyname,cmd,roles,qual,with_check from pg_policies where schemaname in ('public','storage') and policyname like '%v120' order by tablename,policyname;
select c.business_context,count(*) total,count(*) filter(where nullif(to_jsonb(c)->>'client_id','') is null) sans_client,count(*) filter(where coalesce((to_jsonb(c)->>'client_published')::boolean,false)) publiees from public.campagnes_maitres c group by c.business_context order by c.business_context;
select to_jsonb(c)->>'client_id' client_id,c.id campaign_id,count(*) logical_rows,count(distinct concat_ws('|',i.site,cs.support_id,c.id,coalesce(v.id::text,cs.visuel_attendu,''))) unique_rows from public.campagnes_maitres c join public.campagnes_supports cs on cs.campagne_id=c.id join public.infrastructures i on i.support_id=cs.support_id left join public.campagne_visuels_formats v on v.campagne_id=c.id and (v.nom_visuel=cs.visuel_attendu or v.id is null) group by to_jsonb(c)->>'client_id',c.id having count(*)<>count(distinct concat_ws('|',i.site,cs.support_id,c.id,coalesce(v.id::text,cs.visuel_attendu,'')));
select u.client_id,u.role,count(*) from public.utilisateurs u where u.role in ('Client','Client-Admin') group by u.client_id,u.role order by u.client_id,u.role;
select count(*) invalid_client_profiles from public.utilisateurs where role in ('Client','Client-Admin') and client_id is null;
select count(*) public_support_photo_policies from pg_policies where schemaname='public' and tablename='support_photos' and ('public'=any(roles) or 'anon'=any(roles));
select id,name,public,file_size_limit,allowed_mime_types from storage.buckets where id in ('support-photos','terrain-photos') order by id;
select policyname,cmd,roles,qual,with_check from pg_policies where schemaname='storage' and tablename='objects' and (policyname ilike '%support%photo%' or policyname ilike '%terrain%photo%') order by policyname;
select count(*) unexpected_support_photos_public_policies from pg_policies where schemaname='storage' and tablename='objects' and ('public'=any(roles) or 'anon'=any(roles)) and coalesce(qual,'') ilike '%support-photos%';
select count(*) support_photos_bucket_public from storage.buckets where id='support-photos' and public;
select count(*) client_visible_photo_without_campaign from public.support_photos p left join public.campagnes_maitres c on c.id=p.campagne_id where coalesce((to_jsonb(p)->>'client_visible')::boolean,false) and (p.campagne_id is null or nullif(to_jsonb(c)->>'client_id','') is null or not coalesce((to_jsonb(c)->>'client_published')::boolean,false));
select column_name,data_type from information_schema.columns where table_schema='public' and table_name='suivi_des_edt' and column_name in ('no_edt','date_debut_prevue','date_fin_prevue','numero_edt','date_debut','date_fin') order by column_name;
select p.proname,r.rolname owner,p.prosecdef security_definer,p.proconfig configuration,has_function_privilege('anon',p.oid,'execute') anon_execute,has_function_privilege('authenticated',p.oid,'execute') authenticated_execute from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_roles r on r.oid=p.proowner where n.nspname='public' and p.proname in ('client_portal_identity_v120','client_can_access_campaign_v120','client_portal_list_v120','client_admin_invite_member_v120','client_admin_deactivate_member_v120','client_admin_set_campaign_access_v120') order by p.proname;
select count(*) rpc_without_safe_search_path from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like '%v120' and p.proname like '%client%' and not coalesce(p.proconfig,'{}') @> array['search_path=public, auth'];
