import{supabase,supabaseConfigured}from'../lib/supabaseClient';
import{generateFinalReportPdf,normalizeFinalReportContext,uploadFinalReport}from'./finalReportService';
const ready=()=>{if(!supabaseConfigured||!supabase)throw new Error('Service de rapports indisponible.')};
const rows=(store,name)=>store?.[name]?.rows||[];
const text=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const latestBy=(items,key)=>[...items].sort((a,b)=>(b[key]||0)-(a[key]||0))[0]||null;
export const businessEmailError=value=>{const message=text(value);if(message.includes('requerant')||message.includes('recipient'))return'Requérant sans courriel';if(message.includes('missing_final_report')||message.includes('rapport'))return'Rapport final manquant';return'Envoi temporairement impossible'};
export async function listEdtReports(){ready();const{data,error}=await supabase.from('edt_reports').select('*').order('report_version',{ascending:false});if(error)throw error;return data||[]}
export async function listCompletedEdt(){ready();const{data,error}=await supabase.from('suivi_des_edt').select('*').eq('statut','Complété').order('date_fin',{ascending:false,nullsFirst:false});if(error)throw error;return data||[]}
export async function loadEdtReportTracking(dataStore={}){ready();const results=await Promise.all([listCompletedEdt(),listEdtReports(),supabase.from('email_outbox').select('*').order('created_at',{ascending:false}),supabase.from('email_delivery_log').select('*').order('created_at',{ascending:false}),supabase.from('utilisateurs').select('id,nom,courriel,client_id'),supabase.from('campagnes_maitres').select('id,nom_campagne,business_context,client_id')]);for(const result of results.slice(2))if(result.error)throw result.error;const[edt,reports,outboxResult,logResult,contactsResult,campaignsResult]=results,outbox=outboxResult.data||[],logs=logResult.data||[],contacts=contactsResult.data||[],campaigns=campaignsResult.data||[];const tracking=edt.map(item=>{const report=latestBy(reports.filter(r=>String(r.edt_id)===String(item.id)),'report_version'),event=outbox.find(o=>String(o.edt_id)===String(item.id)),delivery=event&&logs.find(l=>String(l.outbox_id)===String(event.id)),requester=contacts.find(c=>String(c.id)===String(item.requester_contact_id)),campaign=campaigns.find(c=>String(c.id)===String(item.campagne_id));const deliveryStatus=event?.status==='sent'?'Envoyé':event?.status==='failed'?'Erreur':event?.status==='pending'||event?.status==='sending'?'En attente':'Non envoyé';const reportStatus=!report?'À générer':report.status==='error'?'Erreur':deliveryStatus==='sent'?'Envoyé':'Prêt à envoyer';return{...item,no_edt:item.no_edt||'—',campaign_name:campaign?.nom_campagne||item.campagne||'—',edt_type:campaign?.business_context==='operational_communication'?'Communication':'Campagne',requester_name:requester?.nom||'Non défini',requester_email:requester?.courriel||'Non disponible',report_status:reportStatus,delivery_status:deliveryStatus,sent_at:delivery?.sent_at||null,delivery_error:event?.last_error?businessEmailError(event.last_error):'',report,event,delivery}});return{tracking,kpis:{completed:tracking.length,toSend:tracking.filter(r=>['Non envoyé','En attente'].includes(r.delivery_status)).length,sent:tracking.filter(r=>r.delivery_status==='Envoyé').length,errors:tracking.filter(r=>r.delivery_status==='Erreur'||r.report_status==='Erreur').length},dataStore}}
export async function generateEdtReport(row,dataStore={}){ready();if(!row.requester_contact_id)throw new Error('Requérant sans courriel');const campaigns=rows(dataStore,'Campagnes et visuels'),clients=rows(dataStore,'Clients'),supports=rows(dataStore,'Infrastructures').filter(s=>String(s.edt_associe||s.no_edt)===String(row.no_edt)),issues=rows(dataStore,'Enjeux des cadres et supports').filter(i=>supports.some(s=>String(s.support_id)===String(i.support_id))),campaign=campaigns.find(c=>String(c.id)===String(row.campagne_id))||{nom_campagne:row.campaign_name},client=clients.find(c=>String(c.id)===String(campaign.client_id))||{nom:row.client};const context=normalizeFinalReportContext({edt:row,campaign,client,issues,supports,requester:{nom:row.requester_name,courriel:row.requester_email}}),blob=await generateFinalReportPdf(context),path=await uploadFinalReport({blob,context,edtId:row.id}),{data,error}=await supabase.rpc('create_edt_report_v1301',{p_edt_id:Number(row.id),p_report_path:path,p_storage_bucket:'final-reports',p_client_visible:Boolean(row.client_visible)});if(error)throw error;return data}
export async function downloadEdtReport(report,open=false){ready();if(!report?.report_path)throw new Error('Rapport final manquant');const{data,error}=await supabase.storage.from(report.storage_bucket||'final-reports').download(report.report_path);if(error)throw error;const url=URL.createObjectURL(data);if(open)window.open(url,'_blank','noopener,noreferrer');else{const link=document.createElement('a');link.href=url;link.download=`Rapport-EDT-${report.edt_id}-v${report.report_version}.pdf`;link.click()}setTimeout(()=>URL.revokeObjectURL(url),30000)}
export async function requestEdtEmail(edtId,resend=false){ready();const{data,error}=await supabase.rpc('request_edt_email_retry_v131',{p_edt_id:Number(edtId),p_resend:Boolean(resend)});if(error)throw error;return data}
export async function processEdtEmail(edtId){ready();const{data,error}=await supabase.functions.invoke('send-edt-completion-email',{body:{edt_id:Number(edtId)}});if(error)throw error;return data}
