import{supabase,supabaseConfigured}from'../lib/supabaseClient';
import{createReportDraft,parseRecipients,reportFileName,uniqueReportSupports,validateReportIntegrity}from'../lib/module15ReportModel';
import{generateEdtReportPdf,uploadFinalReport}from'./finalReportService';
const ready=()=>{if(!supabaseConfigured||!supabase)throw new Error('Service de rapports indisponible.')};
const text=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const latestBy=(items,key)=>[...items].sort((a,b)=>(b[key]||0)-(a[key]||0))[0]||null;
const values=result=>{if(result.error)throw result.error;return result.data||[]};
export const businessEmailError=value=>{const message=text(value);if(message.includes('requerant')||message.includes('recipient'))return'Requérant sans courriel';if(message.includes('missing_final_report')||message.includes('rapport'))return'Rapport final manquant';return'Envoi temporairement impossible'};
export async function listEdtReports(){ready();return values(await supabase.from('edt_reports').select('*').order('report_version',{ascending:false}))}
export async function listCompletedEdt(){ready();return values(await supabase.from('suivi_des_edt').select('*').eq('statut','Complété').order('date_fin',{ascending:false,nullsFirst:false}))}

export async function loadEdtReportTracking(dataStore={}){
  ready();const results=await Promise.all([listCompletedEdt(),listEdtReports(),supabase.from('email_outbox').select('*').order('created_at',{ascending:false}),supabase.from('email_delivery_log').select('*').order('created_at',{ascending:false}),supabase.from('utilisateurs').select('id,nom,courriel,client_id'),supabase.from('campagnes_maitres').select('id,nom_campagne,business_context,client_id')]);
  const[edt,reports,outboxResult,logResult,contactsResult,campaignsResult]=results,outbox=values(outboxResult),logs=values(logResult),contacts=values(contactsResult),campaigns=values(campaignsResult);
  const tracking=edt.map(item=>{const versions=reports.filter(r=>String(r.edt_id)===String(item.id)).sort((a,b)=>b.report_version-a.report_version),report=versions[0]||null,event=outbox.find(o=>String(o.edt_id)===String(item.id)),deliveries=logs.filter(l=>String(l.edt_id)===String(item.id)),delivery=event&&deliveries.find(l=>String(l.outbox_id)===String(event.id)),requester=contacts.find(c=>String(c.id)===String(item.requester_contact_id)),campaign=campaigns.find(c=>String(c.id)===String(item.campagne_id)),deliveryStatus=delivery?.status==='sent'||event?.status==='sent'?'Envoyé':event?.status==='failed'?'Erreur':event?.status==='pending'||event?.status==='sending'?'En attente':'Non envoyé';return{...item,no_edt:item.no_edt||'—',campaign_name:campaign?.nom_campagne||item.campagne||'—',edt_type:campaign?.business_context==='operational_communication'?'Communication':'Campagne',requester_name:requester?.nom||'Non défini',requester_email:requester?.courriel||'Non disponible',report_status:!report?'À générer':report.status==='error'?'Erreur':deliveryStatus==='Envoyé'?'Envoyé':'Prêt à envoyer',delivery_status:deliveryStatus,sent_at:delivery?.sent_at||null,delivery_error:event?.last_error?businessEmailError(event.last_error):'',report,versions,deliveries,event,delivery,support_count:report?.support_count??report?.content_snapshot?.source_support_count??0}});
  return{tracking,kpis:{completed:tracking.length,toSend:tracking.filter(r=>['Non envoyé','En attente'].includes(r.delivery_status)).length,sent:tracking.filter(r=>r.delivery_status==='Envoyé').length,errors:tracking.filter(r=>r.delivery_status==='Erreur'||r.report_status==='Erreur').length},dataStore};
}

export async function loadEdtReportSource(row,report=null){
  ready();const assignments=values(await supabase.from('edt_supports').select('*').eq('edt_id',row.id));const supportIds=[...new Set(assignments.map(item=>item.support_id).filter(Boolean))];
  const [infraResult,photoResult,issueResult]=supportIds.length?await Promise.all([supabase.from('infrastructures').select('*').in('support_id',supportIds),supabase.from('support_photos').select('id,support_id,edt_id,type_photo,est_principale,thumbnail_url,photo_url,storage_bucket,storage_path,captured_at').in('support_id',supportIds),supabase.from('enjeux_terrain').select('*').in('support_id',supportIds)]):[{data:[]},{data:[]},{data:[]}];
  const infrastructures=values(infraResult),photos=values(photoResult),issues=values(issueResult),infraById=new Map(infrastructures.map(item=>[String(item.support_id),item]));
  const supports=uniqueReportSupports(assignments.map(item=>{const infra=infraById.get(String(item.support_id))||{};return{edt_id:row.id,assignment_id:item.id,support_id:item.support_id,site:infra.site||infra.no_arret||'—',infrastructure:infra.type_support||infra.infrastructure||'—',location:infra.emplacement_visibilite||infra.emplacement||'—',campaign_id:row.campagne_id,campaign:row.campaign_name,visual:item.visuel_attendu||infra.visuel_actuel_cadre||'—',format:item.format||infra.format||'—',installation_status:item.statut||'—',installation_date:item.date_completion||null,removal_date:item.date_retrait||null,issue:issues.find(issue=>String(issue.support_id)===String(item.support_id))?.description||''}}));
  return createReportDraft({edt:row,supports,photos,issues,workSummary:row.travaux_realises||row.description||''},report?.content_snapshot||{});
}

export async function saveEdtReportDraft(row,draft,report=null){
  ready();const integrity=validateReportIntegrity(draft);if(!integrity.valid)throw new Error(integrity.message);const payload={p_edt_id:Number(row.id),p_title:draft.title,p_summary:draft.summary,p_conclusion:draft.conclusion,p_content_snapshot:draft,p_support_count:integrity.reportCount,p_client_visible:Boolean(row.client_visible),p_report_id:report?.status==='draft'?report.id:null};const{data,error}=await supabase.rpc('save_edt_report_draft_v132',payload);if(error)throw error;return data;
}
export async function generateEdtReport(row,draft,report=null){
  ready();const integrity=validateReportIntegrity(draft);if(!integrity.valid)throw new Error(integrity.message);const blob=await generateEdtReportPdf(draft),version=report?.status==='draft'?report.report_version:(Math.max(0,...(row.versions||[]).map(item=>Number(item.report_version)||0))+1),path=await uploadFinalReport({blob,context:{edtNumber:draft.edt.no_edt},edtId:row.id});const{data,error}=await supabase.rpc('finalize_edt_report_v132',{p_edt_id:Number(row.id),p_report_id:report?.status==='draft'?report.id:null,p_report_path:path,p_storage_bucket:'final-reports',p_title:draft.title,p_summary:draft.summary,p_conclusion:draft.conclusion,p_content_snapshot:draft,p_support_count:integrity.reportCount,p_client_visible:Boolean(row.client_visible)});if(error)throw error;return{data,blob,version,path};
}
export async function previewEdtReport(draft){const blob=await generateEdtReportPdf(draft),url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),30000)}
export async function downloadEdtReport(report,open=false){ready();if(!report?.report_path)throw new Error('Rapport final manquant');const{data,error}=await supabase.storage.from(report.storage_bucket||'final-reports').download(report.report_path);if(error)throw error;const url=URL.createObjectURL(data);if(open)window.open(url,'_blank','noopener,noreferrer');else{const link=document.createElement('a');link.href=url;link.download=reportFileName(report.content_snapshot||{edt:{no_edt:report.edt_id}},report.report_version);link.click()}setTimeout(()=>URL.revokeObjectURL(url),30000)}
export async function requestEdtEmail(edtId,resend=false,options={}){ready();const recipients=parseRecipients(options.recipients||[]);if(recipients.invalid.length||!recipients.valid.length)throw new Error('Un ou plusieurs destinataires sont invalides.');const{data,error}=await supabase.rpc('request_edt_report_email_v132',{p_edt_id:Number(edtId),p_report_id:options.reportId,p_recipients:recipients.valid,p_message:options.message||'',p_resend:Boolean(resend)});if(error)throw error;return data}
export async function processEdtEmail(edtId){ready();const{data,error}=await supabase.functions.invoke('send-edt-completion-email',{body:{edt_id:Number(edtId)}});if(error)throw error;return data}
