import React,{useEffect,useRef,useState}from'react';import{AlertTriangle,Save,Undo2}from'lucide-react';
import useFieldPermissionDraft from'../../hooks/useFieldPermissionDraft.js';
import{CANONICAL_APP_ROLES,permissionContradictions,resolvePermissionSimulation}from'../../lib/fieldCatalogPermissionDraft.js';
import'../../features/v13/field-catalog-permission.css';
const choices=[['','Hériter'],['true','Autoriser'],['false','Refuser']];const decode=v=>v===''?null:v==='true';
function Choice({label,value,onChange,disabled,name}){return <label>{label}<select name={name} value={value===null?'':String(value)} disabled={disabled} onChange={e=>onChange(decode(e.target.value))}>{choices.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
export default function FieldCatalogPermissionTab({field,role,onSaved,onDirtyChange,onSaveActionChange}){const state=useFieldPermissionDraft({field,role,onSaved,onDirtyChange});const[previewRole,setPreviewRole]=useState(CANONICAL_APP_ROLES[0]);const alertRef=useRef(null);useEffect(()=>{onSaveActionChange?.(state.save);return()=>onSaveActionChange?.(null);},[onSaveActionChange,state.save]);useEffect(()=>{if(['error','stale_draft'].includes(state.status))alertRef.current?.focus();},[state.status]);const disabled=state.protectedField||state.submitting;const conflicts=permissionContradictions(state.draft);const unknown=state.validation.unknownRoles||[];const visible=resolvePermissionSimulation({config:state.draft,role:previewRole,capability:'visible',protectedField:state.protectedField});const editable=resolvePermissionSimulation({config:state.draft,role:previewRole,capability:'editable',protectedField:state.protectedField});return <form className="field-permission-form" aria-busy={state.submitting} onSubmit={e=>{e.preventDefault();state.save();}}>
<header><h3>Permissions</h3><strong>Brouillon sans effet immédiat</strong><p>Ces réglages ne remplacent pas les politiques RLS ni les permissions serveur.</p></header>
{state.protectedField&&<aside role="note" className="field-permission-warning"><AlertTriangle/><div><strong>Champ protégé — lecture seule, aucune requête possible.</strong><ul>{state.protectionReasons.map(x=><li key={x}>{x}</li>)}</ul></div></aside>}
<fieldset><legend>Règles générales</legend><Choice label="Visibilité générale" name="permission-general-visible" value={state.draft.generalRule?.visible??null} disabled={disabled} onChange={v=>state.patch('general',null,'visible',v)}/><Choice label="Modification générale" name="permission-general-editable" value={state.draft.generalRule?.editable??null} disabled={disabled} onChange={v=>state.patch('general',null,'editable',v)}/></fieldset>
<section><h4>Matrice par rôle</h4><div className="permission-matrix" role="group" aria-label="Permissions par rôle">{CANONICAL_APP_ROLES.map(r=><fieldset key={r}><legend>{r}</legend><Choice label="Visibilité" name={`${r}-visible`} value={state.draft.roleRules?.[r]?.visible??null} disabled={disabled} onChange={v=>state.patch('role',r,'visible',v)}/><Choice label="Modification" name={`${r}-editable`} value={state.draft.roleRules?.[r]?.editable??null} disabled={disabled} onChange={v=>state.patch('role',r,'editable',v)}/></fieldset>)}</div></section>
<section><h4>Stratégie</h4><output>deny-wins · refus conservateur actif</output></section>
{(unknown.length>0||conflicts.length>0)&&<aside className="field-permission-warning" role="alert"><AlertTriangle/><div>{unknown.map(r=><p key={r}>Rôle inconnu conservé : {r} — aucun nouveau droit.</p>)}{conflicts.map(c=><p key={c}>Conflit : {c}</p>)}</div></aside>}
<section className="permission-preview"><h4>Prévisualisation administrative fictive</h4><label>Rôle simulé<select value={previewRole} onChange={e=>setPreviewRole(e.target.value)}>{CANONICAL_APP_ROLES.map(r=><option key={r}>{r}</option>)}<option value="Rôle inconnu">Rôle inconnu</option></select></label><div><p><strong>Visibilité :</strong> {visible.decision} — {visible.reasonCodes.join(', ')}</p><p><strong>Modification :</strong> {editable.decision} — {editable.reasonCodes.join(', ')}</p></div><small>Simulation locale uniquement. RLS et le serveur demeurent l’autorité réelle.</small></section>
{state.message&&<div ref={alertRef} tabIndex={-1} role={['error','stale_draft'].includes(state.status)?'alert':'status'} className={`permission-status ${state.status}`}>{state.message}{state.status==='stale_draft'&&<button type="button" onClick={()=>onSaved?.(field.fieldId)}>Recharger le brouillon</button>}</div>}
<div className="permission-actions"><button type="button" disabled={!state.dirty||state.submitting} onClick={state.cancel}><Undo2/> Annuler</button><button type="submit" disabled={!state.dirty||disabled||!state.validation.valid}><Save/>{state.submitting?'Enregistrement…':'Enregistrer le brouillon'}</button></div></form>}
