-- TOS Display Manager v0.12.9 — LOT 3
-- Photos complètes + fiche 360
-- Migration réexécutable et prudente.

begin;

create table if not exists public.photo_action_log (
  id bigint generated by default as identity primary key,
  action text not null,
  photo_id text,
  support_id text,
  nom_fichier text,
  details jsonb not null default '{}'::jsonb,
  user_id uuid default auth.uid(),
  created_at timestamptz not null default now()
);

alter table public.photo_action_log enable row level security;

drop policy if exists "photo_action_log_read_authenticated" on public.photo_action_log;
create policy "photo_action_log_read_authenticated"
on public.photo_action_log for select to authenticated using (true);

drop policy if exists "photo_action_log_insert_authenticated" on public.photo_action_log;
create policy "photo_action_log_insert_authenticated"
on public.photo_action_log for insert to authenticated with check (auth.uid() = user_id or user_id is null);

-- Colonnes facultatives ajoutées seulement si la table existe.
do $$
begin
  if to_regclass('public.support_photos') is not null then
    alter table public.support_photos add column if not exists est_principale boolean not null default false;
    alter table public.support_photos add column if not exists deleted_at timestamptz;
    alter table public.support_photos add column if not exists deleted_by uuid;
  end if;
end $$;

-- Vérifie le rôle sans dépendre d'une seule structure de profils.
create or replace function public.tos_current_role()
returns text
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  v_role text;
begin
  if to_regclass('public.profiles') is not null then
    begin
      execute 'select role::text from public.profiles where id = $1 limit 1'
        into v_role using auth.uid();
    exception when undefined_column then
      begin
        execute 'select role::text from public.profiles where user_id = $1 limit 1'
          into v_role using auth.uid();
      exception when others then null;
      end;
    end;
  end if;

  if coalesce(v_role,'') = '' then
    v_role := coalesce(
      auth.jwt()->'user_metadata'->>'role',
      auth.jwt()->'app_metadata'->>'role',
      ''
    );
  end if;
  return v_role;
end;
$$;

create or replace function public.supprimer_photo_support_v0129_lot3(p_photo_id text)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_photo record;
  v_role text;
  v_replacement record;
  v_id_type text;
begin
  v_role := public.tos_current_role();
  if v_role not in ('Administrateur','Admin','administrator','admin') then
    raise exception 'Suppression réservée aux administrateurs.' using errcode='42501';
  end if;

  if to_regclass('public.support_photos') is null then
    raise exception 'La table support_photos est absente.';
  end if;

  select data_type into v_id_type
  from information_schema.columns
  where table_schema='public' and table_name='support_photos' and column_name='id';

  if v_id_type in ('uuid') then
    execute 'select * from public.support_photos where id = $1::uuid for update'
      into v_photo using p_photo_id;
  elsif v_id_type in ('bigint','integer','smallint','numeric') then
    execute 'select * from public.support_photos where id::text = $1 for update'
      into v_photo using p_photo_id;
  else
    execute 'select * from public.support_photos where id::text = $1 for update'
      into v_photo using p_photo_id;
  end if;

  if v_photo is null then
    raise exception 'Photo introuvable.';
  end if;

  -- Supprime la ligne; Storage est supprimé ensuite par le client avec le chemin retourné.
  execute 'delete from public.support_photos where id::text = $1' using p_photo_id;

  -- Choisit une photo de remplacement.
  execute $q$
    select * from public.support_photos
    where support_id::text = $1
    order by coalesce(prise_le, created_at, now()) desc
    limit 1
  $q$ into v_replacement using v_photo.support_id::text;

  if to_regclass('public.infrastructures') is not null then
    begin
      execute $q$
        update public.infrastructures
        set photo_principale_url=$1,
            photo_miniature_url=$2
        where support_id::text=$3
      $q$ using
        case when v_replacement is null then null else v_replacement.photo_url end,
        case when v_replacement is null then null else coalesce(v_replacement.thumbnail_url,v_replacement.photo_url) end,
        v_photo.support_id::text;
    exception when undefined_column then
      null;
    end;
  end if;

  insert into public.photo_action_log(action,photo_id,support_id,nom_fichier,details,user_id)
  values ('SUPPRESSION',p_photo_id,v_photo.support_id::text,v_photo.nom_fichier,
    jsonb_build_object('storage_path',v_photo.storage_path,'replacement_id',
      case when v_replacement is null then null else v_replacement.id::text end),auth.uid());

  return jsonb_build_object(
    'ok',true,
    'photo_id',p_photo_id,
    'support_id',v_photo.support_id::text,
    'storage_path',v_photo.storage_path,
    'replacement_id',case when v_replacement is null then null else v_replacement.id::text end
  );
end;
$$;

grant execute on function public.supprimer_photo_support_v0129_lot3(text) to authenticated;
grant execute on function public.tos_current_role() to authenticated;

-- RLS explicite pour la suppression directe de repli.
do $$
begin
  if to_regclass('public.support_photos') is not null then
    alter table public.support_photos enable row level security;
    drop policy if exists "support_photos_delete_admin_v0129_lot3" on public.support_photos;
    create policy "support_photos_delete_admin_v0129_lot3"
      on public.support_photos for delete to authenticated
      using (public.tos_current_role() in ('Administrateur','Admin','administrator','admin'));
  end if;
end $$;

commit;
