import React,{useEffect,useState}from'react';
import{Eye,EyeOff,Megaphone,Pencil,Plus,Save,Trash2,X}from'lucide-react';
import{deleteOrArchiveMasterCampaign,listAssignableClients,listMasterCampaigns,saveMasterCampaign}from'../services/campaignService';
import{BUSINESS_CONTEXT,BUSINESS_CONTEXT_OPTIONS,businessContextLabel}from'../lib/businessContext';

const blank=context=>({nom_campagne:'',code_campagne:'',client:'',client_id:'',type_campagne:'Installation',visuel_generique:'',no_edt:'',statut:'Brouillon',publiee_terrain:false,instructions_terrain:'',business_context:context});
export default function CampaignsPanel({role,businessContext=BUSINESS_CONTEXT.MARKETING}){
 const[campaigns,setCampaigns]=useState([]),[clients,setClients]=useState([]),[form,setForm]=useState(()=>blank(businessContext)),[formOpen,setFormOpen]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const canManage=['Administrateur','Coordonnateur'].includes(role);
 async function reload(){try{const[campaignRows,clientRows]=await Promise.all([listMasterCampaigns(false,businessContext),listAssignableClients()]);setCampaigns(campaignRows);setClients(clientRows);}catch(e){setMessage(e.message);}}
 useEffect(()=>{setForm(blank(businessContext));setFormOpen(false);reload();},[businessContext]);
 async function submit(e){e.preventDefault();if(busy)return;setBusy(true);try{const editing=Boolean(form.id);await saveMasterCampaign(form);setForm(blank(businessContext));setFormOpen(false);await reload();setMessage(editing?'Communication modifiée.':'Communication enregistrée.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 function edit(c){setForm({...blank(businessContext),...c});setFormOpen(true);window.scrollTo({top:0,behavior:'smooth'});}
 async function remove(c){if(busy||!window.confirm(`Supprimer ou archiver « ${c.nom_campagne} »? Ses photos, rapports et historiques seront conservés.`))return;setBusy(true);try{const result=await deleteOrArchiveMasterCampaign(c.id);setMessage(result?.action==='archived'?'Les dépendances sont conservées et l’élément a été archivé.':'Élément supprimé.');await reload();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const title=businessContextLabel(businessContext);
 const createLabel=businessContext===BUSINESS_CONTEXT.MARKETING?'Créer une campagne':'Créer une communication';
 return <div className="campaigns-page"><header className="campaigns-hero"><div><h1>{businessContext===BUSINESS_CONTEXT.MARKETING?'Campagnes maîtres':'Communications opérationnelles'}</h1><p>Une seule source de vérité, classée par le champ « Est lié à ».</p></div>{canManage&&<button className="business-primary-action" type="button" onClick={()=>{setForm(blank(businessContext));setFormOpen(true)}}><Plus/> {createLabel}</button>}</header>{message&&<div className="relations-message" aria-live="polite">{message}</div>}<div className={formOpen?'campaigns-layout':'campaigns-layout campaigns-list-only'}>
 {canManage&&formOpen&&<section className="relations-card"><h2>{form.id?<Pencil/>:<Plus/>} {form.id?'Modifier':createLabel}</h2><form className="campaigns-form" onSubmit={submit}>
 <label>Nom<input required value={form.nom_campagne} onChange={e=>setForm({...form,nom_campagne:e.target.value})}/></label><label>Code<input value={form.code_campagne} onChange={e=>setForm({...form,code_campagne:e.target.value})}/></label><label>Client *<select required value={form.client_id||''} onChange={e=>{const selected=clients.find(item=>String(item.id)===e.target.value);setForm({...form,client_id:e.target.value,client:selected?.nom_client||''})}}><option value="">Choisir le client propriétaire</option>{clients.map(item=><option key={item.id} value={item.id}>{item.nom_client}</option>)}</select></label>
 <label>Est lié à<select value={form.business_context} onChange={e=>setForm({...form,business_context:e.target.value})}>{BUSINESS_CONTEXT_OPTIONS.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>
 <label>Type<select value={form.type_campagne} onChange={e=>setForm({...form,type_campagne:e.target.value})}><option>Installation</option><option>Remplacement</option><option>Retrait</option><option>Inspection</option></select></label><label>Date de début<input type="date" value={form.date_debut||''} onChange={e=>setForm({...form,date_debut:e.target.value})}/></label><label>Date de fin<input type="date" value={form.date_fin||''} onChange={e=>setForm({...form,date_fin:e.target.value})}/></label><label>Visuel générique<input value={form.visuel_generique} onChange={e=>setForm({...form,visuel_generique:e.target.value})}/></label><label>No EDT<input value={form.no_edt} onChange={e=>setForm({...form,no_edt:e.target.value})}/></label><label>Statut<select value={form.statut} onChange={e=>setForm({...form,statut:e.target.value})}><option>Brouillon</option><option>Active</option><option>Terminée</option><option>Archivée</option></select></label><label className="campaign-check"><input type="checkbox" checked={form.publiee_terrain} onChange={e=>setForm({...form,publiee_terrain:e.target.checked})}/> Visible dans l’application terrain</label><label>Instructions<textarea value={form.instructions_terrain} onChange={e=>setForm({...form,instructions_terrain:e.target.value})}/></label><div className="business-form-actions"><button className="relations-save" disabled={busy}><Save/> Enregistrer</button><button type="button" disabled={busy} onClick={()=>{setForm(blank(businessContext));setFormOpen(false)}}><X/> Annuler</button></div></form></section>}
 <section className="relations-card"><h2><Megaphone/> {title}</h2><div className="campaign-list">{campaigns.length?campaigns.map(c=><article key={c.id}><div><strong>{c.nom_campagne}</strong><span>Visuel : {c.visuel_generique||'—'}</span><small>Est lié à : {businessContextLabel(c.business_context)} — EDT : {c.no_edt||'—'} — {c.statut}</small></div><span className={c.publiee_terrain?'published':'draft'}>{c.publiee_terrain?<Eye size={15}/>:<EyeOff size={15}/>} {c.publiee_terrain?'Terrain':'Brouillon'}</span>{canManage&&<div><button disabled={busy} onClick={()=>edit(c)}><Pencil size={15}/> Modifier</button><button className="danger" disabled={busy} onClick={()=>remove(c)}><Trash2 size={15}/> Supprimer</button></div>}</article>):<p className="command-empty">Aucun élément dans cette classification.</p>}</div></section></div></div>;
}
