import React,{useEffect,useState}from'react';
import{Eye,EyeOff,Megaphone,Pencil,Plus,Save,Trash2,X}from'lucide-react';
import{deleteOrArchiveMasterCampaign,listMasterCampaigns,saveMasterCampaign}from'../services/campaignService';
import{BUSINESS_CONTEXT,BUSINESS_CONTEXT_OPTIONS,businessContextLabel}from'../lib/businessContext';

const blank=context=>({nom_campagne:'',code_campagne:'',client:'',type_campagne:'Installation',visuel_generique:'',no_edt:'',statut:'Brouillon',publiee_terrain:false,instructions_terrain:'',business_context:context});
export default function CampaignsPanel({role,businessContext=BUSINESS_CONTEXT.MARKETING}){
 const[campaigns,setCampaigns]=useState([]),[form,setForm]=useState(()=>blank(businessContext)),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const canManage=['Administrateur','Coordonnateur'].includes(role);
 async function reload(){try{setCampaigns(await listMasterCampaigns(false,businessContext));}catch(e){setMessage(e.message);}}
 useEffect(()=>{setForm(blank(businessContext));reload();},[businessContext]);
 async function submit(e){e.preventDefault();if(busy)return;setBusy(true);try{const editing=Boolean(form.id);await saveMasterCampaign(form);setForm(blank(businessContext));await reload();setMessage(editing?'Communication modifiée.':'Communication enregistrée.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 function edit(c){setForm({...blank(businessContext),...c});window.scrollTo({top:0,behavior:'smooth'});}
 async function remove(c){if(busy||!window.confirm(`Supprimer ou archiver « ${c.nom_campagne} »? Ses photos, rapports et historiques seront conservés.`))return;setBusy(true);try{const result=await deleteOrArchiveMasterCampaign(c.id);setMessage(result?.action==='archived'?'Les dépendances sont conservées et l’élément a été archivé.':'Élément supprimé.');await reload();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const title=businessContextLabel(businessContext);
 return <div className="campaigns-page"><header className="campaigns-hero"><div><h1>{businessContext===BUSINESS_CONTEXT.MARKETING?'Campagnes maîtres':'Communications opérationnelles'}</h1><p>Une seule source de vérité, classée par le champ « Est lié à ».</p></div></header>{message&&<div className="relations-message" aria-live="polite">{message}</div>}<div className="campaigns-layout">
 {canManage&&<section className="relations-card"><h2>{form.id?<Pencil/>:<Plus/>} {form.id?'Modifier':'Créer'}</h2><form className="campaigns-form" onSubmit={submit}>
 <label>Nom<input required value={form.nom_campagne} onChange={e=>setForm({...form,nom_campagne:e.target.value})}/></label><label>Code<input value={form.code_campagne} onChange={e=>setForm({...form,code_campagne:e.target.value})}/></label><label>Client<input value={form.client} onChange={e=>setForm({...form,client:e.target.value})}/></label>
 <label>Est lié à<select value={form.business_context} onChange={e=>setForm({...form,business_context:e.target.value})}>{BUSINESS_CONTEXT_OPTIONS.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>
 <label>Type<select value={form.type_campagne} onChange={e=>setForm({...form,type_campagne:e.target.value})}><option>Installation</option><option>Remplacement</option><option>Retrait</option><option>Inspection</option></select></label><label>Visuel générique<input value={form.visuel_generique} onChange={e=>setForm({...form,visuel_generique:e.target.value})}/></label><label>No EDT<input value={form.no_edt} onChange={e=>setForm({...form,no_edt:e.target.value})}/></label><label>Statut<select value={form.statut} onChange={e=>setForm({...form,statut:e.target.value})}><option>Brouillon</option><option>Active</option><option>Terminée</option><option>Archivée</option></select></label><label className="campaign-check"><input type="checkbox" checked={form.publiee_terrain} onChange={e=>setForm({...form,publiee_terrain:e.target.checked})}/> Visible dans l’application terrain</label><label>Instructions<textarea value={form.instructions_terrain} onChange={e=>setForm({...form,instructions_terrain:e.target.value})}/></label><button className="relations-save" disabled={busy}><Save/> Enregistrer</button>{form.id&&<button type="button" disabled={busy} onClick={()=>setForm(blank(businessContext))}><X/> Annuler</button>}</form></section>}
 <section className="relations-card"><h2><Megaphone/> {title}</h2><div className="campaign-list">{campaigns.length?campaigns.map(c=><article key={c.id}><div><strong>{c.nom_campagne}</strong><span>Visuel : {c.visuel_generique||'—'}</span><small>Est lié à : {businessContextLabel(c.business_context)} — EDT : {c.no_edt||'—'} — {c.statut}</small></div><span className={c.publiee_terrain?'published':'draft'}>{c.publiee_terrain?<Eye size={15}/>:<EyeOff size={15}/>} {c.publiee_terrain?'Terrain':'Brouillon'}</span>{canManage&&<div><button disabled={busy} onClick={()=>edit(c)}><Pencil size={15}/> Modifier</button><button className="danger" disabled={busy} onClick={()=>remove(c)}><Trash2 size={15}/> Supprimer</button></div>}</article>):<p className="command-empty">Aucun élément dans cette classification.</p>}</div></section></div></div>;
}
