import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,BarChart3,Download,LogOut,Menu,X}from'lucide-react';
import BrandLogo from'./BrandLogo';
import ClientBusinessGrid from'./ClientBusinessGrid';
import ExportsCenter from'./ExportsCenter';
import InteractiveMap from'./InteractiveMap';
import BulkSupportSelector from'./BulkSupportSelector';
import{selectedSiteCount}from'../lib/bulkSupportSelection';
import{resolveClientPortalViews,isAllowedClientPortalView}from'../lib/clientPortalViewRegistry';
import{getClientPortalIdentity,getCurrentUserVisibleViews}from'../services/clientAccessService';
import{createMultiSupportClientRequest,listAllClientPortalSection,listClientPortalSection}from'../services/clientPortalService';
import{prepareMapInfrastructureRows}from'../services/mapService';

// Les miniatures de la grille partagée restent chargées avec loading="lazy".

function ClientRequestForm({supports,onCreated}){const[selected,setSelected]=useState(new Set()),[form,setForm]=useState({type:'Installation',priority:'Normale',description:''}),[confirming,setConfirming]=useState(false),[busy,setBusy]=useState(false),sites=selectedSiteCount(supports,selected);async function submit(){setBusy(true);try{await createMultiSupportClientRequest({type:form.type,priority:form.priority,description:form.description,supportIds:[...selected]});setSelected(new Set());setConfirming(false);onCreated('Requête créée et supports validés par le serveur.')}finally{setBusy(false)}}return <div className="client-request-form"><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Installation</option><option>Retrait</option><option>Inspection</option><option>Réparation</option></select></label><label>Priorité<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Basse</option><option>Normale</option><option>Haute</option><option>Urgente</option></select></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><BulkSupportSelector rows={supports} selected={selected} onChange={setSelected}/>{confirming?<section className="client-request-summary"><h2>Confirmer la requête</h2><strong>Supports : {selected.size}</strong><span>Sites : {sites}</span><button type="button" onClick={()=>setConfirming(false)}>Modifier la sélection</button><button type="button" disabled={busy} onClick={submit}>Soumettre la requête</button></section>:<button type="button" disabled={!selected.size} onClick={()=>setConfirming(true)}>Vérifier avant soumission</button>}</div>}

function ClientDashboard({identity,views,sections,onNavigate}){return <div className="dashboard executive-dashboard module14 client-dashboard" data-reference-component="Module14Dashboard"><header className="executive-hero"><div className="hero-brand"><BrandLogo priority/><div><h1>Tableau de bord</h1></div></div><div className="executive-status"><span className="status-dot"/> Données sécurisées · {identity?.client_name||'Mon organisation'}</div></header><section className="executive-kpis">{views.filter(view=>view.id!=='requests'&&view.id!=='members').map(view=>{const Icon=view.icon,section=sections[view.section]||{};return <button key={view.id} className="executive-kpi" onClick={()=>onNavigate(view.id)}><span><Icon/>{view.label}</span><strong>{Number(section.total||0).toLocaleString('fr-CA')}</strong><small>Ouvrir le module</small></button>})}</section>{!views.length&&<div className="client-empty">Aucune vue n’est actuellement autorisée pour votre profil.</div>}</div>}

export default function ClientPortal({profile={},onLogout,preview=null,onClose}){
 const previewMode=Boolean(preview),previewUser=preview?.target_user||preview?.user||preview,previewSections=preview?.sections||{};
 const[active,setActive]=useState('dashboard'),[identity,setIdentity]=useState(previewUser||null),[permission,setPermission]=useState(preview?{visible_tables:preview.visible_tables||previewUser?.visible_tables||[]}:null),[sections,setSections]=useState(previewSections),[result,setResult]=useState({rows:[],total:0,page:1,page_size:25}),[loading,setLoading]=useState(!preview),[error,setError]=useState(''),[menu,setMenu]=useState(false),[mapRows,setMapRows]=useState(null);
 const resolved=useMemo(()=>resolveClientPortalViews(permission?.visible_tables),[permission]),available=resolved.views,currentView=available.find(view=>view.id===active);
 useEffect(()=>{if(preview)return;let live=true;(async()=>{setLoading(true);try{const[id,views]=await Promise.all([getClientPortalIdentity(),getCurrentUserVisibleViews()]);if(!live)return;setIdentity(id);setPermission(views);const allowed=resolveClientPortalViews(views.visible_tables).views,loaded=await Promise.all(allowed.filter(view=>view.id!=='requests').map(async view=>[view.section,await listClientPortalSection(view.section,{page:1,pageSize:25})]));if(live)setSections(Object.fromEntries(loaded))}catch(e){if(live)setError(e.message||'Portail client indisponible.')}finally{if(live)setLoading(false)}})();return()=>{live=false}},[previewMode]);
 async function load(view=currentView,page=1,pageSize=25,filters={}){if(!view)return;if(previewMode){setResult(previewSections[view.section]||{rows:[],total:0,page:1,page_size:25});return}setLoading(true);setError('');try{const next=view.id==='requests'?{rows:await listAllClientPortalSection('supports'),page:1,page_size:25,total:0}:await listClientPortalSection(view.section,{page,pageSize,filters});setResult(next);setSections(current=>({...current,[view.section]:next}))}catch(e){setError(e.message||'Données client indisponibles.')}finally{setLoading(false)}}
 useEffect(()=>{if(currentView)load(currentView,1,25)},[currentView?.id]);
 const navigate=id=>{if(!['dashboard','exports'].includes(id)&&!isAllowedClientPortalView(available,id)){setError('Accès refusé.');return}if(id==='exports'&&!available.some(view=>!['requests','members'].includes(view.id))){setError('Aucun export autorisé.');return}setActive(id);setMapRows(null);setMenu(false)};
 async function openMap(){setLoading(true);try{setMapRows(previewMode?(previewSections.supports?.rows||[]):await listAllClientPortalSection('supports'))}catch(e){setError(e.message)}finally{setLoading(false)}}
 const loadAll=filters=>previewMode?Promise.resolve(previewSections[currentView.section]?.rows||[]):listAllClientPortalSection(currentView.section,{filters});
 let content;if(active==='dashboard')content=<ClientDashboard identity={identity} views={available} sections={sections} onNavigate={navigate}/>;else if(active==='exports'){const domains=available.filter(view=>!['requests','members'].includes(view.id)).map(view=>({id:view.id,label:view.label,section:view.section}));content=<ExportsCenter title="Exports" domains={domains} loadRows={domain=>previewMode?Promise.resolve(previewSections[domain.section]?.rows||[]):listAllClientPortalSection(domain.section)}/>;}else if(mapRows)content=<><button className="client-back" onClick={()=>setMapRows(null)}><ArrowLeft/> Tableau</button><p>{prepareMapInfrastructureRows(mapRows).points.length.toLocaleString('fr-CA')} infrastructure(s) cartographiable(s) sur {mapRows.length.toLocaleString('fr-CA')} autorisée(s).</p><InteractiveMap dataStore={{Infrastructures:{rows:mapRows}}} role={identity?.role||profile.role}/></>;else if(currentView?.id==='requests')content=<ClientRequestForm supports={result.rows||[]} onCreated={setError}/>;else if(currentView)content=<ClientBusinessGrid view={currentView} result={result} onLoad={(page,size,filters)=>load(currentView,page,size,filters)} onLoadAll={loadAll} onOpenMap={openMap}/>;else content=<div className="client-empty">Aucune vue n’est actuellement autorisée.</div>;
 return <div className={`client-portal${previewMode?' client-preview-mode':''}`}>{previewMode&&<div className="ca-preview-banner"><strong>APERÇU ADMINISTRATEUR — Vue simulée pour {identity?.nom||identity?.name||identity?.courriel}</strong><span>L’Admin reste connecté comme Administrateur.</span><button onClick={onClose}>Quitter l’aperçu</button></div>}<header><div className="client-brand"><BrandLogo priority/><span>Display Manager</span></div><button className="client-menu-button" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}<span>Menu</span></button><div className="client-profile"><span>{identity?.name||identity?.nom||profile.nom||profile.courriel}</span><small>{identity?.role||profile.role}</small>{!previewMode&&<button onClick={onLogout}><LogOut/> Déconnexion</button>}</div></header><div className="client-body"><aside className={menu?'open':''}><button className={active==='dashboard'?'active':''} onClick={()=>navigate('dashboard')}><BarChart3/>Sommaire</button>{available.some(view=>!['requests','members'].includes(view.id))&&<button className={active==='exports'?'active':''} onClick={()=>navigate('exports')}><Download/>Exports</button>}{available.map(view=>{const Icon=view.icon;return <button key={view.id} className={active===view.id?'active':''} onClick={()=>navigate(view.id)}><Icon/>{view.label}</button>})}</aside><main>{!['dashboard','exports'].includes(active)&&<div className="client-title"><div><span>{identity?.client_name||'Mon organisation'}</span><h1>{currentView?.label}</h1></div><span>{result.total||0} résultat(s)</span></div>}{resolved.unknown.length>0&&<div className="client-notice" role="alert">Configuration portail invalide : vue non implémentée.</div>}{error&&<div className="client-notice" role="alert">{error}</div>}{loading?<div className="client-loading">Chargement sécurisé…</div>:content}</main></div></div>;
}
