import React,{useEffect,useMemo,useState}from'react';
import{Building2,CalendarClock,Camera,Download,FileText,History,Home,Image,LogOut,Menu,ShieldCheck,Users,X}from'lucide-react';
import BrandLogo from'./BrandLogo';
import GridPagination from'./GridPagination';
import{getClientPortalIdentity,isClientAdmin}from'../services/clientAccessService';
import{deactivateClientMember,inviteClientMember,listClientPortalSection}from'../services/clientPortalService';

const sections=[['dashboard','Accueil',Home],['campaigns','Campagnes',Image],['communications','Communications opérationnelles',ShieldCheck],['supports','Sites et supports',Building2],['photos','Photos',Camera],['reports','Rapports',FileText],['edt','EDT / Progression',CalendarClock],['issues','Enjeux',ShieldCheck],['history','Historique',History],['members','Mon organisation',Users]];
const labels={nom_campagne:'Campagne / communication',business_context:'Contexte',date_debut:'Début',date_fin:'Fin',statut:'Statut',site:'Site',support_id:'Support',type_support:'Type',emplacement_visibilite:'Infrastructure',visual:'Visuel',numero_edt:'EDT',objet:'Rapport',sent_at:'Publié le',type_enjeu:'Enjeu',description:'Description',occurred_at:'Date',action:'Activité',nom:'Nom',courriel:'Courriel',role:'Rôle'};
const hidden=new Set(['id','campaign_id','campagne_id','visuel_id','organization_id','report_path','photo_url','thumbnail_url']);
const display=v=>v===null||v===undefined||v===''?'—':String(v);

function Dashboard({identity,onOpen}){const cards=[['Campagnes','campaigns'],['Communications','communications'],['Supports','supports'],['Photos récentes','photos'],['Rapports','reports'],['EDT','edt'],['Enjeux visibles','issues'],['Activité récente','history']];return <><section className="client-welcome"><span>Espace sécurisé</span><h1>Bonjour {identity.name||''}</h1><p>Suivez vos campagnes, vos installations et vos livrables au même endroit.</p></section><section className="client-summary">{cards.map(([label,id])=><button key={id} onClick={()=>onOpen(id)}><strong>{label}</strong><span>Consulter</span></button>)}</section></>}
function PhotoGallery({rows}){return <div className="client-gallery">{rows.map(row=><article key={row.id}><button onClick={()=>row.signed_url&&window.open(row.signed_url,'_blank','noopener,noreferrer')} aria-label={`Ouvrir ${row.nom_fichier}`}>{row.signed_thumbnail_url?<img loading="lazy" src={row.signed_thumbnail_url} alt={row.nom_fichier||'Photo de support'}/>:<span>Photo indisponible</span>}</button><div><strong>{row.support_id}</strong><span>{row.type_photo||'Photo'}</span><small>{display(row.prise_le)}</small>{row.signed_url&&<a href={row.signed_url} target="_blank" rel="noreferrer"><Download/> Télécharger</a>}</div></article>)}</div>}
function DataTable({rows,section,onDeactivate}){if(!rows.length)return <div className="client-empty">Aucune donnée autorisée disponible.</div>;const columns=[...new Set(rows.flatMap(Object.keys))].filter(key=>!hidden.has(key)).slice(0,7);return <div className="client-table-wrap"><table><thead><tr>{columns.map(key=><th key={key}>{labels[key]||key.replaceAll('_',' ')}</th>)}{section==='members'&&<th>Actions</th>}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id??index}>{columns.map(key=><td key={key}>{display(row[key])}</td>)}{section==='members'&&<td>{row.role==='Client'&&row.statut!=='Inactif'?<button className="client-danger" onClick={()=>onDeactivate(row.id)}>Désactiver</button>:'—'}</td>}</tr>)}</tbody></table></div>}
function MemberInvite({onInvite}){const[email,setEmail]=useState(''),[name,setName]=useState('');return <form className="client-invite" onSubmit={async e=>{e.preventDefault();await onInvite({email,name});setEmail('');setName('')}}><h2>Inviter un membre Client</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nom"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Courriel"/><button type="submit">Préparer l’invitation</button><small>L’invitation est traitée côté serveur; aucun rôle interne ne peut être créé ici.</small></form>}

export default function ClientPortal({profile,onLogout}){
 const[active,setActive]=useState('dashboard'),[identity,setIdentity]=useState(null),[result,setResult]=useState({rows:[],total:0,page:1,page_size:25}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[menu,setMenu]=useState(false);
 const admin=isClientAdmin(profile.role),available=useMemo(()=>sections.filter(([id])=>id!=='members'||admin),[admin]);
 async function load(section=active,page=1,pageSize=result.page_size||25){setLoading(true);setError('');try{if(!identity)setIdentity(await getClientPortalIdentity());if(section==='dashboard'){setResult({rows:[],total:0,page:1,page_size:25});return}setResult(await listClientPortalSection(section,{page,pageSize}));}catch(e){setError(e.message||'Données client indisponibles.')}finally{setLoading(false)}}
 useEffect(()=>{load(active,1)},[active]);
 const navigate=id=>{setActive(id);setMenu(false)};
 async function invite(values){try{await inviteClientMember(values);await load('members',1);setError('Invitation sécurisée préparée.')}catch(e){setError(e.message)}}
 async function deactivate(id){try{await deactivateClientMember(id);await load('members',result.page)}catch(e){setError(e.message)}}
 const current=available.find(([id])=>id===active)?.[1]||'Accueil';
 return <div className="client-portal"><header><div className="client-brand"><BrandLogo priority/><span>Portail client</span></div><button className="client-menu-button" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}<span>Menu</span></button><div className="client-profile"><span>{identity?.name||profile.nom||profile.courriel}</span><small>{profile.role}</small><button onClick={onLogout}><LogOut/> Déconnexion</button></div></header><div className="client-body"><aside className={menu?'open':''}>{available.map(([id,label,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>navigate(id)}><Icon/>{label}</button>)}</aside><main><div className="client-title"><div><span>Mon organisation</span><h1>{current}</h1></div>{active!=='dashboard'&&<span>{result.total||0} résultat(s)</span>}</div>{error&&<div className="client-notice" role="alert">{error}</div>}{loading?<div className="client-loading">Chargement sécurisé…</div>:active==='dashboard'?<Dashboard identity={identity||profile} onOpen={navigate}/>:<>{active==='members'&&admin&&<MemberInvite onInvite={invite}/>} {active==='photos'?<PhotoGallery rows={result.rows||[]}/>:<DataTable rows={result.rows||[]} section={active} onDeactivate={deactivate}/>}<GridPagination currentPage={result.page||1} totalRows={result.total||0} pageSize={result.page_size||25} onPageChange={page=>load(active,page)} onPageSizeChange={size=>load(active,1,size)}/></>}</main></div></div>;
}
