import React,{useEffect,useMemo,useState}from'react';
import{Eye,Pencil,Plus,RefreshCw,X}from'lucide-react';
import{changeClientUserRole,createClient,getClientAccessDetail,inviteClientUser,linkUserToClient,listClientAccessOverview,searchClientUsers,transferUserClient,unlinkUserFromClient,updateClient}from'../services/clientAccessAdminService';
import'../features/clients/clients-access-admin-v135.css';

const blank={nom_client:'',type_client:'',statut:'Actif',notes:'',courriels_rapport:'',courriels_cc:'',logo_url:'',couleur_rapport:'#2563eb',mention_legale:''};
const dt=value=>value?new Date(value).toLocaleString('fr-CA'):'Jamais';
function ClientForm({value,busy,onClose,onSave}){const[form,setForm]=useState(value),set=(key,value)=>setForm({...form,[key]:value});return <div className="ca-modal"><form className="ca-dialog ca-form" onSubmit={e=>{e.preventDefault();onSave(form)}}><button type="button" className="ca-close" onClick={onClose}><X/></button><h2>{value.client_id?'Modifier le client':'Ajouter un client'}</h2><label>Nom<input required value={form.nom_client||''} onChange={e=>set('nom_client',e.target.value)}/></label><label>Type<input value={form.type_client||''} onChange={e=>set('type_client',e.target.value)}/></label><label>Statut<select value={form.statut||'Actif'} onChange={e=>set('statut',e.target.value)}><option>Actif</option><option>Désactivé</option></select></label>{[['notes','Notes'],['courriels_rapport','Courriels rapport'],['courriels_cc','CC'],['logo_url','Logo'],['couleur_rapport','Couleur rapport'],['mention_legale','Mention légale']].map(([key,label])=><label key={key}>{label}<input value={form[key]||''} onChange={e=>set(key,e.target.value)}/></label>)}<button disabled={busy}>Enregistrer</button></form></div>}
function InviteForm({onInvite}){const[form,setForm]=useState({nom:'',courriel:'',role:'Client'});return <form className="ca-invite" onSubmit={e=>{e.preventDefault();onInvite(form)}}><h3>Inviter un utilisateur</h3><input required placeholder="Nom" value={form.nom} onChange={e=>setForm({...form,nom:e.target.value})}/><input required type="email" placeholder="Courriel" value={form.courriel} onChange={e=>setForm({...form,courriel:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>Client</option><option>Client-Admin</option></select><button>Inviter</button></form>}
function LinkForm({client,onLink}){const[query,setQuery]=useState(''),[users,setUsers]=useState([]),[role,setRole]=useState('Client');async function search(){setUsers(await searchClientUsers(query))}return <section><h3>Rattacher un utilisateur</h3><div className="ca-invite"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom ou courriel"/><button type="button" onClick={search}>Rechercher</button><select value={role} onChange={e=>setRole(e.target.value)}><option>Client</option><option>Client-Admin</option></select></div>{users.map(user=><article key={user.id}><strong>{user.nom} — {user.courriel}</strong><span>{user.role||'Sans rôle'} · {user.client_name||'Aucun client'} · {user.statut}</span><small>Auth : {user.auth_user_id?'oui':'non'}</small><button onClick={()=>onLink({userId:user.id,clientId:client.client_id,role})}>Rattacher</button></article>)}</section>}
function Access({client,clients,data,busy,onClose,onRefresh,onMessage}){
 async function mutate(action,success){try{await action();await onRefresh();onMessage(success)}catch(error){onMessage(error.message,true)}}
 return <div className="ca-modal"><section className="ca-dialog"><button className="ca-close" onClick={onClose}><X/></button><h2>Voir les accès — {client.nom_client}</h2>{busy&&<p>Chargement…</p>}{data&&<><section><h3>MEMBRES</h3>{(data.members||[]).map(member=><article key={member.id}><strong>{member.nom} — {member.courriel}</strong><span>{member.role} · {member.statut} · {member.client_name||client.nom_client}</span><small>{member.auth_user_id?'Compte activé':'Compte non activé'} · Dernière activité : {dt(member.derniere_activite_le)} · Vues : {(member.visible_views||[]).join(', ')||'Aucune'}</small><div className="ca-invite"><button onClick={()=>mutate(()=>changeClientUserRole({userId:member.id,role:member.role==='Client'?'Client-Admin':'Client'}),'Rôle modifié.')}>Modifier le rôle</button><button onClick={()=>window.confirm('Détacher cet utilisateur sans supprimer son compte Auth ?')&&mutate(()=>unlinkUserFromClient(member.id),'Utilisateur détaché.')}>Détacher</button><select defaultValue="" onChange={e=>{const target=e.target.value;if(target&&window.confirm('Transférer cet utilisateur et réévaluer ses accès campagne ?'))mutate(()=>transferUserClient({userId:member.id,clientId:+target,role:member.role}),'Utilisateur transféré.')}}><option value="">Transférer vers…</option>{clients.filter(item=>item.client_id!==client.client_id).map(item=><option key={item.client_id} value={item.client_id}>{item.nom_client}</option>)}</select></div></article>)}</section><section><h3>INVITATIONS</h3>{(data.invitations||[]).map((item,index)=><article key={item.id||index}><strong>{item.email}</strong><span>{item.requested_role} · {item.status}</span></article>)}</section><section><h3>CAMPAGNES</h3>{(data.campaigns||[]).map(item=><article key={item.id}><strong>{item.nom_campagne}</strong><span>{item.access_mode}</span></article>)}</section><InviteForm onInvite={form=>mutate(()=>inviteClientUser(client,form),`Invitation ${form.role} envoyée.`)}/><LinkForm client={client} onLink={values=>mutate(()=>linkUserToClient(values),'Utilisateur rattaché.')}/></>}</section></div>
}
export default function ClientsAccessAdmin({role}){
 const[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[form,setForm]=useState(null),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[filters,setFilters]=useState({status:'',portal:'',admin:'',pending:''}),[sort,setSort]=useState('nom_client');const admin=role==='Administrateur';
 async function load(){setBusy(true);try{setRows(await listClientAccessOverview());setMessage('')}catch(error){setMessage(error.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 const shown=useMemo(()=>rows.filter(row=>(!filters.status||row.statut_client===filters.status)&&(!filters.portal||row.portal_access_status===filters.portal)&&(!filters.admin||(filters.admin==='yes'?+row.client_admin_count>0:+row.client_admin_count===0))&&(!filters.pending||(filters.pending==='yes'?+row.pending_invitation_count>0:+row.pending_invitation_count===0))).sort((a,b)=>String(a[sort]??'').localeCompare(String(b[sort]??''),undefined,{numeric:true})),[rows,filters,sort]);
 async function open(row){setSelected(row);setBusy(true);try{setDetail(await getClientAccessDetail(row.client_id))}catch(error){setMessage(error.message)}finally{setBusy(false)}}
 async function refreshDetail(){if(selected)setDetail(await getClientAccessDetail(selected.client_id));await load()}
 async function save(value){setBusy(true);try{value.client_id?await updateClient(value.client_id,value):await createClient(value);setForm(null);await load();setMessage('Client enregistré sans rechargement.')}catch(error){setMessage(error.message);setBusy(false)}}
 if(!['Administrateur','Coordonnateur'].includes(role))return <div className="admin-page"><h1>Accès réservé</h1></div>;
 const cols=[['nom_client','Nom client'],['type_client','Type'],['statut_client','Statut'],['portal_access_status','Accès portail'],['client_admins','Client-Admin'],['active_member_count','Membres actifs'],['pending_invitation_count','Invitations en attente'],['accessible_campaign_count','Campagnes autorisées'],['latest_activity_at','Dernière activité']];
 return <div className="ca-page"><header><div><h1>Clients et accès portail</h1><p>Vue réelle des organisations et de leurs accès.</p></div><div>{admin&&<button onClick={()=>setForm(blank)}><Plus/> Ajouter un client</button>}<button onClick={load}><RefreshCw/>Actualiser</button></div></header>{message&&<p className="ca-message">{message}</p>}<nav className="ca-filters"><select onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Tous statuts</option><option>Actif</option><option>Désactivé</option></select><select onChange={e=>setFilters({...filters,portal:e.target.value})}><option value="">Tous accès portail</option>{['ACTIF','INVITATION EN ATTENTE','À ACTIVER','INCOMPLET'].map(value=><option key={value}>{value}</option>)}</select></nav><div className="ca-table"><table><thead><tr>{cols.map(([key,label])=><th key={key}><button onClick={()=>setSort(key)}>{label}</button></th>)}<th>Actions</th></tr></thead><tbody>{shown.map(row=><tr key={row.client_id}>{cols.map(([key,label])=><td key={key} data-label={label}>{key==='latest_activity_at'?dt(row[key]):row[key]||'—'}</td>)}<td><button onClick={()=>open(row)}><Eye/>Voir les accès</button>{admin&&<button onClick={()=>setForm(row)}><Pencil/>Modifier</button>}</td></tr>)}</tbody></table></div>{form&&<ClientForm value={form} busy={busy} onClose={()=>setForm(null)} onSave={save}/>} {selected&&<Access client={selected} clients={rows} data={detail} busy={busy} onClose={()=>setSelected(null)} onRefresh={refreshDetail} onMessage={(value,error)=>setMessage(error?`Erreur : ${value}`:value)}/>}</div>
}
