import React,{useEffect,useRef,useState} from 'react';
import {getPhotoInventoryCapabilities,listDisplayMovements,readDisplayCurrentState,cancelDisplayMovement} from '../services/displayMovementService';
import PhotoImage from './PhotoImage';
export default function DisplayMovementInventory({supportId='',edtNumber='',onClearEdt}) {
 const [rows,setRows]=useState([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[sort,setSort]=useState('recent'),[cancelled,setCancelled]=useState(false),[capabilities,setCapabilities]=useState({cancel:false,author:false}),[error,setError]=useState(''),[loading,setLoading]=useState(false),[pending,setPending]=useState(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[photos,setPhotos]=useState(null),[current,setCurrent]=useState(null);
 const request=useRef(0),cancelActive=useRef(false);
 async function load(){const id=++request.current;setLoading(true);try{const data=await listDisplayMovements({support:supportId,edt:edtNumber,search:query,sort,cancelled,offset:page*50});if(id!==request.current)return;setRows(data.rows);setTotal(data.total);setError('');}catch(e){if(id===request.current)setError(e.message);}finally{if(id===request.current)setLoading(false);}}
 useEffect(()=>{getPhotoInventoryCapabilities().then(setCapabilities).catch(e=>setError(e.message));},[]);
 useEffect(()=>{load();return()=>{request.current++;};},[supportId,edtNumber,page,query,sort,cancelled]);
 useEffect(()=>setPage(0),[supportId,edtNumber]);
 async function cancel(){if(cancelActive.current||!pending)return;cancelActive.current=true;setBusy(true);try{await cancelDisplayMovement(pending,reason);setPending(null);setCurrent(null);await load();window.dispatchEvent(new Event('tos-terrain-data-updated'));}catch(e){setError(e.message);}finally{cancelActive.current=false;setBusy(false);}}
 async function showState(support){try{setCurrent({support,state:await readDisplayCurrentState(support)});}catch(e){setError(e.message);}}
 return <section aria-label="Mouvements d’affiches"><h3>Mouvements d’affiches</h3><p>Installations et retraits provenant de l’historique canonique.</p>
  {edtNumber&&<p>EDT : <strong>{edtNumber}</strong> <button onClick={onClearEdt}>Tous les EDT</button></p>}
  <form className="review-toolbar" onSubmit={e=>{e.preventDefault();setPage(0);setQuery(search);}}><label>Support, EDT, campagne, visuel ou date<input aria-label="Rechercher un mouvement" value={search} onChange={e=>setSearch(e.target.value)}/></label><button>Rechercher</button><label>Tri<select aria-label="Trier les mouvements" value={sort} onChange={e=>{setPage(0);setSort(e.target.value);}}><option value="recent">Plus récents</option><option value="oldest">Plus anciens</option><option value="support">Support</option></select></label>{capabilities.author&&<label><input type="checkbox" checked={cancelled} onChange={e=>{setPage(0);setCancelled(e.target.checked);}}/> Inclure les mouvements annulés</label>}</form>
  {error&&<p role="alert">{error}</p>}{loading&&<p role="status">Chargement des mouvements…</p>}
  <p>{total} mouvement(s)</p>
  <div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Support</th><th>EDT</th><th>Campagne / communication</th><th>Visuel</th><th>Photos</th><th>Client</th><th>Source</th><th>Statut</th>{capabilities.author&&<th>Auteur</th>}<th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>
   <td>{new Date(row.event_at).toLocaleString('fr-CA')}</td><td>{row.movement_kind==='installation'?'Installation':'Retrait'}</td><td>{row.support_id}</td><td>{row.edt_number||'Sans EDT'}</td><td>{row.campaign||'—'}</td><td>{row.visual||'—'}</td><td><button disabled={!row.photos?.length} onClick={()=>setPhotos(row.photos)}>{row.photos?.length||0} photo(s)</button></td><td>{row.client_id}</td><td>{row.source}</td><td>{row.status==='CANCELLED'?'Annulé':'Valide'}</td>{capabilities.author&&<td>{row.author||'—'}</td>}<td><button onClick={()=>showState(row.support_id)}>État courant</button>{capabilities.cancel&&row.status!=='CANCELLED'&&<button onClick={()=>{setPending(row);setReason('');}}>Supprimer le mouvement</button>}</td>
  </tr>)}</tbody></table></div>
  {!loading&&!rows.length&&<p>Aucun mouvement pour ces critères.</p>}
  <div className="review-toolbar"><button disabled={page===0||loading} onClick={()=>setPage(p=>p-1)}>Précédent</button><span>{page+1} / {Math.max(1,Math.ceil(total/50))}</span><button disabled={(page+1)*50>=total||loading} onClick={()=>setPage(p=>p+1)}>Suivant</button></div>
  {current&&<section aria-label="État courant du support"><h4>{current.support} — État courant</h4><dl><dt>Campagne</dt><dd>{current.state.campagne_actuelle||'Aucune installation courante'}</dd><dt>Visuel</dt><dd>{current.state.visuel_campagne||'—'}</dd><dt>EDT</dt><dd>{current.state.edt_associe||'—'}</dd><dt>Dernière intervention</dt><dd>{current.state.date_derniere_manipulation||'—'}</dd></dl><button onClick={()=>setCurrent(null)}>Fermer l’état courant</button></section>}
  {pending&&<div className="movement-confirmation" role="dialog" aria-modal="true" aria-label="Confirmer la suppression du mouvement"><h3>Supprimer le mouvement</h3><p>{pending.movement_kind==='installation'?'Installation':'Retrait'} — {new Date(pending.event_at).toLocaleString('fr-CA')}</p><p>Support : {pending.support_id} · EDT : {pending.edt_number||'Sans EDT'} · Visuel : {pending.visual||'—'}</p><p>L’état courant sera recalculé. Les photos et l’audit seront conservés.</p><label>Motif (facultatif)<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy} onClick={()=>setPending(null)}>Annuler</button><button disabled={busy} onClick={cancel}>Confirmer la suppression</button></div>}
  {photos&&<div className="review-viewer" role="dialog" aria-modal="true" aria-label="Photos du mouvement"><button onClick={()=>setPhotos(null)}>Fermer</button>{photos.map(photo=><figure key={photo.id}><PhotoImage photo={photo} alt={photo.nom_fichier} loading="lazy"/><figcaption>{photo.nom_fichier}</figcaption></figure>)}</div>}
 </section>;
}
