import React,{useMemo,useState}from'react';
import{Archive,Download,FileSpreadsheet,FileText}from'lucide-react';
import{downloadCSV,downloadExcel,downloadPDF,professionalExportName}from'../lib/utils';
import{getSignedDownloadUrl}from'../services/photoAccessService';

const hidden=/^(id|client_id|organization_id)$|(_id$)|storage|bucket|auth_|raw_data/i;
const clean=value=>String(value||'Sans classement').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9._-]+/gi,'_').replace(/^_+|_+$/g,'')||'Sans_classement';
const photoUrl=row=>row.signed_url||row.signed_thumbnail_url||row.photo_url||row.thumbnail_url||'';
const dateValue=row=>row.prise_le||row.captured_at||row.uploaded_at||row.created_at||'';

export default function ExportsCenter({domains=[],loadRows,title='Exports'}){
 const[busy,setBusy]=useState(''),[message,setMessage]=useState('');
 const[photoFilters,setPhotoFilters]=useState({support:'',campaign:'',edt:'',status:'',from:'',to:'',activeOnly:false});
 const photos=useMemo(()=>domains.find(domain=>domain.id==='photos'),[domains]);
 async function exportDomain(domain,format){const token=`${domain.id}:${format}`;setBusy(token);setMessage('');try{const rows=await loadRows(domain);const columns=[...new Set(rows.flatMap(Object.keys))].filter(key=>!hidden.test(key));const labels=Object.fromEntries(columns.map(key=>[key,key.replaceAll('_',' ')]));const options={moduleName:domain.label,labels,exportType:'Export complet autorisé'};if(format==='csv')downloadCSV(professionalExportName(domain.label,'csv'),rows,columns.map(key=>({key,label:labels[key]})));if(format==='xlsx')await downloadExcel(professionalExportName(domain.label,'xlsx'),rows,columns,options);if(format==='pdf')await downloadPDF(professionalExportName(domain.label,'pdf'),domain.label,rows,columns,options);setMessage(`${rows.length} ligne(s) autorisée(s) exportée(s).`)}catch(error){setMessage(error.message||'Export impossible.')}finally{setBusy('')}}
 async function exportPhotos(){setBusy('photos:zip');setMessage('');try{const JSZip=(await import('jszip')).default;const rows=(await loadRows(photos)).filter(row=>{const day=String(dateValue(row)).slice(0,10);return(!photoFilters.support||String(row.support_id||row.infrastructure||'').toLowerCase().includes(photoFilters.support.toLowerCase()))&&(!photoFilters.campaign||String(row.campagne_id||row.campaign_id||row.nom_campagne||'').toLowerCase().includes(photoFilters.campaign.toLowerCase()))&&(!photoFilters.edt||String(row.edt_id||row.no_edt||row.numero_edt||'').toLowerCase().includes(photoFilters.edt.toLowerCase()))&&(!photoFilters.status||String(row.statut||row.status||row.statut_validation||'').toLowerCase().includes(photoFilters.status.toLowerCase()))&&(!photoFilters.from||day>=photoFilters.from)&&(!photoFilters.to||day<=photoFilters.to)&&(!photoFilters.activeOnly||row.est_principale===true||row.is_current_visual===true||row.is_active===true)});const zip=new JSZip();let added=0,failed=0;for(const row of rows){try{let url=photoUrl(row);if(row.storage_path)url=await getSignedDownloadUrl(row);if(!url)throw new Error('URL absente');const response=await fetch(url,{credentials:'omit'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const extension=(row.nom_fichier||row.storage_path||url).match(/\.(jpe?g|png|webp|gif)(?:$|\?)/i)?.[1]||'jpg';const path=[clean(row.client_name||row.client||'Client'),clean(row.nom_campagne||row.campagne_id||row.campaign_id||'Sans_campagne'),clean(row.support_id||row.infrastructure||'Sans_support'),clean(row.nom_fichier||`Photo_${row.id||added+1}.${extension}`)].join('/');zip.file(path,await response.blob());added+=1}catch{failed+=1}}const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=professionalExportName('Photos_autorisees','zip');link.click();URL.revokeObjectURL(url);setMessage(`${added} photo(s) exportée(s)${failed?`, ${failed} inaccessible(s) ignorée(s)`:''}.`)}catch(error){setMessage(error.message||'Export photo impossible.')}finally{setBusy('')}}
 return <div className="tablePage exports-center"><header className="pageHead"><div><h1>{title}</h1><p>Exports produits uniquement à partir des domaines et lignes autorisés.</p></div></header>{message&&<div className="v07-message">{message}</div>}<section className="exports-domain-grid">{domains.filter(domain=>domain.id!=='photos').map(domain=><article key={domain.id} className="panel"><h2>{domain.label}</h2><div className="actions"><button disabled={Boolean(busy)} onClick={()=>exportDomain(domain,'csv')}><Download/> CSV complet</button><button disabled={Boolean(busy)} onClick={()=>exportDomain(domain,'xlsx')}><FileSpreadsheet/> Excel complet</button><button disabled={Boolean(busy)} onClick={()=>exportDomain(domain,'pdf')}><FileText/> PDF complet</button></div></article>)}</section>{photos&&<section className="panel exports-photos"><h2><Archive/> Exporter les photos</h2><div className="fieldGrid"><label>Support / infrastructure<input value={photoFilters.support} onChange={e=>setPhotoFilters({...photoFilters,support:e.target.value})}/></label><label>Campagne<input value={photoFilters.campaign} onChange={e=>setPhotoFilters({...photoFilters,campaign:e.target.value})}/></label><label>EDT<input value={photoFilters.edt} onChange={e=>setPhotoFilters({...photoFilters,edt:e.target.value})}/></label><label>Statut<input value={photoFilters.status} onChange={e=>setPhotoFilters({...photoFilters,status:e.target.value})}/></label><label>Du<input type="date" value={photoFilters.from} onChange={e=>setPhotoFilters({...photoFilters,from:e.target.value})}/></label><label>Au<input type="date" value={photoFilters.to} onChange={e=>setPhotoFilters({...photoFilters,to:e.target.value})}/></label><label><input type="checkbox" checked={photoFilters.activeOnly} onChange={e=>setPhotoFilters({...photoFilters,activeOnly:e.target.checked})}/> Photos actives seulement</label></div><button disabled={Boolean(busy)} onClick={exportPhotos}><Archive/> {busy==='photos:zip'?'Préparation…':'Télécharger le ZIP autorisé'}</button></section>}</div>;
}
