import React,{useMemo,useRef,useState}from'react';
import{Download,Pause,Play,RotateCcw,UploadCloud,XCircle}from'lucide-react';
import{applyBulkResolution,createImportId,createImportItem,errorCsv,importReport,importSummary,rematchManifestFiles,summaryCsv,virtualWindow}from'../lib/massPhotoImport.js';
import{analyzePhotoItem,listImportManifests,runControlledQueue,saveImportManifest,uploadPhotoItem}from'../services/massPhotoImportService.js';
import'../features/v10/mass-photo-import.css';

const steps=['Sélection','Analyse','Vérification','Import','Résultat'], ROW_HEIGHT=44, VIEWPORT_HEIGHT=440;
const download=(content,name,type='text/csv;charset=utf-8')=>{const url=URL.createObjectURL(new Blob(['\ufeff',content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};
export default function MassPhotoImporter({role}){
 const[batchId,setBatchId]=useState(createImportId),[items,setItems]=useState([]),[step,setStep]=useState(0),[supportId,setSupportId]=useState(''),[campaignId,setCampaignId]=useState(''),[edtId,setEdtId]=useState(''),[busy,setBusy]=useState(false),[paused,setPaused]=useState(false),[scrollTop,setScrollTop]=useState(0),[startedAt,setStartedAt]=useState(null),[endedAt,setEndedAt]=useState(null),[message,setMessage]=useState('');const control=useRef(null);const summary=useMemo(()=>importSummary(items),[items]),selected=items.filter(i=>i.selected),windowed=virtualWindow(items.length,scrollTop,{rowHeight:ROW_HEIGHT,viewportHeight:VIEWPORT_HEIGHT}),visible=items.slice(windowed.start,windowed.end),report=useMemo(()=>importReport(items,{batchId,startedAt,endedAt}),[items,batchId,startedAt,endedAt]);
 if(!['Administrateur','Coordonnateur'].includes(role))return <div className="sync-error-banner">Import massif non autorisé pour ce rôle.</div>;
 const update=(index,value)=>setItems(current=>current.map((item,i)=>i===index?value:item));
 function choose(event){const files=Array.from(event.target.files||[]);setBatchId(createImportId());setItems(files.map((file,index)=>createImportItem(file,index,{supportId})));setStep(0);setEndedAt(null)}
 async function restore(event){const files=Array.from(event.target.files||[]),manifests=await listImportManifests(),latest=manifests[0];if(!latest){setMessage('Aucun manifeste à reprendre.');return}const matched=await rematchManifestFiles(latest.items,files);setBatchId(latest.id);setItems([...latest.items.filter(i=>['completed','duplicate','skipped'].includes(i.status)),...matched]);setMessage(`${matched.length} fichier(s) non terminé(s) rematché(s).`);setStep(2)}
 async function process(mode,onlySelected=false){setBusy(true);if(!startedAt)setStartedAt(new Date().toISOString());setStep(mode==='analyze'?1:3);const eligible=item=>(!onlySelected||item.selected)&&(mode==='analyze'?['queued','failed','cancelled','requires_review'].includes(item.status):item.status==='ready');const snapshot=[...items];const task=await runControlledQueue(snapshot,async(item,index)=>{if(!eligible(item))return;let next;try{next=mode==='analyze'?await analyzePhotoItem(item,{supportId:item.supportId,explicitCampaign:item.campaignId?{id:item.campaignId}:null,explicitEdt:item.edtId?{id:item.edtId}:null}):await uploadPhotoItem({...item,status:'uploading'},{batchId});}catch(error){next={...item,status:'failed',error:error.message||'UPLOAD_FAILED'}}snapshot[index]=next;update(index,next)}, {concurrency:mode==='analyze'?2:6,batchSize:100},{onBatch:()=>saveImportManifest({id:batchId,items:snapshot}).catch(()=>{})});control.current=task.control;await task.run;setItems([...snapshot]);const end=new Date().toISOString();if(mode==='upload')setEndedAt(end);await saveImportManifest({id:batchId,items:snapshot,startedAt,endedAt:end}).catch(()=>{});setBusy(false);setPaused(false);setStep(mode==='analyze'?2:4)}
 function toggle(){if(paused){control.current?.resume();setPaused(false)}else{control.current?.pause();setPaused(true)}}
 function bulk(decision,label){if(!selected.length)return;if(!window.confirm(`Appliquer « ${label} » à ${selected.length} fichier(s) ?`))return;setItems(current=>applyBulkResolution(current,selected.map(i=>i.id),decision))}
 return <section className="mass-photo-import"><h2>Importer des photos en lot</h2>{message&&<div className="v07-message">{message}</div>}<ol className="mass-steps">{steps.map((label,index)=><li className={index<=step?'active':''} key={label}>{index+1}. {label}</li>)}</ol><div className="mass-controls"><label>Support par défaut<input value={supportId} onChange={e=>setSupportId(e.target.value)} placeholder="Ex. TOS-001"/></label><label className="mass-file">Sélectionner<input type="file" accept="image/*" multiple onChange={choose}/></label><label className="mass-file">Reprendre après fermeture<input type="file" accept="image/*" multiple onChange={restore}/></label>{items.length>0&&<><button disabled={busy} onClick={()=>process('analyze')}><RotateCcw/> Analyser / Réessayer les erreurs</button><button disabled={busy||!items.some(i=>i.status==='ready')} onClick={()=>process('upload')}><UploadCloud/> Importer</button><button disabled={busy||!selected.length} onClick={()=>process('analyze',true)}><RotateCcw/> Réessayer la sélection</button>{busy&&<button onClick={toggle}>{paused?<Play/>:<Pause/>}{paused?'Reprendre':'Pause'}</button>}<button disabled={!busy} onClick={()=>control.current?.cancel()}><XCircle/> Annuler en attente</button></>}</div>
 {selected.length>0&&<div className="mass-controls mass-bulk"><strong>{selected.length} sélectionné(s)</strong><input placeholder="Support" value={supportId} onChange={e=>setSupportId(e.target.value)}/><button onClick={()=>bulk({supportId},'support')} disabled={!supportId}>Appliquer support</button><input placeholder="Campagne ID" value={campaignId} onChange={e=>setCampaignId(e.target.value)}/><button onClick={()=>bulk({campaignId},'campagne')} disabled={!campaignId}>Appliquer campagne</button><input placeholder="EDT ID" value={edtId} onChange={e=>setEdtId(e.target.value)}/><button onClick={()=>bulk({edtId},'EDT')} disabled={!edtId}>Appliquer EDT</button><button onClick={()=>bulk({explicitType:'inspection'},'inspection')}>Confirmer inspection</button><button onClick={()=>bulk({status:'skipped'},'ignorer')}>Ignorer</button></div>}
 {items.length>0&&<><progress max={summary.total} value={summary.processed}/><p>{step<3?'Analyse':'Import'} {summary.processed.toLocaleString('fr-CA')} / {summary.total.toLocaleString('fr-CA')} — {summary.completed} réussies — {summary.duplicate} doublons — {summary.failed} erreurs — {summary.requiresReview} à vérifier</p><div className="mass-list" style={{height:VIEWPORT_HEIGHT,overflow:'auto'}} onScroll={e=>setScrollTop(e.currentTarget.scrollTop)}><div style={{height:windowed.totalHeight,position:'relative'}}><div style={{position:'absolute',top:windowed.offset,left:0,right:0}}>{visible.map((item,localIndex)=>{const index=windowed.start+localIndex;return <div className="mass-row" style={{height:ROW_HEIGHT}} key={item.id}><input type="checkbox" aria-label={`Sélectionner ${item.originalFilename}`} checked={item.selected} onChange={e=>update(index,{...item,selected:e.target.checked})}/><span>{item.originalFilename}</span><input aria-label={`Support ${item.originalFilename}`} value={item.supportId} onChange={e=>update(index,{...item,supportId:e.target.value,status:'queued',error:''})}/><b className={`state-${item.status}`}>{item.status}</b><small>{item.error}</small></div>})}</div></div></div><div className="mass-controls"><button disabled={!summary.failed&&!summary.requiresReview} onClick={()=>download(errorCsv(items),'erreurs-import-photos.csv')}><Download/> CSV erreurs</button><button onClick={()=>download(summaryCsv(report),'resume-import-photos.csv')}><Download/> CSV résumé</button><button onClick={()=>download(JSON.stringify({id:batchId,items,report},null,2),'manifeste-import-photos.json','application/json')}><Download/> Manifeste</button></div>{step===4&&<dl className="mass-report">{Object.entries(report).map(([key,value])=><React.Fragment key={key}><dt>{key}</dt><dd>{typeof value==='object'?JSON.stringify(value):String(value??'—')}</dd></React.Fragment>)}</dl>}</>}</section>
}
