import React,{useEffect,useMemo,useState}from'react';
import{Archive,Download,Eye,FileSpreadsheet,FileText,Pencil,RefreshCw,Send,Undo2}from'lucide-react';
import{archiveReport,createDraftReport,generateReport,loadReportData,publishReport,reportValue,unpublishReport,updateDraftReport}from'../services/reportDataService';
import{buildReportPreview,REPORT_TEMPLATES}from'../services/reportBuilder';
import{exportReportCsv,exportReportExcel}from'../services/reportExportService';

const tabs=[['general','Vue générale'],['reports','Cycle de vie'],['campaign','Campagnes'],['communication','Communications'],['site','Sites / supports'],['client','Clients'],['edt','EDT'],['inspection','Inspections'],['photos','Photos'],['issues','Enjeux'],['history','Historique']];
const statusLabels={draft:'Brouillon',generated:'Généré',published:'Publié',archived:'Archivé',error:'Erreur'};
const unavailable=<span className="report-unavailable">Donnée non disponible</span>;
export default function Module15Reports({dataStore,role}){
 const[data,setData]=useState(null),[tab,setTab]=useState('general'),[busy,setBusy]=useState(false),[type,setType]=useState('campaign'),[scope,setScope]=useState(''),[title,setTitle]=useState(''),[preview,setPreview]=useState(null),[statusFilter,setStatusFilter]=useState(''),[typeFilter,setTypeFilter]=useState('');
 const canManage=['Administrateur','Coordonnateur'].includes(role);
 const reload=async()=>{setBusy(true);try{setData(await loadReportData(dataStore))}finally{setBusy(false)}};
 useEffect(()=>{reload()},[dataStore]);
 const tabRows=useMemo(()=>!data?[]:({reports:data.reports,campaign:data.marketing,communication:data.communications,site:data.supports,client:data.clients,edt:data.edt,inspection:data.inspections,photos:data.photos,issues:data.issues,history:data.history}[tab]||[]),[data,tab]);
 const visibleRows=useMemo(()=>tab==='reports'?tabRows.filter(row=>(!statusFilter||row.status===statusFilter)&&(!typeFilter||row.report_type===typeFilter)):tabRows,[tab,tabRows,statusFilter,typeFilter]);
 const makePreview=()=>setPreview(buildReportPreview({type,scope,rows:tabRows.length?tabRows:(data?.reports||[])}));
 const mutate=async(action,confirmation)=>{if(busy||confirmation&&!window.confirm(confirmation))return;setBusy(true);try{await action();await reload()}finally{setBusy(false)}};
 const createDraft=()=>mutate(()=>createDraftReport({report_type:type,title:title||`Rapport ${scope||'sans titre'}`,campaign_id:type==='campaign'?scope||null:null,communication_id:type==='operational_communication'?scope||null:null,template_key:type}));
 const edit=row=>{const next=window.prompt('Titre du rapport',row.title);if(next&&next!==row.title)mutate(()=>updateDraftReport(row.id,{title:next}))};
 const actions=row=><div className="module15-row-actions">{['draft','generated','error'].includes(row.status)&&<button disabled={busy} onClick={()=>edit(row)}><Pencil/> Modifier</button>}{row.status==='draft'&&<button disabled={busy} onClick={()=>mutate(()=>generateReport(row.id,row.metadata))}><FileText/> Générer</button>}{row.status==='generated'&&<button disabled={busy} onClick={()=>mutate(()=>publishReport(row.id),'Publier ce rapport pour le client?')}><Send/> Publier</button>}{row.status==='published'&&<button disabled={busy} onClick={()=>mutate(()=>unpublishReport(row.id),'Dépublier ce rapport?')}><Undo2/> Dépublier</button>}{row.status!=='archived'&&<button disabled={busy} onClick={()=>mutate(()=>archiveReport(row.id),'Archiver ce rapport?')}><Archive/> Archiver</button>}<button onClick={()=>setPreview(buildReportPreview({type:row.report_type,scope:row.title,rows:[row]}))}><Eye/> {['published','archived'].includes(row.status)?'Ouvrir':'Prévisualiser'}</button>{['generated','published','archived'].includes(row.status)&&<button onClick={()=>exportReportCsv([row],`rapport-${row.id}.csv`)}><Download/> Télécharger</button>}</div>;
 return <div className="module15-page"><header className="module15-hero"><div><span className="eyebrow">Module 15</span><h1>Rapports et livrables</h1><p>Analytique opérationnelle, génération, vérification et publication des livrables.</p></div><button onClick={reload} disabled={busy}><RefreshCw/> Actualiser</button></header>
 <nav className="module15-tabs" aria-label="Sections des rapports">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {!data?<div role="status">Chargement…</div>:<>
 {tab==='general'&&<section className="module15-kpis">{[['Rapports générés','generated'],['Publiés','published'],['Brouillons','drafts'],['En erreur','errors'],['Récents','recent'],['Campagnes sans rapport','campaignsWithoutReport'],['Communications sans rapport','communicationsWithoutReport'],['EDT terminés sans rapport final','completedEdtWithoutReport']].map(([label,key])=><article key={key}><span>{label}</span><strong>{data.available?data.kpis[key]:unavailable}</strong></article>)}</section>}
 {tab!=='general'&&<section className="module15-list"><header><h2>{tabs.find(item=>item[0]===tab)?.[1]}</h2><div><button onClick={()=>exportReportCsv(visibleRows,`rapport-${tab}.csv`)}><Download/> CSV</button><button onClick={()=>exportReportExcel(visibleRows,`rapport-${tab}.xlsx`)}><FileSpreadsheet/> Excel</button></div></header>{tab==='reports'&&<div className="module15-filters"><label>Statut<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Tous</option>{Object.entries(statusLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Type<select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">Tous</option>{REPORT_TEMPLATES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div>}{visibleRows.length?visibleRows.slice(0,50).map((row,index)=><article key={row.id||index}><div><strong>{reportValue(row,'title','objet','nom_campagne','nom','support_id','no_edt','description')||'Élément'}</strong><span>{tab==='reports'?<b className={`report-status status-${row.status}`}>{statusLabels[row.status]||'Erreur'}</b>:reportValue(row,'client','site','statut','action','type_photo','created_at')||'—'}</span></div>{tab==='reports'&&canManage&&actions(row)}{tab==='photos'&&reportValue(row,'miniature_url','photo_miniature_url')&&<img loading="lazy" src={reportValue(row,'miniature_url','photo_miniature_url')} alt="Aperçu"/>}</article>):<p>Aucune donnée accessible.</p>}</section>}
 {canManage&&<section className="module15-builder"><h2>Générer un rapport</h2><ol><li>Type</li><li>Périmètre</li><li>Filtres</li><li>Prévisualisation</li><li>Génération</li><li>Vérification</li><li>Enregistrement</li><li>Publication éventuelle</li></ol><div className="module15-builder-fields"><label>Type<select value={type} onChange={e=>setType(e.target.value)}>{REPORT_TEMPLATES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Titre<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Titre du rapport"/></label><label>Périmètre<input value={scope} onChange={e=>setScope(e.target.value)} placeholder="Identifiant ou périmètre"/></label><button onClick={makePreview}><Eye/> Prévisualiser</button><button disabled={busy} onClick={createDraft}><FileText/> Enregistrer le brouillon</button></div>{preview&&<div className="module15-preview"><h3><FileText/> {preview.title}</h3><p>{preview.scope||'Tous les éléments accessibles'} · {preview.count} élément(s)</p><p>La publication demeure explicite; aucun brouillon n’est visible au client.</p></div>}</section>}
 {!canManage&&<p className="module15-readonly">Consultation des rapports publiés autorisés uniquement.</p>}
 </>}</div>
}
