import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,BarChart3,Bell,Camera,ChevronRight,ClipboardList,FileText,MapPin,RefreshCw,ShieldCheck}from'lucide-react';
import BrandLogo from'./BrandLogo';
import RecentActivityWidget from'./RecentActivityWidget';
import{displayKpiValue}from'../lib/module14Kpi.js';
import{countSupportPhotos}from'../services/photoInventoryService';
import{loadModule14Data,loadModule14OperationalKpis,marketingRows,operationalRows,uniqueMarketingAssignments,uniqueOperationalAssignments}from'../services/module14Service';

const fold=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const rows=(store,name)=>store?.[name]?.rows||[];
const active=row=>['active','actif','en cours','planifie','planifiee'].includes(fold(row.statut_campagne||row.statut));
const open=row=>!['ferme','fermee','resolu','resolue','termine','terminee','complete','completee','annule','annulee','archive','archivee'].includes(fold(row.statut));
const soon=row=>{const d=new Date(row.date_fin);const n=new Date();return !Number.isNaN(d.getTime())&&d>=n&&d-n<=7*86400000};
const late=row=>{const raw=row.date_fin_prevue||row.date_prevue_fin||row.date_echeance;if(!raw)return false;return new Date(raw)<new Date()&&open(row)};
function Kpi({label,value:count,target,onNavigate}){const destination=target==='Rapports finaux'?'Rapports EDT':target;return <button className="executive-kpi" onClick={()=>destination&&onNavigate(destination)} disabled={!destination}><span><BarChart3/>{label}</span><strong>{displayKpiValue(count)}</strong><small>{destination?'Ouvrir le module':'Source non disponible'}</small></button>}
function Bars({marketing,operational}){const max=Math.max(marketing,operational,1);return <article className="executive-panel"><header><div><span className="eyebrow">Répartition</span><h2>Marketing vs communication opérationnelle</h2></div><BarChart3/></header><div className="m14-bars">{[['Marketing',marketing],['Communication opérationnelle',operational]].map(([label,count])=><div key={label}><span>{label}</span><div><i style={{width:`${count/max*100}%`}}/></div><b>{count}</b></div>)}</div></article>}
function InternalDashboard({dataStore,onNavigate,role,permission,terrainSyncStatus}){
 const[photoCount,setPhotoCount]=useState({status:'loading'});
 useEffect(()=>{let live=true,request=0;const refresh=async()=>{const id=++request;try{const value=await countSupportPhotos();if(live&&id===request)setPhotoCount({status:'available',value})}catch{if(live&&id===request)setPhotoCount({status:'error'})}};refresh();window.addEventListener('tos-terrain-data-updated',refresh);return()=>{live=false;window.removeEventListener('tos-terrain-data-updated',refresh)}},[dataStore?.Photos]);
 const[data,setData]=useState({campaigns:[],assignments:[],visuals:[],available:false}),[operationalKpis,setOperationalKpis]=useState(Object.fromEntries(['terrain','reports','reportsCompleted','reportsSent','reportsToSend','reportsErrors'].map(key=>[key,{status:'loading'}]))),[error,setError]=useState(''),[tab,setTab]=useState('general');
 useEffect(()=>{if(!dataStore?.Infrastructures?.rows)return;let live=true;loadModule14Data({infrastructureRows:dataStore.Infrastructures.rows}).then(next=>live&&setData(next)).catch(e=>live&&setError(e.message));return()=>{live=false}},[dataStore?.Infrastructures]);
 useEffect(()=>{let live=true;loadModule14OperationalKpis().then(next=>live&&setOperationalKpis(next));return()=>{live=false}},[]);
 const model=useMemo(()=>{const marketing=marketingRows(data.campaigns),operational=operationalRows(data.campaigns),infra=rows(dataStore,'Infrastructures'),edt=rows(dataStore,'Suivi des EDT'),photos=rows(dataStore,'Photos'),issues=rows(dataStore,'Enjeux des cadres et supports'),work=rows(dataStore,'Bons de travail'),reports=rows(dataStore,'Rapports finaux');return{marketing,operational,marketingPlaces:uniqueMarketingAssignments(data.assignments),operationalPlaces:uniqueOperationalAssignments(data.assignments),marketingVisuals:marketingRows(data.visuals),operationalVisuals:operationalRows(data.visuals),infra,edt,photos,issues,work,reports,lateEdt:edt.filter(late),openIssues:issues.filter(open),missingPhotos:infra.filter(r=>!r.photo_principale_url&&!r.photo_miniature_url&&!r.visuel_actuel_cadre),urgent:work.filter(r=>fold(r.priorite).includes('urgent')&&open(r))}},[data,dataStore]);
 const tabs=[['general','Vue générale'],['marketing','Marketing'],['operational','Communication opérationnelle'],['terrain','Terrain'],['edt','EDT'],['infrastructure','Infrastructures'],['clients','Clients'],['reports','Rapports'],['alerts','Alertes'],['trends','Tendances']];
 const cards=tab==='marketing'?[["Campagnes actives",model.marketing.filter(active).length,'Campagnes maîtres'],['Supports affectés',model.marketingPlaces.length,'Campagnes maîtres'],['Visuels',model.marketingVisuals.length,'Campagne — Visuels et formats'],['Fin prochaine',model.marketing.filter(soon).length,'Campagnes maîtres']]:tab==='operational'?[["Communications actives",model.operational.filter(active).length,'Communications opérationnelles'],['Emplacements utilisés',model.operationalPlaces.length,'Communications opérationnelles'],['Visuels actifs',model.operationalVisuals.filter(v=>v.actif!==false).length,'Communication opérationnelle — Visuels'],['Expiration prochaine',model.operational.filter(soon).length,'Communications opérationnelles']]:[['Infrastructures actives',model.infra.filter(r=>r.actif!==false).length,'Infrastructures'],['Campagnes marketing actives',model.marketing.filter(active).length,'Campagnes maîtres'],['Communications opérationnelles actives',model.operational.filter(active).length,'Communications opérationnelles'],['EDT actifs',model.edt.filter(open).length,'Suivi des EDT'],['Enjeux ouverts',model.openIssues.length,'Enjeux des cadres et supports'],['Photos ajoutées',model.photos.length,'Photos et inventaire'],['Rapports',model.reports.length||null,'Rapports finaux'],['Synchronisations Terrain',terrainSyncStatus||null,'Diagnostic terrain']];
 const pendingFor=target=>['Campagnes maîtres','Communications opérationnelles'].includes(target)?!data.available:!dataStore?.[target];
 const alerts=[[model.lateEdt,'EDT en retard','Suivi des EDT'],[model.marketing.filter(soon),'Campagne marketing terminant bientôt','Campagnes maîtres'],[model.operational.filter(soon),'Communication expirant bientôt','Communications opérationnelles'],[model.urgent,'Enjeu Terrain urgent','Bons de travail'],[model.missingPhotos,'Photo manquante','Infrastructures']];
 const displayedCards=cards.map(([label,count,target])=>label==='Photos ajoutées'?[label,photoCount,target]:label==='Rapports'?[label,operationalKpis.reports,target]:label==='Synchronisations Terrain'?[label,operationalKpis.terrain,target]:['Infrastructures','Suivi des EDT','Enjeux des cadres et supports','Bons de travail','Clients'].includes(target)&&!dataStore?.[target]?[label,{status:'loading'},target]:(['Campagnes maîtres','Communications opérationnelles','Campagne — Visuels et formats','Communication opérationnelle — Visuels'].includes(target)&&!data.available)?[label,{status:error?'error':'loading'},target]:[label,count,target]);
 return <div className="dashboard executive-dashboard module14"><DashboardHeader status={error?'Données partiellement disponibles':!data.available?'Chargement des indicateurs…':'Données synchronisées'}/>
 <nav className="command-tabs" aria-label="Vues du centre de pilotage">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {error&&<div className="sync-error-banner">Classification indisponible jusqu’à l’application de la migration : {error}</div>}
 {['general','marketing','operational'].includes(tab)&&<><section className="executive-kpis">{displayedCards.map(([label,count,target])=><Kpi key={label} label={label} value={count} target={target} onNavigate={onNavigate}/>)}</section><section className="executive-layout">{data.available?<Bars marketing={model.marketing.length} operational={model.operational.length}/>:<p role="status">{error?'Répartition indisponible.':'Chargement de la répartition…'}</p>}<RecentActivityWidget onNavigate={onNavigate} role={role} permission={permission}/></section></>}
 {tab==='alerts'&&<section className="command-alerts">{alerts.map(([list,label,target])=><button key={label} onClick={()=>onNavigate(target)}><AlertTriangle/><span>{label}</span><strong>{pendingFor(target)?displayKpiValue({status:error?'error':'loading'}):list.length}</strong></button>)}</section>}
 {tab==='terrain'&&<section className="executive-kpis"><Kpi label="Bons de travail" value={dataStore?.['Bons de travail']?model.work.length:{status:'loading'}} target="Bons de travail" onNavigate={onNavigate}/><Kpi label="Photos" value={photoCount} target="Photos et inventaire" onNavigate={onNavigate}/><Kpi label="Erreurs Terrain actives" value={dataStore?.['Bons de travail']?model.urgent.length:{status:'loading'}} target="Diagnostic terrain" onNavigate={onNavigate}/></section>}
 {tab==='edt'&&<section className="executive-kpis"><Kpi label="EDT actifs" value={dataStore?.['Suivi des EDT']?model.edt.filter(open).length:{status:'loading'}} target="Suivi des EDT" onNavigate={onNavigate}/><Kpi label="EDT en retard" value={dataStore?.['Suivi des EDT']?model.lateEdt.length:{status:'loading'}} target="Suivi des EDT" onNavigate={onNavigate}/></section>}
 {tab==='infrastructure'&&<section className="executive-kpis"><Kpi label="Infrastructures" value={dataStore?.Infrastructures?model.infra.length:{status:'loading'}} target="Infrastructures" onNavigate={onNavigate}/><Kpi label="Nécessitant attention" value={dataStore?.Infrastructures?model.missingPhotos.length:{status:'loading'}} target="Infrastructures" onNavigate={onNavigate}/><Kpi label="Carte" value={dataStore?.Infrastructures?model.infra.length:{status:'loading'}} target="Carte interactive" onNavigate={onNavigate}/></section>}
 {tab==='clients'&&<section className="executive-kpis"><Kpi label="Clients" value={dataStore?.Clients?rows(dataStore,'Clients').length:{status:'loading'}} target="Clients" onNavigate={onNavigate}/></section>}
 {tab==='reports'&&<section className="executive-kpis"><Kpi label="EDT complétés" value={operationalKpis.reportsCompleted} target="Rapports EDT" onNavigate={onNavigate}/><Kpi label="Rapports envoyés" value={operationalKpis.reportsSent} target="Rapports EDT" onNavigate={onNavigate}/><Kpi label="Rapports à envoyer" value={operationalKpis.reportsToSend} target="Rapports EDT" onNavigate={onNavigate}/><Kpi label="Erreurs" value={operationalKpis.reportsErrors} target="Rapports EDT" onNavigate={onNavigate}/></section>}
 {tab==='trends'&&<>{data.available?<Bars marketing={model.marketing.length} operational={model.operational.length}/>:<p role="status">{error?'Répartition indisponible.':'Chargement de la répartition…'}</p>}<div className="command-empty">Les autres tendances seront affichées lorsqu’une série temporelle réelle sera disponible.</div></>}
 </div>;
}

// Client data is supplied by the scoped portal RPC/preview. This branch never
// mounts the internal dashboard loaders or RecentActivityWidget.
export default function Module14Dashboard(props){
 if(props.clientProjection){
  const {identity,views=[],sections={}}=props.clientProjection;
  return <div className="dashboard executive-dashboard module14 client-dashboard" data-reference-component="Module14Dashboard"><DashboardHeader status={`Données sécurisées · ${identity?.client_name||'Mon organisation'}`}/><section className="executive-kpis">{views.filter(view=>!['requests','members'].includes(view.id)).map(view=><Kpi key={view.id} label={view.label} value={sections[view.section]?.error?{status:'error'}:sections[view.section]?Number(sections[view.section].total||0):{status:'loading'}} target={view.id} onNavigate={props.onNavigate}/>)}</section>{!views.length&&<div className="client-empty">Aucune vue n’est actuellement autorisée pour votre profil.</div>}</div>;
 }
 if(['Client','Client-Admin'].includes(props.role))return <div role="alert">Données autorisées indisponibles.</div>;
 return <InternalDashboard {...props}/>;
}
function DashboardHeader({status}){return <header className="executive-hero"><div className="hero-brand"><BrandLogo priority/><div><h1>Tableau de bord</h1></div></div><div className="executive-status"><span className="status-dot"/> {status}</div></header>}
