import React,{useEffect,useMemo,useState}from'react';
import{Check,ChevronLeft,ChevronRight,Expand,RotateCw,Search,X}from'lucide-react';
import{ignoreReviewPhoto,listPhotoReviewQueue,searchSupports,validateReviewPhoto}from'../services/photoReviewService';
import'../features/v10/photo-review-queue.css';
const labels={needs_review:'À valider',unmatched:'Non reconnue',manually_validated:'Validée manuellement',ignored:'Ignorée',error:'Erreur'};
export default function PhotoReviewQueue(){const[rows,setRows]=useState([]),[filter,setFilter]=useState('all'),[sort,setSort]=useState('recent'),[selected,setSelected]=useState(new Set()),[choice,setChoice]=useState({}),[results,setResults]=useState({}),[viewer,setViewer]=useState(null),[rotation,setRotation]=useState(0),[zoom,setZoom]=useState(1),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{try{setRows(await listPhotoReviewQueue({status:filter}));setMessage('')}catch(e){setMessage(e.message)}};useEffect(()=>{load()},[filter]);
 const visible=useMemo(()=>[...rows].sort((a,b)=>sort==='oldest'?new Date(a.uploaded_at)-new Date(b.uploaded_at):sort==='confidence'?(b.ocr_confidence||0)-(a.ocr_confidence||0):sort==='name'?String(a.original_filename).localeCompare(String(b.original_filename)):new Date(b.uploaded_at)-new Date(a.uploaded_at)),[rows,sort]);
 const counts=useMemo(()=>rows.reduce((a,r)=>(a[r.review_status]=(a[r.review_status]||0)+1,a),{}),[rows]);
 async function find(id,value){setChoice(c=>({...c,[id]:value}));if(value.trim().length<2)return setResults(r=>({...r,[id]:[]}));const matches=await searchSupports(value);setResults(r=>({...r,[id]:matches}))}
 async function validate(ids,support){if(!support||!ids.length)return;setBusy(true);try{for(const id of ids){const photo=rows.find(r=>r.id===id);await validateReviewPhoto(photo,support)}setSelected(new Set());setMessage(`${ids.length} photo(s) rattachée(s) à ${support}.`);await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 const batchSupport=choice.batch||'';const viewerIndex=viewer===null?-1:visible.findIndex(r=>r.id===viewer);
 return <section className="photo-review-queue"><header><div><h2>Photos à valider</h2><p>Les originaux restent conservés jusqu’à une décision explicite.</p></div><div className="review-counters"><span>Importées <b>{rows.length}</b></span><span>À valider <b>{counts.needs_review||0}</b></span><span>Non reconnues <b>{counts.unmatched||0}</b></span><span>Validées <b>{counts.manually_validated||0}</b></span><span>Erreurs <b>{counts.error||0}</b></span></div></header>{message&&<div className="v07-message">{message}</div>}
 <div className="review-toolbar"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Toutes</option>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Plus récente</option><option value="oldest">Plus ancienne</option><option value="confidence">Confiance</option><option value="name">Nom de fichier</option></select>{selected.size>0&&<><input placeholder="Support pour la sélection" value={batchSupport} onChange={e=>find('batch',e.target.value)}/><button disabled={busy||!batchSupport} onClick={()=>validate([...selected],batchSupport)}><Check/> Valider les {selected.size} photos</button></>}</div>
 <div className="review-grid">{visible.map(photo=><article key={photo.id}><div className="review-thumb"><input type="checkbox" checked={selected.has(photo.id)} onChange={e=>setSelected(s=>{const n=new Set(s);e.target.checked?n.add(photo.id):n.delete(photo.id);return n})}/>{photo.signed_thumbnail_url?<button onClick={()=>{setViewer(photo.id);setRotation(0);setZoom(1)}}><img src={photo.signed_thumbnail_url} alt={photo.original_filename||photo.nom_fichier}/><Expand/></button>:<span>Aperçu indisponible</span>}</div><div className="review-card-body"><strong>{photo.original_filename||photo.nom_fichier}</strong><small>{new Date(photo.uploaded_at||photo.created_at).toLocaleString('fr-CA')} · {labels[photo.review_status]||photo.review_status}</small><dl><dt>Texte détecté</dt><dd>{photo.ocr_text||'—'}</dd><dt>Confiance</dt><dd>{photo.ocr_confidence==null?'—':`${photo.ocr_confidence} %`}</dd><dt>Suggestion</dt><dd>{photo.proposed_support_id||'—'}</dd></dl><label><Search/> Rechercher un support<input value={choice[photo.id]||''} onChange={e=>find(photo.id,e.target.value)}/></label>{results[photo.id]?.length>0&&<div className="support-results">{results[photo.id].map(s=><button key={s.support_id} onClick={()=>{setChoice(c=>({...c,[photo.id]:s.support_id}));setResults(r=>({...r,[photo.id]:[]}))}}><b>{s.support_id}</b><span>{s.site||s.emplacement_visibilite||s.no_cadre}</span></button>)}</div>}<div className="review-actions"><button disabled={busy||!choice[photo.id]} onClick={()=>validate([photo.id],choice[photo.id])}><Check/> Valider</button><button disabled={busy} onClick={async()=>{await ignoreReviewPhoto(photo.id);load()}}>Ignorer</button></div></div></article>)}</div>
 {viewerIndex>=0&&<div className="review-viewer" role="dialog" aria-modal="true"><button className="viewer-close" onClick={()=>setViewer(null)}><X/></button><button disabled={viewerIndex===0} onClick={()=>setViewer(visible[viewerIndex-1].id)}><ChevronLeft/></button><div><img style={{transform:`rotate(${rotation}deg) scale(${zoom})`}} src={visible[viewerIndex].signed_thumbnail_url} alt="Aperçu agrandi"/><footer><button onClick={()=>setZoom(z=>Math.min(4,z+.25))}>Zoom +</button><button onClick={()=>setZoom(z=>Math.max(.5,z-.25))}>Zoom −</button><button onClick={()=>setRotation(r=>r+90)}><RotateCw/> Rotation</button></footer></div><button disabled={viewerIndex===visible.length-1} onClick={()=>setViewer(visible[viewerIndex+1].id)}><ChevronRight/></button></div>}</section>}
