import React,{useEffect,useMemo,useState}from'react';
import{ArrowDown,ArrowUp,Download,ExternalLink,Search,Settings2}from'lucide-react';
import GridColumnHeader from'./GridColumnHeader';
import GridPagination from'./GridPagination';
import{getAllAssignmentsBySiteAndSupport,getMarketingAssignmentsBySiteAndSupport,getOperationalCommunicationAssignmentsBySiteAndSupport}from'../services/siteSupportBusinessService';
import{BUSINESS_CONTEXT}from'../lib/businessContext';
import{assignmentColumnProfile,assignmentColumnWidth}from'../lib/gridPresentation';

const campaignColumns=[['id','ID'],['nom_campagne','Nom campagne'],['visuel_terrain','Visuel terrain'],['date_debut','Date début'],['date_fin','Date fin'],['statut_campagne','Statut'],['support_id','Support'],['emplacement','Infrastructure'],['date_mise_a_jour','Date mise à jour'],['created_at','Créé le'],['updated_at','Modifié le'],['raw_data','Données source']];
const operationalColumns=[['id','ID'],['emplacement','Emplacement'],['message','Communication'],['date_debut','Date début'],['date_fin','Date fin'],['statut','Statut'],['no_arret','No arrêt'],['site_ou_arret','Site ou arrêt'],['support_id','Support'],['no_edt','EDT'],['related_voiture','Voiture'],['visuel_message','Visuel message'],['visuel_terrain','Visuel terrain'],['created_at','Créé le'],['updated_at','Dernière activité'],['raw_data','Données source']];
const enrichment=[['site','Site'],['infrastructure_id','Infrastructure ID'],['campaign_id','Relation campagne'],['visual_id','Relation visuel'],['business_context','Contexte métier'],['legacy_id','ID historique']];
campaignColumns.splice(8,0,['no_edt','EDT'],['date_completion','Installation']);
operationalColumns.splice(10,0,['date_completion','Installation']);
const dateKeys=new Set(['date_debut','date_fin','date_completion','date_mise_a_jour','created_at','updated_at']);
const dateFormatter=new Intl.DateTimeFormat('fr-CA',{timeZone:'America/Toronto',day:'2-digit',month:'short',year:'numeric'});
const csvCell=value=>`"${String(typeof value==='object'?JSON.stringify(value):value??'').replaceAll('"','""')}"`;

function exportCsv(rows,columns,name){const content=[columns.map(([,label])=>csvCell(label)).join(','),...rows.map(row=>columns.map(([key])=>csvCell(row[key])).join(','))].join('\r\n'),url=URL.createObjectURL(new Blob(['\ufeff',content],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}
function displayValue(key,value){if(value==null||value==='')return'—';if(dateKeys.has(key)){const date=new Date(value);if(!Number.isNaN(date.getTime()))return dateFormatter.format(date)}return typeof value==='object'?JSON.stringify(value):String(value)}
const cellKind=key=>dateKeys.has(key)?'is-compact':/(statut|status)/i.test(key)?'is-status':/(raw_data|message|campagne|visuel|emplacement)/i.test(key)?'is-long':'';

export default function SiteSupportAssignmentsView({context,onNavigate,role}){
 const operational=context===BUSINESS_CONTEXT.OPERATIONAL;
 const available=useMemo(()=>[...(operational?operationalColumns:campaignColumns),...enrichment],[operational]);
 const storageKey=`tos-grid-layout-v123-${operational?'operational':'campaign'}`;
 const[columns,setColumns]=useState(available),[widths,setWidths]=useState({}),[gridEditing,setGridEditing]=useState(false),[hydratedKey,setHydratedKey]=useState(null);
 const[result,setResult]=useState({rows:[],total:0,page:1,pageSize:25}),[search,setSearch]=useState(''),[filters,setFilters]=useState({}),[sortState,setSortState]=useState({column:'id',direction:'desc'});
 const[selected,setSelected]=useState(new Set()),[error,setError]=useState(''),[loading,setLoading]=useState(true),[exporting,setExporting]=useState(false);
 const canEdit=['Administrateur','Coordonnateur'].includes(role),title=operational?'Communications opérationnelles par site et supports':'Campagnes et visuels par site et supports';
 async function load(page=1,pageSize=result.pageSize){setLoading(true);setError('');try{const loader=operational?getOperationalCommunicationAssignmentsBySiteAndSupport:getMarketingAssignmentsBySiteAndSupport;setResult(await loader({page,pageSize,search,filters,sortState}))}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{setHydratedKey(null);let saved;try{saved=JSON.parse(localStorage.getItem(storageKey)||'null')}catch{}const byKey=new Map(available);const restored=(saved?.order||[]).filter(key=>byKey.has(key)).map(key=>byKey.get(key));setColumns(restored.length?restored:available);setWidths(saved?.widths||{});setFilters({});setSearch('');setSelected(new Set());setSortState({column:'id',direction:'desc'});setHydratedKey(storageKey)},[context,available,storageKey]);
 useEffect(()=>{if(hydratedKey===storageKey)localStorage.setItem(storageKey,JSON.stringify({order:columns.map(([key])=>key),widths}))},[columns,widths,storageKey,hydratedKey]);
 useEffect(()=>{const timer=setTimeout(()=>load(1,result.pageSize),250);return()=>clearTimeout(timer)},[context,search,filters,sortState]);
 const picked=result.rows.filter(row=>selected.has(row.logical_key));
 const go=(target,row,action)=>{sessionStorage.setItem('tos_assignment_context',JSON.stringify({action,support_id:row.support_id,campaign_id:row.campaign_id,visual_id:row.visual_id,edt:row.no_edt,business_context:context}));onNavigate?.(target,row)};
 const exportFiltered=async()=>{setExporting(true);setError('');try{exportCsv(await getAllAssignmentsBySiteAndSupport({context,search,filters,sortState}),columns,'affectations-ensemble-filtre.csv')}catch(e){setError(e.message)}finally{setExporting(false)}};
 const move=(index,direction)=>setColumns(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next});
 return <div className="tablePage assignment-page">
  <header className="assignment-header"><div><span className="eyebrow">Source canonique consolidée</span><h1>{title}</h1></div></header>
  <div className="searchbar assignment-search"><Search/><input aria-label="Recherche globale" placeholder="Recherche globale dans les colonnes métier…" value={search} onChange={event=>setSearch(event.target.value)}/></div>
  {error&&<div className="sync-error-banner">{error}</div>}
  {loading?<div className="client-loading">Chargement…</div>:<div className="client-table-wrap professional-grid assignment-grid-wrap"><table><colgroup><col className="assignment-select-col"/>{columns.map(([key,label])=>{const width=widths[key]||assignmentColumnWidth(result.rows,key,label);return <col key={key} style={{width,minWidth:width}}/>})}<col style={{width:assignmentColumnProfile('actions').preferredWidth}}/></colgroup><thead><tr><th><input aria-label="Sélectionner la page" type="checkbox" checked={result.rows.length>0&&picked.length===result.rows.length} onChange={event=>setSelected(current=>{const next=new Set(current);result.rows.forEach(row=>event.target.checked?next.add(row.logical_key):next.delete(row.logical_key));return next})}/></th>{columns.map(([key,label])=>key==='raw_data'?<th key={key} style={{width:widths[key]||assignmentColumnWidth(result.rows,key,label)}}>{label}</th>:<GridColumnHeader key={key} column={key} label={label} rows={result.rows} preferredWidth={widths[key]||assignmentColumnWidth(result.rows,key,label)} filterValue={filters[key]} onFilter={value=>setFilters(current=>({...current,[key]:value}))} sortState={sortState} onSort={setSortState} onReset={()=>setSortState(null)}/>)}<th className="assignment-actions-heading">Actions</th></tr></thead><tbody>{result.rows.map(row=><tr key={row.logical_key}><td><input aria-label={`Sélectionner ${row.support_id}`} type="checkbox" checked={selected.has(row.logical_key)} onChange={()=>setSelected(current=>{const next=new Set(current);next.has(row.logical_key)?next.delete(row.logical_key):next.add(row.logical_key);return next})}/></td>{columns.map(([key])=>{const value=displayValue(key,row[key]);return <td key={key} className={cellKind(key)} title={value}>{/(statut|status)/i.test(key)?<span className="assignment-status">{value}</span>:<span className="assignment-cell-text">{value}</span>}</td>})}<td className="assignment-actions"><button title={canEdit?'Modifier':'Ouvrir'} aria-label={canEdit?'Modifier':'Ouvrir'} onClick={()=>go(operational?'Communications opérationnelles':'Campagnes maîtres',row,canEdit?'edit':'open')}><ExternalLink/></button><button title="Visuel" onClick={()=>go(operational?'Communication opérationnelle — Visuels':'Campagne — Visuels et formats',row,'visual')}>Visuel</button><button title="Support / Fiche 360" onClick={()=>go('Infrastructures',row,'support360')}>Support</button>{row.no_edt&&<button title="EDT" onClick={()=>go('Centre EDT et BT',row,'edt')}>EDT</button>}<button title="Photos" onClick={()=>go('Photos et inventaire',row,'photos')}>Photos</button><button title="Historique" onClick={()=>go('Édition — Historique',row,'history')}>Hist.</button></td></tr>)}</tbody></table></div>}
  <div className="assignment-toolbar assignment-table-actions"><button type="button" onClick={()=>setGridEditing(value=>!value)}><Settings2/> Modifier la grille</button><button type="button" onClick={()=>exportCsv(result.rows,columns,'affectations-page-visible.csv')}><Download/> Page visible</button><button type="button" disabled={!picked.length} onClick={()=>exportCsv(picked,columns,'affectations-selection.csv')}><Download/> Sélection</button><button type="button" disabled={exporting} onClick={exportFiltered}><Download/> {exporting?'Préparation…':'Ensemble filtré'}</button></div>
  {gridEditing&&<div className="grid-edit-toolbar">{available.map(column=>{const index=columns.findIndex(item=>item[0]===column[0]),visible=index>=0,profile=assignmentColumnProfile(column[0],column[1]);return <div key={column[0]}><label><input type="checkbox" checked={visible} onChange={event=>setColumns(current=>event.target.checked?[...current,column]:current.filter(item=>item[0]!==column[0]))}/>{column[1]}</label>{visible&&<><button type="button" aria-label={`Déplacer ${column[1]} à gauche`} onClick={()=>move(index,-1)}><ArrowUp/></button><button type="button" aria-label={`Déplacer ${column[1]} à droite`} onClick={()=>move(index,1)}><ArrowDown/></button><input aria-label={`Largeur ${column[1]}`} type="number" min={profile.minWidth} max={profile.maxWidth} value={widths[column[0]]||''} placeholder={`${assignmentColumnWidth(result.rows,column[0],column[1])} px`} onChange={event=>setWidths(current=>({...current,[column[0]]:Number(event.target.value)||undefined}))}/></>}</div>})}<button type="button" onClick={()=>{setColumns(available);setWidths({});localStorage.removeItem(storageKey)}}>Réinitialiser la grille</button></div>}
  <GridPagination page={result.page} pageCount={Math.max(1,Math.ceil(result.total/result.pageSize))} pageSize={result.pageSize} total={result.total} selectedCount={selected.size} onPage={page=>load(page,result.pageSize)} onPageSize={size=>load(1,size)}/>
 </div>
}
