import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{ArrowDown,ArrowUp,Download,ExternalLink,Search,Settings2}from'lucide-react';
import UnifiedDataGrid from'./UnifiedDataGrid';
import GridPagination from'./GridPagination';
import{getAllAssignmentsBySiteAndSupport,getMarketingAssignmentsBySiteAndSupport,getOperationalCommunicationAssignmentsBySiteAndSupport}from'../services/siteSupportBusinessService';
import{BUSINESS_CONTEXT}from'../lib/businessContext';
import{assignmentColumnProfile,assignmentColumnWidth}from'../lib/gridPresentation';
import{assignmentColumns,formatAssignmentCell,isLatestAssignmentRequest,mergeAssignmentPreferences}from'../lib/assignmentGrid';

const dateKeys=new Set(['date_debut','date_fin','date_completion','date_mise_a_jour','created_at','updated_at']);
const csvCell=value=>`"${String(typeof value==='object'?JSON.stringify(value):value??'').replaceAll('"','""')}"`;
function exportCsv(rows,columns,name){const content=[columns.map(([,label])=>csvCell(label)).join(','),...rows.map(row=>columns.map(([key])=>csvCell(row[key])).join(','))].join('\r\n'),url=URL.createObjectURL(new Blob(['\ufeff',content],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}
const cellKind=key=>dateKeys.has(key)?'is-compact':/(statut|status)/i.test(key)?'is-status':/(raw_data|message|campagne|visuel|emplacement)/i.test(key)?'is-long':'';

export default function SiteSupportAssignmentsView({context,onNavigate,role}){
 const operational=context===BUSINESS_CONTEXT.OPERATIONAL;
 const definitions=useMemo(()=>assignmentColumns(context),[context]);
 const available=useMemo(()=>definitions.map(({id,label})=>[id,label]),[definitions]);
 const gridId=operational?'operational-site-supports':'campaigns-site-supports';
 const storageKey=`tos-grid-layout-v126-${gridId}`;
 const[columns,setColumns]=useState(available),[widths,setWidths]=useState({}),[gridEditing,setGridEditing]=useState(false),[hydratedKey,setHydratedKey]=useState(null);
 const[result,setResult]=useState({rows:[],total:0,page:1,pageSize:25,context:null}),[search,setSearch]=useState(''),[filters,setFilters]=useState({}),[sortState,setSortState]=useState({column:'id',direction:'desc'});
 const[selected,setSelected]=useState(new Set()),[error,setError]=useState(''),[isLoading,setLoading]=useState(true),[exporting,setExporting]=useState(false);
 const loading=isLoading||hydratedKey!==storageKey||result.context!==context;
 const canEdit=['Administrateur','Coordonnateur'].includes(role),title=operational?'Communications opérationnelles par site et supports':'Campagnes et visuels par site et supports';
 const requestRef=useRef(0),abortRef=useRef(null);
 const load=useCallback(async(page=1,pageSize=result.pageSize)=>{const requestId=++requestRef.current;abortRef.current?.abort();const controller=new AbortController();abortRef.current=controller;setLoading(true);setError('');try{const loader=operational?getOperationalCommunicationAssignmentsBySiteAndSupport:getMarketingAssignmentsBySiteAndSupport;const next=await loader({page,pageSize,search,filters,sortState,signal:controller.signal});if(isLatestAssignmentRequest(requestId,requestRef.current,controller.signal))setResult({...next,context})}catch(e){if(e?.name!=='AbortError'&&requestId===requestRef.current)setError(e.message||'Erreur de chargement')}finally{if(requestId===requestRef.current)setLoading(false)}},[context,operational,search,filters,sortState,result.pageSize]);
 useEffect(()=>()=>{requestRef.current+=1;abortRef.current?.abort()},[]);
 useEffect(()=>{setHydratedKey(null);let saved;try{saved=JSON.parse(localStorage.getItem(storageKey)||'null')}catch{}const merged=mergeAssignmentPreferences(definitions,saved);setColumns(merged.columns.map(({id,label})=>[id,label]));setWidths(merged.widths);setFilters({});setSearch('');setSelected(new Set());setSortState({column:'id',direction:'desc'});setHydratedKey(storageKey)},[context,definitions,storageKey]);
 useEffect(()=>{if(hydratedKey===storageKey)localStorage.setItem(storageKey,JSON.stringify({order:columns.map(([key])=>key),widths}))},[columns,widths,storageKey,hydratedKey]);
 useEffect(()=>{if(hydratedKey===storageKey)load(1,result.pageSize)},[load,hydratedKey,storageKey]);
 const picked=result.rows.filter(row=>selected.has(row.logical_key));
 const go=(target,row,action)=>{sessionStorage.setItem('tos_assignment_context',JSON.stringify({action,support_id:row.support_id,campaign_id:row.campaign_id,visual_id:row.visual_id,edt:row.no_edt,business_context:context}));onNavigate?.(target,row)};
 const exportFiltered=async()=>{setExporting(true);setError('');try{exportCsv(await getAllAssignmentsBySiteAndSupport({context,search,filters,sortState}),columns,'affectations-ensemble-filtre.csv')}catch(e){setError(e.message)}finally{setExporting(false)}};
 const move=(index,direction)=>setColumns(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next});
 const configuredColumns=columns.map(([id,label])=>{const profile=assignmentColumnProfile(id,label);return{id,label,type:dateKeys.has(id)?'date':/(quantit|total|nombre)/i.test(id)?'number':'text',sortable:id!=='raw_data',filterable:id!=='raw_data',width:widths[id]||assignmentColumnWidth(result.rows,id,label),minWidth:profile.minWidth,maxWidth:profile.maxWidth,className:cellKind(id)}});
 const selection={selected,toggle:key=>setSelected(current=>{const next=new Set(current);next.has(key)?next.delete(key):next.add(key);return next}),togglePage:(rows,checked)=>setSelected(current=>{const next=new Set(current);rows.forEach(row=>checked?next.add(row.logical_key):next.delete(row.logical_key));return next})};
 const actions=row=><div className="assignment-actions"><button title={canEdit?'Modifier':'Ouvrir'} aria-label={canEdit?'Modifier':'Ouvrir'} onClick={()=>go(operational?'Communications opérationnelles':'Campagnes maîtres',row,canEdit?'edit':'open')}><ExternalLink/></button><button title="Visuel" onClick={()=>go(operational?'Communication opérationnelle — Visuels':'Campagne — Visuels et formats',row,'visual')}>Visuel</button><button title="Support / Fiche 360" onClick={()=>go('Infrastructures',row,'support360')}>Support</button>{row.no_edt&&<button title="EDT" onClick={()=>go('Centre EDT et BT',row,'edt')}>EDT</button>}<button title="Photos" onClick={()=>go('Photos et inventaire',row,'photos')}>Photos</button><button title="Historique" onClick={()=>go('Édition — Historique',row,'history')}>Hist.</button></div>;
 return <div className="tablePage assignment-page">
  <header className="assignment-header"><div><span className="eyebrow">Source canonique consolidée</span><h1>{title}</h1></div></header>
  <div className="data-grid-toolbar"><div className="searchbar assignment-search"><Search/><input aria-label="Recherche globale" placeholder="Recherche globale dans les colonnes métier…" value={search} onChange={event=>setSearch(event.target.value)}/></div>{Object.values(filters).filter(value=>value?.length).length>0&&<><span className="grid-active-filter-count">Filtres actifs : {Object.values(filters).filter(value=>value?.length).length}</span><button onClick={()=>setFilters({})}>Effacer tous les filtres</button></>}</div>
  {error&&<div className="sync-error-banner">{error}</div>}
  {loading&&<div className="client-loading" role="status">Chargement…</div>}
  <UnifiedDataGrid gridId={gridId} columns={configuredColumns} rows={loading?[]:result.rows} filterRows={result.rows} filters={filters} onFilter={(column,value)=>setFilters(current=>({...current,[column]:value}))} sortState={sortState} onSort={setSortState} onResetSort={()=>setSortState(null)} rowKey={row=>row.logical_key} renderCell={(column,row)=>{const value=formatAssignmentCell(column.id,row[column.id]);return/(statut|status)/i.test(column.id)?<span className="assignment-status">{value}</span>:<span className="assignment-cell-text" title={value}>{value}</span>}} selection={selection} actions={actions} emptyMessage={loading?'Chargement…':'Aucune affectation.'}/>
  <div className="assignment-toolbar assignment-table-actions"><button type="button" onClick={()=>setGridEditing(value=>!value)}><Settings2/> Modifier la grille</button><button type="button" onClick={()=>exportCsv(result.rows,columns,'affectations-page-visible.csv')}><Download/> Page visible</button><button type="button" disabled={!picked.length} onClick={()=>exportCsv(picked,columns,'affectations-selection.csv')}><Download/> Sélection</button><button type="button" disabled={exporting} onClick={exportFiltered}><Download/> {exporting?'Préparation…':'Ensemble filtré'}</button></div>
  {gridEditing&&<div className="grid-edit-toolbar">{available.map(column=>{const index=columns.findIndex(item=>item[0]===column[0]),visible=index>=0,profile=assignmentColumnProfile(column[0],column[1]);return <div key={column[0]}><label><input type="checkbox" checked={visible} onChange={event=>setColumns(current=>event.target.checked?[...current,column]:current.filter(item=>item[0]!==column[0]))}/>{column[1]}</label>{visible&&<><button type="button" aria-label={`Déplacer ${column[1]} à gauche`} onClick={()=>move(index,-1)}><ArrowUp/></button><button type="button" aria-label={`Déplacer ${column[1]} à droite`} onClick={()=>move(index,1)}><ArrowDown/></button><input aria-label={`Largeur ${column[1]}`} type="number" min={profile.minWidth} max={profile.maxWidth} value={widths[column[0]]||''} placeholder={`${assignmentColumnWidth(result.rows,column[0],column[1])} px`} onChange={event=>setWidths(current=>({...current,[column[0]]:Number(event.target.value)||undefined}))}/></>}</div>})}<button type="button" onClick={()=>{setColumns(available);setWidths({});localStorage.removeItem(storageKey)}}>Réinitialiser la grille</button></div>}
  <GridPagination page={result.page} pageCount={Math.max(1,Math.ceil(result.total/result.pageSize))} pageSize={result.pageSize} total={result.total} selectedCount={selected.size} onPage={page=>load(page,result.pageSize)} onPageSize={size=>load(1,size)}/>
 </div>;
}
