import assert from 'node:assert/strict';
import fs from 'node:fs';
import {activityDedupKey,normalizeHistoricalEvent,reconstructHistoricalEvents} from '../src/lib/activityHistory.js';
let checks=0;const ok=(x,m)=>{assert.ok(x,m);checks++};
const exact={sourceSystem:'operations_history',sourceRecordId:'7',occurredAt:'2025-01-01T00:00:00Z',actorId:null,actorEmail:null,action:'creation',entityType:'edt',entityId:'2',confidence:'exact'};
assert.equal(activityDedupKey(exact),'operations_history:7');checks++;
assert.equal(normalizeHistoricalEvent({...exact,confidence:'unknown'}),null);checks++;
ok(normalizeHistoricalEvent(exact),'Événement exact refusé');ok(normalizeHistoricalEvent({...exact,sourceSystem:'support_photos',sourceRecordId:'9',confidence:'derived'}),'Événement dérivé refusé');
assert.equal(reconstructHistoricalEvents([exact,exact]).length,1);checks++;assert.equal(reconstructHistoricalEvents(reconstructHistoricalEvents([exact])).length,1);checks++;ok(normalizeHistoricalEvent(exact).actorEmail===null,'Utilisateur inconnu doit rester vide');
const files={structure:'supabase/V1_1_3_ACTIVITY_HISTORY_STRUCTURE.sql',backfill:'supabase/V1_1_3_ACTIVITY_HISTORY_BACKFILL.sql',dry:'supabase/DRY_RUN_V1_1_3_ACTIVITY_HISTORY.sql',verify:'supabase/VERIFIER_V1_1_3_ACTIVITY_HISTORY.sql',journal:'src/components/ActivityJournal.jsx',terrain:'src/components/TerrainSyncDiagnostics.jsx',service:'src/services/terrainDiagnosticsService.js',main:'src/main.jsx'};
const source=Object.fromEntries(Object.entries(files).map(([k,v])=>[k,fs.readFileSync(v,'utf8')]));
for(const table of['journal_des_evenements','operations_history','terrain_sync_diagnostics','terrain_operations','photo_action_log','journal_propagations','relation_field_config_audit','support_photos','historique_des_campagnes','edt_supports','suivi_des_edt'])ok(source.backfill.includes(table)&&source.dry.includes(table),`Source absente: ${table}`);
for(const token of['on conflict(source_system,source_record_id) do nothing','reconstruction_method','confidence'])ok(source.backfill.includes(token),token);
ok(!/truncate|delete\s+from|drop\s+table/i.test(source.backfill),'Backfill destructif');ok(/\nbegin;[\s\S]*commit;\s*$/i.test(source.backfill),'Backfill non transactionnel');
ok(source.dry.startsWith('begin read only;')&&source.dry.trim().endsWith('rollback;'),'Dry-run non READ ONLY');ok(source.verify.startsWith('begin read only;')&&source.verify.trim().endsWith('rollback;'),'Vérificateur non READ ONLY');ok(!/^\s*(insert|update|delete|truncate|drop|alter|create|call)\b/im.test(source.verify),'Vérificateur avec écriture');
for(const token of['GridPagination','Recherche globale','date_from','date_to','actor_email','module','campaign_id','edt_id','support_id','client_id','status'])ok(source.journal.includes(token),`Journal incomplet: ${token}`);
for(const token of['En attente','Erreurs actives','Réussies aujourd’hui','Dernière synchronisation','Réessayer','Marquer résolue','GridPagination'])ok(source.terrain.includes(token),`Terrain incomplet: ${token}`);
for(const token of['resolve_terrain_sync_v113','request_terrain_sync_retry_v113'])ok(source.service.includes(token),token);
ok(source.main.includes("active === 'Journal des événements'")&&/<ActivityJournal role=\{role\}[^>]*\/>/.test(source.main),'Route Journal non corrigée');
console.log(`V1.1.3 historique : ${checks} contrôles réussis.`);
