import assert from'node:assert/strict';import fs from'node:fs';import{applyBulkResolution,clampImportOptions,createImportItem,errorCsv,importReport,importSummary,prepareImportItem,readExifDate,rematchManifestFiles,virtualWindow}from'../src/lib/massPhotoImport.js';
const fake=(i=0)=>({name:`S1-${i}.jpg`,size:100+i,lastModified:Date.now(),type:'image/jpeg'});assert.equal(importSummary([]).total,0);assert.equal(createImportItem(fake(),0).status,'queued');
for(const count of[1,100,5000,20000]){const rows=Array.from({length:count},(_,i)=>createImportItem(fake(i),i,{supportId:'S1'}));assert.equal(importSummary(rows).total,count)}
assert.deepEqual(clampImportOptions({concurrency:99,batchSize:999}),{concurrency:10,batchSize:200});assert.deepEqual(clampImportOptions({concurrency:0,batchSize:1}),{concurrency:6,batchSize:50});
const ready=prepareImportItem(createImportItem(fake(),0,{supportId:'S1'}),{});assert.equal(ready.status,'ready');assert.match(ready.normalizedFilename,/^S1-\d{8}-INSPECTION-NONE-NONE-001\.jpg$/);assert.equal(ready.classification.reason,'no_active_business_context');
const review=prepareImportItem(createImportItem(fake(),0),{});assert.equal(review.status,'requires_review');assert.ok(errorCsv([{...review,status:'failed'}]).includes('fichier,support,statut,erreur'));
const windowed=virtualWindow(20000,999999);assert.ok(windowed.end-windowed.start<=20);assert.equal(windowed.totalHeight,880000);assert.equal(await readExifDate(fake()),null);
const selected=[{...createImportItem(fake(),0),selected:true}],bulk=applyBulkResolution(selected,[selected[0].id],{supportId:'S2',explicitType:'inspection'});assert.equal(bulk[0].supportId,'S2');assert.equal(bulk[0].status,'queued');
const manifest=[{...createImportItem(fake(),0),file:undefined,hash:'abc',status:'failed'}],matched=await rematchManifestFiles(manifest,[fake()],async()=> 'abc');assert.equal(matched.length,1);assert.ok(matched[0].file);const report=importReport([{...matched[0],status:'completed',classification:{reason:'no_active_business_context'}}],{batchId:'LOT',startedAt:'2026-01-01',endedAt:'2026-01-02'});assert.equal(report.total_imported,1);assert.equal(report.automatic_inspections,1);
const service=fs.readFileSync('src/services/massPhotoImportService.js','utf8'),workflow=fs.readFileSync('src/services/photoWorkflowService.js','utf8'),ui=fs.readFileSync('src/components/MassPhotoImporter.jsx','utf8');for(const marker of['prepareAndUploadPhoto','insertPhotoWithRollback','concurrency','batchSize','indexedDB','sha256','support-photos','readExifDate'])assert.ok(service.includes(marker),marker);assert.ok(workflow.includes('upsert:false'));for(const marker of['Pause','Reprendre','CSV erreurs','CSV résumé','Administrateur','Coordonnateur','virtualWindow','Réessayer la sélection','Appliquer support','Confirmer inspection'])assert.ok(ui.includes(marker),marker);console.log('V1.2.1 import massif: simulations 0/1/100/5 000/20 000, virtualisation, reprise et rapport réussis.');
