import fs from 'node:fs';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE SCHEMA auth;CREATE SCHEMA storage;CREATE SCHEMA tdm_private;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$SELECT '00000000-0000-0000-0000-000000000001'::uuid$$;
CREATE TABLE auth.users(id uuid,email text);CREATE TABLE storage.objects(bucket_id text,name text,owner_id text);
CREATE FUNCTION public.tos_current_role() RETURNS text LANGUAGE sql AS $$SELECT coalesce(nullif(current_setting('test.role',true),''),'Administrateur')$$;
CREATE FUNCTION public.tos_table_resource_scope(bigint,text,bigint,bigint,boolean) RETURNS boolean LANGUAGE sql AS $$SELECT coalesce($1,2)=2$$;
CREATE FUNCTION public.remove_visual_reference(bigint,text) RETURNS jsonb LANGUAGE sql AS $$SELECT '[]'::jsonb$$;
CREATE FUNCTION public.add_visual_reference(bigint,jsonb) RETURNS jsonb LANGUAGE sql AS $$SELECT '[]'::jsonb$$;
CREATE FUNCTION public.save_visual_edt_associations(bigint,jsonb) RETURNS void LANGUAGE sql AS $$SELECT$$;`);
const columns=JSON.parse(fs.readFileSync('scripts/fixtures/visual-terrain-schema.json'));
for(const table of [...new Set(columns.map(c=>c.table_name))]){
 const fields=columns.filter(c=>c.table_name===table).map(c=>`"${c.column_name}" ${c.data_type}${c.column_name==='id'?(c.data_type==='bigint'?' GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY':' PRIMARY KEY DEFAULT gen_random_uuid()'):c.default_value&&!c.default_value.includes('nextval(')?' DEFAULT '+c.default_value:''}`);
 await db.exec(`CREATE TABLE public."${table}"(${fields.join(',')});`);
}
await db.exec(`CREATE UNIQUE INDEX local_support_key ON infrastructures(support_id);CREATE UNIQUE INDEX local_operation_reference ON terrain_operations(reference);
CREATE FUNCTION tdm_private.capture_display_baseline(text) RETURNS void LANGUAGE sql AS $$SELECT$$;
CREATE FUNCTION tdm_private.display_state(text) RETURNS jsonb LANGUAGE sql AS $$SELECT to_jsonb(i) FROM infrastructures i WHERE support_id=$1$$;
CREATE FUNCTION tdm_private.apply_display_state(text,jsonb) RETURNS void LANGUAGE sql AS $$SELECT$$;
INSERT INTO clients(id) VALUES(2),(3);INSERT INTO utilisateurs(id,auth_user_id,role,statut) VALUES(1,auth.uid(),'Administrateur','Actif');
INSERT INTO infrastructures(id,support_id,client_id,actif,photo_principale_url) VALUES(1,'TEST-SUPPORT',2,'Oui','original.jpg');
INSERT INTO campagnes_maitres(id,client_id,nom_campagne) VALUES(1,2,'Test');
INSERT INTO campagne_visuels_formats(id,client_id,campagne_id,nom_visuel,format_support) VALUES(1,2,1,'Test visual','20 x 28');
INSERT INTO repertoire_des_affiches(id,client_id,nom_detaille_visuel,nom_campagne,format,quantite_entrepot,quantite_expo) VALUES(1,2,'Test visual','Test','20 x 28',100,50),(2,3,'Wrong client','Test','20 x 28',1,0),(3,2,'Wrong format','Test','24 x 36',1,0);`);
await db.exec(fs.readFileSync('scripts/fixtures/visual-terrain-baseline.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/20260920220303_visual_terrain_stock_workflows.sql','utf8'));
const query=async(sql,args=[])=>(await db.query(sql,args)).rows;
const stock=async()=>{const [r]=await query('select quantite_entrepot,quantite_expo from repertoire_des_affiches where id=1');return Object.values(r);};
let sequence=0;
const issue=async type=>{
 const path=`supports/TEST-SUPPORT/issue-${++sequence}.jpg`;
 await query("insert into storage.objects values('terrain-photos',$1,auth.uid()::text)",[path]);
 const [{result}]=await query("select finaliser_intervention_terrain_v1342('TEST-SUPPORT',null,'enjeu',$1,'','issue.jpg',$2,null,null,$2) result",[type,path]);assert.equal(result.ok,true,JSON.stringify(result));return result.enjeu_id;
};
const resolve=async id=>{
 const path=`supports/TEST-SUPPORT/resolution-${id}.jpg`;await query("insert into storage.objects values('terrain-photos',$1,auth.uid()::text)",[path]);
 const [{result}]=await query("select resolve_terrain_issue($1,'resolution.jpg',$2,null) result",[id,path]);assert.equal(result.ok,true);return result;
};
const rules=await query('select * from terrain_issue_types order by sort_order');assert.equal(rules.length,11);
for(const rule of rules){const id=await issue(rule.label);const [r]=await query('select * from enjeux_terrain where id=$1',[id]);assert.equal(r.duration,rule.duration);assert.equal(r.deactivates_support,rule.deactivates_support);assert.equal((await query('select actif from infrastructures'))[0].actif,rule.deactivates_support?'Non':'Oui');await resolve(id);assert.equal((await query('select actif from infrastructures'))[0].actif,'Oui');assert.equal((await query('select photo_principale_url from infrastructures'))[0].photo_principale_url,'original.jpg');assert.ok((await query('select resolved_at,resolved_by,resolution_photo_id from enjeux_terrain where id=$1',[id]))[0].resolution_photo_id);}
const one=await issue(rules[0].label),two=await issue(rules[1].label);await resolve(one);assert.equal((await query('select actif from infrastructures'))[0].actif,'Non');await resolve(two);assert.equal((await query('select actif from infrastructures'))[0].actif,'Oui');await resolve(two);
await db.exec("update infrastructures set actif='Non'");const nonblocking=await issue(rules[3].label);await resolve(nonblocking);assert.equal((await query('select actif from infrastructures'))[0].actif,'Non');
await assert.rejects(()=>db.exec('update campagne_visuels_formats set inventory_item_id=2 where id=1'),/même client/);await assert.rejects(()=>db.exec('update campagne_visuels_formats set inventory_item_id=3 where id=1'),/même client/);
await db.exec('update campagne_visuels_formats set inventory_item_id=1 where id=1');
const movement=async(kind='installation')=>(await query(`insert into historique_des_campagnes(support_id,client_id,${kind==='installation'?'date_installation':'date_retrait'},raw_data,movement_meta) values('TEST-SUPPORT',2,now()::text,'{"reference":"test-stock"}',jsonb_build_object($1::text,jsonb_build_object('state',jsonb_build_object('visuel_id',1)))) returning id`,[kind]))[0].id;
const first=await movement();assert.deepEqual(await stock(),[99,51]);await db.exec(`update historique_des_campagnes set movement_meta=movement_meta where id=${first}`);assert.deepEqual(await stock(),[99,51]);await movement('retrait');assert.deepEqual(await stock(),[100,50]);
await db.exec('update repertoire_des_affiches set quantite_entrepot=0 where id=1');const count=(await query('select count(*) n from historique_des_campagnes'))[0].n;await assert.rejects(()=>movement(),/Stock insuffisant/);assert.equal((await query('select count(*) n from historique_des_campagnes'))[0].n,count);
await db.exec("update repertoire_des_affiches set quantite_entrepot=100 where id=1");await db.exec("BEGIN");await movement();await db.exec('ROLLBACK');assert.deepEqual(await stock(),[100,50]);
await db.exec("insert into support_photos(id,client_id,source,statut_validation,storage_bucket,storage_path) select 1000+n,2,'mass_import','À valider','support-photos','review/'||n||'.jpg' from generate_series(1,20)n;insert into storage.objects select 'support-photos','review/'||n||'.jpg',auth.uid()::text from generate_series(1,20)n;");
const ids=[1001,1002,1003,1004,1005];assert.equal((await query('select jsonb_array_length(delete_review_photos($1,false)) n',[ids]))[0].n,5);
await assert.rejects(()=>db.exec("update support_photos set import_finalized_at=now() where id=1001"),/Suppression/);await assert.rejects(()=>query('select delete_review_photos($1,true)',[ids]),/Storage/);
await db.exec("delete from storage.objects where bucket_id='support-photos' and name in ('review/1.jpg','review/2.jpg','review/3.jpg','review/4.jpg','review/5.jpg')");await query('select delete_review_photos($1,true)',[ids]);assert.equal((await query('select count(*)::int n from support_photos where id>1000'))[0].n,15);
await db.exec("update support_photos set import_finalized_at=now() where id=1006");await assert.rejects(()=>query('select delete_review_photos($1,false)',[[1006,1007]]),/finalisée/);assert.equal((await query('select review_delete_requested_at from support_photos where id=1007'))[0].review_delete_requested_at,null);
await db.exec("update utilisateurs set role='Client-Admin'");await assert.rejects(()=>query('select delete_review_photos($1,false)',[[1007]]),/denied/);await assert.rejects(()=>resolve(one),/denied/);
await db.close();console.log('PASS: local PostgreSQL 11 issue types, resolution/history/photos, conditional activation, stock 100/50 → 99/51 → 100/50, format/client denial, zero stock, rollback, batch 20→15, finalized guard and role denial');
