import fs from 'node:fs';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
await db.exec(`CREATE TABLE suivi_des_edt(id bigint,no_edt text,client_id bigint,campagne_id bigint,statut text,lifecycle_status text,progression int,raw_data jsonb,archived_at timestamptz,archived_by uuid,archive_reason text,updated_at timestamptz,date_debut text);
CREATE TABLE edt_phases(edt_id bigint,progression int,closed_at timestamptz,id bigint);
CREATE TABLE campagne_visuels_formats(id bigint,client_id bigint,nom_visuel text,edt_phase_id bigint);
CREATE TABLE visual_edt_associations(visual_id bigint,edt_id bigint);
CREATE FUNCTION portal_business_context(text,text) RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT coalesce(jsonb_agg(to_jsonb(x)),'[]') FROM (SELECT * FROM public.suivi_des_edt WHERE archived_at IS NULL ORDER BY date_debut DESC NULLS LAST)x$$;
INSERT INTO suivi_des_edt(id,no_edt,client_id,campagne_id,statut,lifecycle_status,progression,archived_at,archive_reason) VALUES(22,'EDT-TOS-22-A',2,15,'Terminé','retrait_termine',100,now(),'historic'),(10,'EDT-TOS-09 (0.1)',2,11,'Annule','annule',0,now(),'historic');
INSERT INTO edt_phases VALUES(22,100,now(),40),(22,100,now(),41);
INSERT INTO campagne_visuels_formats VALUES(1,2,'Affiche Gare',40),(2,3,'Other client',40);
INSERT INTO visual_edt_associations VALUES(1,22);`);
await db.exec(fs.readFileSync('supabase/migrations/20260920101926_edt_completed_visibility.sql','utf8'));
const {rows}=await db.query('SELECT * FROM suivi_des_edt ORDER BY id');
assert(rows[0].archived_at);assert.equal(rows[0].statut,'Annule');
assert.equal(rows[1].archived_at,null);assert.equal(rows[1].statut,'Terminé');
assert.equal(rows[1].raw_data.completed_visibility_restoration.archive_reason,'historic');
assert.equal((await db.query("select jsonb_array_length(portal_business_context('operations',null)) n")).rows[0].n,2);
const projection=(await db.query("select portal_business_context('operations',null) data")).rows[0].data;
assert.equal(projection.find(e=>e.id===22).visual_names,'Affiche Gare');
await db.close();console.log('PASS: local PostgreSQL projection, completed restoration, former archive metadata and cancelled EDT preservation');
