import assert from 'node:assert/strict';
import fs from 'node:fs';
const main = fs.readFileSync('src/main.jsx', 'utf8');
const brand = fs.readFileSync('src/components/BrandLogo.jsx', 'utf8');
const support = fs.readFileSync('src/components/Support360Panel.jsx', 'utf8');
const dataService = fs.readFileSync('src/services/dataService.js', 'utf8');
const css = fs.readFileSync('src/styles.css', 'utf8');
assert.ok(brand.includes('/assets/logo-groupe-tos-web-transparent.png'));
assert.ok(fs.existsSync('public/assets/logo-groupe-tos-officiel.png'));
assert.ok(fs.existsSync('public/assets/logo-groupe-tos-web-transparent.png'));
assert.ok(brand.includes('alt="Groupe TOS"'));
assert.ok(main.includes('lazy(() => import'));
assert.ok(main.includes("fallback: () => import('./data/infrastructures.json')"));
assert.ok(dataService.includes('resolveFallback'));
assert.ok(main.includes('Suspense'));
assert.ok(main.includes('<BrandLogo priority/>'));
assert.ok(support.includes("['activity',Activity,'Activité']"));
assert.ok(css.includes('prefers-reduced-motion:reduce'));
assert.ok(css.includes(':focus-visible'));
assert.ok(css.includes('@media(max-width:700px)'));
console.log('Bloc 13.2 Lot 3 : logo officiel, chargement différé, responsive, focus et mouvement réduit validés.');
