import assert from 'node:assert/strict';
import fs from 'node:fs';
import React from 'react';
import {renderToStaticMarkup}from'react-dom/server';
import{createServer}from'vite';
const source=fs.readFileSync('src/components/Module15Reports.jsx','utf8'),main=fs.readFileSync('src/main.jsx','utf8'),service=fs.readFileSync('src/services/reportDataService.js','utf8'),builder=fs.readFileSync('src/services/reportBuilder.js','utf8'),module14=fs.readFileSync('src/components/Module14Dashboard.jsx','utf8'),clientService=fs.readFileSync('src/services/clientPortalService.js','utf8'),exportsSource=fs.readFileSync('src/services/reportExportService.js','utf8'),finalService=fs.readFileSync('src/services/finalReportService.js','utf8');
const vite=await createServer({server:{middlewareMode:true},appType:'custom',logLevel:'silent'});
try{const{default:Module15}=await vite.ssrLoadModule('/src/components/Module15Reports.jsx');const html=renderToStaticMarkup(React.createElement(Module15,{dataStore:{},role:'Administrateur'}));
for(const label of['Rapports et livrables','Vue générale','Cycle de vie','Campagnes','Communications','Sites / supports','Clients','EDT','Inspections','Photos','Enjeux','Historique'])assert.ok(html.includes(label),`Écran manquant: ${label}`);assert.ok(source.includes('Générer un rapport'),'Workflow de génération absent');
for(const label of['Rapports générés','Publiés','Brouillons','En erreur','Récents','Campagnes sans rapport','Communications sans rapport','EDT terminés sans rapport final'])assert.ok(source.includes(label),`KPI manquant: ${label}`);
for(const type of['Campagne marketing','Communication opérationnelle','Site / support','Client','EDT','Inspection'])assert.ok(source.includes('REPORT_TEMPLATES')||source.includes(type));
assert.ok(source.includes('Aucune donnée accessible')&&!source.includes('NaN'),'Zéro/indisponibilité non protégés');for(const operation of['createDraftReport','updateDraftReport','generateReport','publishReport','unpublishReport','archiveReport','getReport','listReports'])assert.ok(service.includes(operation),`Opération absente: ${operation}`);for(const action of['Modifier','Générer','Publier','Dépublier','Archiver','Prévisualiser'])assert.ok(source.includes(action),`Action absente: ${action}`);assert.ok(source.includes('window.confirm')&&source.includes('if(busy'),'Confirmations ou double soumission absentes');assert.ok(builder.includes("archived:[]")&&builder.includes('canTransitionReport'),'Transitions fermées absentes');assert.ok(exportsSource.includes('exportReportCsv')&&exportsSource.includes("import('xlsx')"),'CSV/Excel ou lazy load absent');assert.ok(finalService.includes("await import('jspdf')")&&finalService.includes("await import('xlsx')"),'PDF/XLSX non différés');assert.ok(main.includes("lazy(() => import('./components/Module15Reports'))")&&main.includes("active === 'Rapports et livrables'"),'Navigation/lazy load absent');assert.ok(service.includes("from('reports')")&&service.includes("'Suivi des EDT'")&&service.includes("'Photos'")&&service.includes("'Enjeux des cadres et supports'")&&service.includes("from('activity_events')"),'Sources réelles incomplètes');assert.ok(module14.includes('reportsPublished')&&module14.includes('reportsDraft')&&module14.includes('reportsToProduce'),'Module 14 incomplet');assert.ok(clientService.includes('module15_client_reports_v130'),'Module 17 non raccordé');assert.ok(!source.includes('Supabase')&&!source.includes('business_context'),'Terme technique visible');
const clientHtml=renderToStaticMarkup(React.createElement(Module15,{dataStore:{},role:'Client'}));assert.ok(!clientHtml.includes('Générer un rapport'),'Action interne exposée au client');
console.log('Module 15: écrans, KPI, rapports métier, exports, aperçu, permissions, sources et chargements différés validés.');}finally{await vite.close()}
