import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { clientPortalAccessStatus } from '../src/lib/clientPortalAccessStatus.js';
const read = file => readFileSync(file, 'utf8');
const ui = read('src/components/ClientsAccessAdmin.jsx');
const service = read('src/services/clientAccessAdminService.js');
const sql = read('supabase/V1_3_5_CLIENTS_ACCESS_ADMIN_PREPARED.sql');
assert.equal(clientPortalAccessStatus({ active_authenticated_count: 1 }), 'ACTIF');
assert.equal(clientPortalAccessStatus({ pending_invitation_count: 1 }), 'INVITATION EN ATTENTE');
assert.equal(clientPortalAccessStatus({}), 'À ACTIVER');
assert.equal(clientPortalAccessStatus({ statut_client: 'Actif' }), 'À ACTIVER');
assert.equal(clientPortalAccessStatus({ active_member_count: 1 }), 'INCOMPLET');
for (const marker of ['Ajouter un client','Modifier le client','Voir les accès','Client-Admin','Membres actifs','Invitations en attente','Campagnes autorisées','Dernière activité']) assert.ok(ui.includes(marker), marker);
for (const marker of ['admin_client_access_overview_v135','admin_client_access_detail_v135','admin_create_client_v135','admin_update_client_v135']) assert.ok(service.includes(marker) && sql.includes(marker), marker);
assert.ok(sql.includes('auth.uid()is null'));
assert.ok(sql.includes("set search_path=''"));
assert.ok(sql.includes('from public,anon'));
assert.ok(sql.includes("current_app_role()<>'Administrateur'"));
assert.ok(sql.includes('client_campaign_access'));
assert.ok(sql.includes("status='accepted'"));
assert.ok(sql.includes('auth_user_id is not null'));
assert.ok(!ui.match(/Supprimer le client/i));
assert.ok(service.includes("role: 'Client-Admin'"));
console.log('Clients V1.3.5: UI, statuts, permissions, batch et Module 17 validés.');
