import assert from 'node:assert/strict';
import {filterEdts,edtStatus} from '../src/lib/edtList.js';
const identifiers=['EDT-TOS-108','EDT-TOS-09.0.1','EDT-TOS-73-A','EDT-TOS-22-A','EDT-TOS-09','EDT-TOS-9'];
const rows=identifiers.map((no_edt,id)=>({id,no_edt,nom:'Campagne été',client:'EXO',statut:'Terminé',visual_names:'Affiche Gare',progression:100}));
assert.deepEqual(filterEdts(rows).map(r=>r.no_edt),['EDT-TOS-9','EDT-TOS-09','EDT-TOS-09.0.1','EDT-TOS-22-A','EDT-TOS-73-A','EDT-TOS-108']);
assert.equal(filterEdts(rows,'EDT-TOS-22-A','Terminés').length,1);
assert.equal(filterEdts(rows,'EDT-TOS-09.0.1','Terminés').length,1);
for(const query of ['ete','EXO','termine','Affiche Gare'])assert.equal(filterEdts(rows,query).length,6);
assert.deepEqual(filterEdts(rows,'EXO').map(r=>r.id),filterEdts(rows).map(r=>r.id));
assert.equal(filterEdts([{id:10,no_edt:'EDT-TOS-09 (0.1)',statut:'Annule',archived_at:'2026-01-01'}],'EDT-TOS-09.0.1','Archivés').length,1);
const archived={...rows[0],archived_at:'2026-01-01'};
assert.equal(edtStatus(archived),'Archivé');
assert.equal(edtStatus({statut:'Terminé',lifecycle_status:'archive'}),'Archivé');
assert.equal(filterEdts([...rows,archived],'','Terminés').length,6);
assert.equal(filterEdts([...rows,archived],'','Archivés').length,1);
assert.equal(filterEdts([...rows,archived],'','Tous').length,7);
assert.equal(edtStatus({statut:'Fermé',lifecycle_status:'ferme'}),'Terminé');
assert.equal(edtStatus({statut:'Annulé',lifecycle_status:'annule'}),'Annulé');
console.log('PASS: natural EDT order, zero padding, punctuation aliases, search, completed/archive distinction and all filters');
