import fs from 'node:fs';import assert from 'node:assert/strict';import {offlineBrowser} from './lib/offlineBrowser.mjs';
const records=[];await offlineBrowser('scripts/fixtures/strict-lifecycle-entry.jsx',async({evaluate,waitFor,sleep,exceptions,consoleErrors})=>{
for(const role of ['Administrateur','Coordonnateur'])for(const action of ['installation','retrait','missing','closed']){
await evaluate('mount('+JSON.stringify(role)+','+JSON.stringify(['missing','closed'].includes(action)?action:'open')+')');await sleep(80);await waitFor('!!document.querySelector(".lifecycle-close")');
let selector=action==='closed'?'document.querySelector(".lifecycle-close button")':action==='missing'?'document.querySelector("[data-phase-type=retrait] button")':'[...document.querySelectorAll("[data-phase-type='+action+'] .phase-actions button")].find(n=>n.textContent==="Terminer")';
if(action==='missing'){assert.equal(await evaluate(selector+'.disabled'),true);await evaluate('const n=document.querySelector("[data-phase-type=retrait] input");Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(n,"2026-10-02");n.dispatchEvent(new Event("input",{bubbles:true}))');await sleep(40)}
assert.equal(await evaluate(selector+'.disabled'),false);await evaluate('fixture.fail=true;'+selector+'.click()');await waitFor('document.body.textContent.includes("LIFECYCLE_ERROR")');await evaluate('fixture.fail=false;fixture.hold=true;fixture.calls=[];const b='+selector+';b.click();b.click()');await sleep(30);assert.equal(await evaluate(selector+'.disabled'),true);await evaluate('fixture.hold=false;fixture.pending.splice(0).forEach(resolve=>resolve())');await waitFor('!'+selector+'.disabled');const calls=await evaluate('fixture.calls');assert.equal(calls.length,1);assert.equal(calls[0].name,action==='closed'?'closeEdtLifecycle':action==='missing'?'createRemovalPhase':'transitionEdtPhase');assert.equal(calls[0].args[0],action==='installation'?7:action==='retrait'?8:1);records.push({role,action,result:'PASS_LOCAL',tests:'enabled contract|error/retry|pending disabled|double click one mutation|target ID'});
}
for(const role of ['Client','Client-Admin','Installateur']){await evaluate('mount('+JSON.stringify(role)+',"closed")');await sleep(70);assert.equal(await evaluate('document.querySelectorAll(".phase-actions button,.lifecycle-close button").length'),0);records.push({role,result:'PASS_LOCAL',tests:'management actions absent'})}
assert.deepEqual(exceptions,[]);assert.deepEqual(consoleErrors,[]);fs.writeFileSync('docs/stabilization-local/certification/strict/lifecycle-results.json',JSON.stringify({records,exceptions,consoleErrors},null,2));});console.log(records.length+' strict lifecycle cases PASS');
