import assert from'node:assert/strict';import fs from'node:fs';
const read=p=>fs.readFileSync(p,'utf8'),source=read('src/components/Module15Reports.jsx'),service=read('src/services/reportDataService.js'),main=read('src/main.jsx'),module14=read('src/components/Module14Dashboard.jsx'),client=read('src/services/clientPortalService.js'),pdf=read('src/services/finalReportService.js');
for(const label of['Rapports EDT','Suivi des rapports finaux','Recherche globale','Aucun EDT complété pour le moment.'])assert.ok(source.includes(label),label);
for(const forbidden of['Vue générale','Cycle de vie','Campagnes</button>','Communications</button>','Inspections','Générer un rapport','Publier','Dépublier','Archiver','Périmètre','REPORT_TEMPLATES'])assert.ok(!source.includes(forbidden),`UX générique restante: ${forbidden}`);
for(const column of['No EDT','Client','Campagne / Communication','Type EDT','Requérant','Courriel du requérant','Date prévue','Date de complétion','Statut EDT','Rapport','Statut d’envoi','Date d’envoi'])assert.ok(source.includes(column),column);
for(const action of['Générer','Prévisualiser','Télécharger','Envoyer','Réessayer','Renvoyer','Voir le problème'])assert.ok(source.includes(action),action);
for(const operation of['listCompletedEdt','listEdtReports','loadEdtReportTracking','generateEdtReport','downloadEdtReport','requestEdtEmail','processEdtEmail'])assert.ok(service.includes(operation),operation);
assert.ok(service.includes("eq('statut','Complété')")&&service.includes("from('edt_reports')"));assert.ok(!service.includes("from('reports')"));assert.ok(source.includes('<UnifiedDataGrid')&&source.includes('sortRows')&&source.includes('window.confirm'));assert.ok(main.includes("lazy(() => import('./components/Module15Reports'))")&&main.includes("active === 'Rapports EDT'"));assert.ok(module14.includes('Rapports envoyés')&&module14.includes('Rapports à envoyer'));assert.ok(client.includes('module15_client_edt_reports_v130'));assert.ok(pdf.includes("await import('jspdf')")&&pdf.includes('requesterName'));assert.ok(!source.includes('Excel')&&!source.includes('xlsx'));
console.log('Module 15 simplifié : une vue Rapports EDT, grille métier, PDF, envoi, relance et isolation validés.');
