import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.TDM_PGLITE_MODULE || pathToFileURL(path.join(os.tmpdir(),'tdm-rpc-test-runtime/node_modules/@electric-sql/pglite/dist/index.js')).href);
const db=new PGlite();const records=[];
const dir='scripts/fixtures/targeted';
const schema=JSON.parse(fs.readFileSync('scripts/fixtures/targeted/schema.json'));
try {
await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
create table auth.users(id uuid,email text);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table storage.objects(bucket_id text,name text,owner_id text);
grant usage on schema public,auth to authenticated,anon;set check_function_bodies=false;`);
for(const table of ['utilisateurs','clients','infrastructures','suivi_des_edt','edt_phases','edt_supports','campagnes_maitres','campagne_visuels_formats','campagnes_visuels_sites_supports','communications_operationnelles_sites_supports','terrain_operations','support_photos','historique_des_campagnes','inspections_terrain','enjeux_terrain']) {
 const cols=schema.columns.filter(c=>c.schema==='public'&&c.table===table);assert(cols.length,table);
 await db.exec(`create table public.${table}(${cols.map(c=>'"'+c.name+'" '+c.type+(c.name==='id'?(c.type==='bigint'?' generated by default as identity primary key':c.type==='uuid'?' default gen_random_uuid() primary key':' primary key'):'')).join(',')});grant all on public.${table} to authenticated;`);
}
await db.exec(`create unique index operation_reference on terrain_operations(reference);create unique index support_path on support_photos(support_id,storage_path);create unique index phase_support on edt_supports(phase_id,support_id);
create function refresh_edt_enterprise(bigint) returns void language sql as $$select$$;
insert into clients(id) values(1),(2);
insert into utilisateurs(id,auth_user_id,role,statut,client_id,courriel) values(1,'91000000-0000-4000-8000-000000092941','Installateur','Actif',2,'fixture@example.invalid');
select set_config('request.jwt.claim.sub','91000000-0000-4000-8000-000000092941',false);
insert into infrastructures(id,support_id,client_id,format_affichage) values(1,'HA-87719 -02',2,'20 × 28 Portrait'),(2,'CLIENT-B',1,'20 x 28');
insert into campagnes_maitres(id,client_id,nom_campagne,business_context,publiee_terrain,statut) values(7,2,'Marketing','marketing',true,'Active'),(8,2,'Communication','operational_communication',true,'Active'),(9,1,'Other','marketing',true,'Active');
insert into suivi_des_edt(id,client_id,campagne_id,no_edt) values(64,2,7,'EDT-64'),(65,1,9,'EDT-B'),(66,2,7,'EDT-66');
insert into edt_phases(id,edt_id,client_id,phase_type) values(114,64,2,'installation'),(115,65,1,'installation'),(116,66,2,'installation');
insert into campagne_visuels_formats(id,campagne_id,client_id,nom_visuel,format_support,actif,is_out_of_frame,edt_phase_id) values(34,7,2,'Visible','20x28 portrait',true,false,null),(35,7,2,'Linked','20 x 28',true,false,114),(89,7,2,'Wrong','26 x 20',true,false,null),(90,7,2,'Wrong2','24.25 x 18',true,false,null),(100,8,2,'Outside','99 x 99',true,true,null),(101,8,2,'Communication','20x28',true,false,null),(102,9,1,'Other client','20x28',true,false,null);`);
for(const f of JSON.parse(fs.readFileSync(dir+'/helpers.json')))await db.exec(f.definition);
await db.exec(fs.readFileSync('supabase/migrations/20260914103135_terrain_visual_driven_installation_p0.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/20260914103142_admin_visual_edt_assignment_p0.sql','utf8'));
await db.exec(`create table photos(id bigint);create table inventory_movements(id bigint);
alter table historique_des_campagnes add column client_id bigint;
create table role_ui_permissions(role text,visible_tables text[],capabilities jsonb);
insert into role_ui_permissions values('Administrateur',array['*'],'{}'),('Installateur',array['*'],'{}'),('Client',array['Campagnes maîtres','Photos','Communications opérationnelles'],'{}'),('Client-Admin',array['Campagnes maîtres','Photos','Communications opérationnelles'],'{}');
create function portal_view_allowed(text,boolean default false) returns boolean language sql as $$select auth.uid() is not null$$;
alter table campagne_visuels_formats add column if not exists edt_phase_id bigint;
grant usage on schema storage to authenticated;grant select on storage.objects,role_ui_permissions to authenticated;
grant usage on all sequences in schema public to authenticated;
alter table campagne_visuels_formats alter column updated_at set default now();
`);
const current=JSON.parse(fs.readFileSync('docs/targeted-improvements/functions-before.json'));
for(const f of current)await db.exec(f.definition);
await db.exec(fs.readFileSync('supabase/migrations/20260915023244_targeted_terrain_visual_photo_improvements.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/20260915024026_client_photo_inventory_canonical_scope.sql','utf8'));
const pass=name=>{records.push({name,result:'PASS'});console.log(name+' PASS');};
assert.equal((await db.query('select count(*)::int n from visual_edt_associations')).rows[0].n,1);pass('Legacy EDT link backfilled');
await db.exec("update utilisateurs set role='Administrateur';set role authenticated");
const links=async rows=>(await db.query('select save_visual_edt_associations(35,$1::jsonb) value',[JSON.stringify(rows)])).rows[0].value;
assert.equal((await links([{phase_id:114,date_debut:'2026-01-01',date_fin:'2026-01-31'},{phase_id:116,date_debut:'2026-02-01',date_fin:'2026-02-28'}])).ok,true);
assert.equal((await db.query('select count(*)::int n from visual_edt_associations where visual_id=35')).rows[0].n,2);pass('Multiple EDT links with distinct dates');
await assert.rejects(links([{phase_id:115}]),e=>e.code==='42501');
await assert.rejects(links([{phase_id:114,date_debut:'2026-02-01',date_fin:'2026-01-01'}]),e=>e.code==='23514');
assert.equal((await db.query('select count(*)::int n from visual_edt_associations where visual_id=35')).rows[0].n,2);pass('Cross-client links and reversed dates rejected atomically');
await links([{phase_id:116,date_debut:'2026-03-01',date_fin:'2026-04-01'}]);
assert.equal((await db.query('select count(*)::int n from visual_edt_associations where visual_id=35')).rows[0].n,1);
await links([]);assert.equal((await db.query('select count(*)::int n from visual_edt_associations where visual_id=35')).rows[0].n,0);pass('Modify and remove associations, including zero EDT');
await links([{phase_id:114}]);
const upload=async path=>{await db.exec('reset role');await db.query('insert into storage.objects values($1,$2,$3)',['terrain-photos',path,'91000000-0000-4000-8000-000000092941']);await db.exec('set role authenticated');};
await db.exec("reset role;update utilisateurs set role='Installateur';set role authenticated");
const write=async(visual,path,phase,without)=>(await db.query(`select finaliser_installation_terrain_v1344('HA-87719 -02',$1,'test.png',$2,null,null,null,$2,$3,$4) value`,[visual,path,phase,without])).rows[0].value;
for(const [id,phase,without] of [[35,114,false],[35,null,true],[101,null,true],[100,null,true]]){
 const path=`supports/HA-87719 -02/target-${id}-${without}.png`;await upload(path);
 const result=await write(id,path,phase,without);assert.equal(result.ok,true,JSON.stringify(result));
 assert.equal(result.edt_id,without?null:64);
 const photo=(await db.query('select metadata,edt_id from support_photos where id=$1',[result.photo_id])).rows[0];
 assert.equal(photo.metadata.installation_sans_edt,without);assert.equal(photo.edt_id,without?null:'64');
 const retry=await write(id,path,phase,without);assert.equal(retry.ok,true);
}
pass('Normal installation, no-EDT linked visual, communication and out-of-frame; private metadata and idempotency');
await assert.rejects(write(35,'supports/HA-87719 -02/invalid.png',null,false),e=>e.code==='23502');
await assert.rejects(write(35,'supports/HA-87719 -02/invalid.png',114,true),e=>e.code==='23502');
const wrong='supports/HA-87719 -02/wrong.png';await upload(wrong);assert.equal((await write(89,wrong,null,true)).ok,false);pass('Explicit mode, required EDT and format enforced');
await db.exec('reset role');
for(const f of JSON.parse(fs.readFileSync(dir+'/functions-before.json')).filter(f=>f.proname==='finaliser_intervention_terrain_v01273'))await db.exec(f.definition);
await db.exec(fs.readFileSync('supabase/migrations/20260914103706_terrain_private_photo_metadata_p0.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/20260914112600_terrain_optional_removal_and_replacement_p0.sql','utf8'));
// New wrapper executed against the real existing intervention writer.
await db.exec('set role authenticated');
for(const action of ['inspection','enjeu','retrait']){
 const path=`supports/HA-87719 -02/target-${action}.png`;await upload(path);
 const result=(await db.query(`select finaliser_intervention_terrain_v1342('HA-87719 -02',null,$1,'Vitre','Description','test.png',$2,null,null,$2) value`,[action,path])).rows[0].value;
 assert.equal(result.ok,true,JSON.stringify(result));assert.equal(result.edt_id,null);
}
pass('Issue without EDT/phase, inspection and removal use existing writer');
await db.exec("reset role;update utilisateurs set role='Client-Admin';set role authenticated");
await assert.rejects(links([{phase_id:114}]),e=>e.code==='42501');
const counts=(await db.query("select canonical_campaign_counts('marketing') value")).rows[0].value;
assert.equal(counts.total,1);assert.equal(counts.active,1);pass('Canonical EXO campaign count is scoped');
await db.exec("reset role;update utilisateurs set role='Client';set role authenticated");
assert.deepEqual((await db.query("select canonical_campaign_counts('marketing') value")).rows[0].value,counts);pass('Client and Client-Admin counts match');
await db.exec("reset role;update utilisateurs set role='Administrateur',client_id=null;set role authenticated");
assert.equal((await db.query("select canonical_campaign_counts('marketing') value")).rows[0].value.total,2);pass('Admin canonical count includes all authorized clients');
await db.exec("reset role;select set_config('request.jwt.claim.sub','',false);set role anon");
await assert.rejects(db.query("select canonical_campaign_counts('marketing')"),e=>e.code==='42501');pass('Anonymous aggregate denied');
fs.mkdirSync('docs/targeted-improvements',{recursive:true});fs.writeFileSync('docs/targeted-improvements/local-sql-tests.json',JSON.stringify(records,null,2));
}finally{await db.close();}
