import fs from 'node:fs';import assert from 'node:assert/strict';import {createServer} from 'vite';import {targetedAccess} from './targeted_remote_access.mjs';import {existingSession} from './targeted_existing_session.mjs';import {managementQuery} from './targeted_management_access.mjs';
const dir='.cache/visual-terrain-stock',ids=JSON.parse(fs.readFileSync(`${dir}/requested-review-cleanup-selection.json`)).ids,before=JSON.parse(fs.readFileSync(`${dir}/original-204-contexts.json`)),progress=new Map();assert.equal(ids.length,204);
for(const p of ['reanalysis-204-progress',...[0,1,2,3].map(n=>'reanalysis-shard-'+n)])if(fs.existsSync(`${dir}/${p}.json`))for(const row of JSON.parse(fs.readFileSync(`${dir}/${p}.json`)))progress.set(row.id,row);
assert.equal(progress.size,204);assert([...progress.values()].every(r=>r.ok));
const access=await targetedAccess(),actor=await existingSession(access,1);process.env.VITE_SUPABASE_URL=actor.client.supabaseUrl;process.env.VITE_SUPABASE_PUBLISHABLE_KEY=actor.client.supabaseKey;assert.equal(JSON.parse(Buffer.from(actor.client.supabaseKey.split('.')[1],'base64url')).role,'anon');
const vite=await createServer({server:{middlewareMode:true},appType:'custom',logLevel:'silent'});let app;
try{
 app=(await vite.ssrLoadModule('/src/lib/supabaseClient.js')).supabase;assert.ifError((await app.auth.setSession(actor.session)).error);const service=await vite.ssrLoadModule('/src/services/photoImportContextService.js'),catalog=await service.loadPhotoImportCatalog();
 let rows=await actor.client.from('support_photos').select('*').in('id',ids).order('id');assert.ifError(rows.error);assert.equal(rows.data.length,204);
 if(process.argv.includes('--refresh-context')){let count=0;for(const photo of rows.data){assert(!photo.import_finalized_at);const context=service.importContextForPhoto(photo,catalog,photo.import_context.manual);assert.deepEqual(context.manual,photo.import_context.manual);for(let attempt=0;;attempt++){try{await service.savePhotoImportContext(photo.id,context);break;}catch(error){if(attempt>=2||!/fetch failed|network|socket/i.test(error.message))throw error;await new Promise(r=>setTimeout(r,500));}}if(++count%50===0)console.log(`Contexte actualisé ${count}/204, aucun mouvement créé`);}rows=await actor.client.from('support_photos').select('*').in('id',ids).order('id');assert.ifError(rows.error);}
 for(const p of rows.data){const original=before.find(x=>x.id===p.id);assert(original);for(const key of ['storage_bucket','storage_path','source','import_finalized_at','movement_history_id','est_principale','is_current_visual','support_id','campagne_id','visuel_id','edt_id'])assert.deepEqual(p[key],original[key],`${p.id}:${key}`);assert.deepEqual(p.import_context.manual||{},original.import_context?.manual||{});}
 const [storage]=await managementQuery('select count(*) as originals from support_photos p join storage.objects o on o.bucket_id=p.storage_bucket and o.name=p.storage_path where p.id=any($1::bigint[])',[ids]);assert.equal(storage.originals,204);
 const fields=['support','date','type','edt','phase','campaign','visual'],confirmed=Object.fromEntries(fields.map(k=>[k,rows.data.filter(p=>['AUTO_CONFIRMED','MANUAL_CONFIRMED'].includes(p.import_context.recognition.states[k])).length]));
 const report={at:new Date().toISOString(),result:'PASS',total:204,originalsPreserved:204,rowsPreserved:204,allAnalyzed:true,manualChoicesPreserved:true,newMovements:0,newFinalizations:0,confirmed,supportCandidates:rows.data.filter(p=>p.import_context.recognition.candidates.supportDetails?.length).length,ready:rows.data.filter(p=>p.import_context.recognition.ready).length,activeReferenceVisuals:catalog.visuals.filter(v=>v.reference_assets?.some(a=>!a.archived)).length,limitations:['Automatic visual identification requires generic references.','Unknown or absent EDT records are never invented.']};
 fs.writeFileSync(`${dir}/reanalysis-204-final.json`,JSON.stringify(report,null,2));fs.writeFileSync(`${dir}/reanalysis-204-progress.json`,JSON.stringify([...progress.values()],null,2));console.log(JSON.stringify(report));
}finally{await app?.auth.signOut({scope:'local'});await actor.client.auth.signOut({scope:'local'});await vite.close();}
