import assert from 'node:assert/strict';
import {getUserViewPreview,setUserViewPreview,previewAwareFetch,userViewSession} from '../src/lib/userViewPreview.js';
const requests=[];globalThis.window=new EventTarget();
globalThis.fetch=async(input,init={})=>{requests.push({url:String(input),method:init.method||'GET',headers:Object.fromEntries(new Headers(init.headers)),body:init.body});return new Response('true',{status:200})};
setUserViewPreview({id:25,role:'Client-Admin',auth_user_id:'target',courriel:'target@example.invalid',_preview_account_activated:false});
const adminSession={access_token:'admin-test-token',user:{id:'admin',user_metadata:{account_activated:true}}};
assert.equal(userViewSession(adminSession).user.id,'target');
assert.equal(userViewSession(adminSession).user.user_metadata.account_activated,false);
assert.equal(userViewSession(adminSession).access_token,adminSession.access_token);
await previewAwareFetch('https://fixture.invalid/rest/v1/infrastructures',{headers:{Authorization:'Bearer fixture'}});
assert.equal(requests[0].headers['x-tos-preview-user'],'25');
assert.equal(requests[0].headers.authorization,'Bearer fixture');
for(const path of ['/functions/v1/send-report','/auth/v1/logout','/storage/v1/object/bucket/name'])await assert.rejects(previewAwareFetch('https://fixture.invalid'+path,{method:'POST'}),/écritures/);
assert.equal(requests.length,1,'No side-effect request leaves the preview');
await previewAwareFetch('https://fixture.invalid/storage/v1/object/sign/support-photos/name.jpg',{method:'POST',headers:{Authorization:'Bearer fixture'}});
assert.equal(requests[1].url,'https://fixture.invalid/rest/v1/rpc/portal_preview_storage_read');
assert.deepEqual(JSON.parse(requests[1].body),{p_bucket:'support-photos',p_name:'name.jpg'});
assert.equal(requests[1].headers['x-tos-preview-user'],'25');
setUserViewPreview(null);assert.equal(getUserViewPreview(),null);
await previewAwareFetch('https://fixture.invalid/rest/v1/infrastructures');
assert.equal(requests.at(-1).headers['x-tos-preview-user'],undefined);
console.log('Real-view preview transport: target reads, side effects blocked, storage scope, return to Admin PASS');
