import assert from'node:assert/strict';import fs from'node:fs';
import{classifyPhotoContext,DEFAULT_INSPECTION_NOTICE}from'../src/lib/photoWorkflow.js';
import{isVisualFormatCompatible}from'../src/lib/visualCompatibility.js';
let checks=0;const eq=(a,b,m)=>{assert.deepEqual(a,b,m);checks++};
eq(classifyPhotoContext({issueId:9}).type,'enjeu');eq(classifyPhotoContext({activeInstallationEdt:{id:1}}).type,'installation');eq(classifyPhotoContext({activeRemovalEdt:{id:2}}).type,'retrait');eq(classifyPhotoContext({inspectionId:3}).type,'inspection');eq(classifyPhotoContext({activeCampaigns:[{id:4}]}).campaignId,4);const fallback=classifyPhotoContext({activeCampaigns:[{},{}],activeInstallationEdts:[],activeRemovalEdts:[]});eq(fallback.type,'inspection');eq(fallback.reason,'no_active_business_context');eq(fallback.notice,DEFAULT_INSPECTION_NOTICE);eq(fallback.campaignId,null);eq(fallback.edtId,null);
eq(isVisualFormatCompatible({format_support:'10 x 20',is_out_of_frame:false},{format_affichage:'10X20'}),true);eq(isVisualFormatCompatible({format_support:'10 x 20',is_out_of_frame:false},{format_affichage:'20X30'}),false);eq(isVisualFormatCompatible({format_support:'10 x 20',is_out_of_frame:true},{format_affichage:'20X30'}),true);
const campaignUi=fs.readFileSync('src/components/CampaignsPanel.jsx','utf8'),visualUi=fs.readFileSync('src/components/CampaignVisualManager.jsx','utf8'),migration=fs.readFileSync('supabase/V1_1_1_URGENT_FIXES.sql','utf8'),verifier=fs.readFileSync('supabase/VERIFIER_V1_1_1_URGENT_FIXES.sql','utf8');for(const token of['Modifier','Supprimer','window.confirm','disabled={busy}'])assert.ok(campaignUi.includes(token)),checks++;for(const token of['Hors-Cadre','is_out_of_frame'])assert.ok(visualUi.includes(token)),checks++;assert.match(migration,/is_out_of_frame boolean not null default false/i);checks++;assert.doesNotMatch(migration,/drop\s+(table|column)|truncate/i);checks++;for(const statement of verifier.split(';').map(x=>x.trim()).filter(Boolean))assert.match(statement,/^select\b/i),checks++;
const visible=[...fs.readdirSync('src/components').filter(x=>x.endsWith('.jsx')).map(x=>'src/components/'+x),'src/main.jsx'];for(const file of visible){const source=fs.readFileSync(file,'utf8');for(const forbidden of['Erreur Supabase','ID Supabase','Supabase Storage','Supabase configuré','Recharger depuis Supabase'])assert.ok(!source.includes(forbidden),`Terme technique visible: ${file}`),checks++;}
console.log(`V1.1.1 : ${checks} contrôles réussis.`);
