import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';
import{CANONICAL_APP_ROLES,EMPTY_PERMISSION_CONFIG,normalizePermissionConfig,permissionConfigChanged,permissionContradictions,resolvePermissionSimulation,stablePermissionConfig}from'../src/lib/fieldCatalogPermissionDraft.js';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8');let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++};
const expected=['src/lib/fieldCatalogPermissionDraft.js','src/hooks/useFieldPermissionDraft.js','src/services/fieldCatalogPermissionWriteService.js','src/components/field-catalog/FieldCatalogPermissionTab.jsx','src/features/v13/field-catalog-permission.css','supabase/V0_13_1_A6_PERMISSION_DRAFT.sql','supabase/VERIFIER_V0_13_1_A6_PERMISSION_DRAFT.sql','src/features/v13/field-contracts/A6-PERMISSIONCONFIG-FINAL-IMPLEMENTATION.md'];for(const f of expected)ok(fs.existsSync(path.join(root,f)),f);
assert.deepEqual(normalizePermissionConfig({}).normalized,EMPTY_PERMISSION_CONFIG);checks++;ok(!normalizePermissionConfig({extra:true}).valid,'unknown property');ok(!normalizePermissionConfig({priorityStrategy:'allow-wins'}).valid,'strategy');ok(!normalizePermissionConfig({conservativeDeny:false}).valid,'conservative');
const config={generalRule:{visible:true,editable:true},roleRules:{Client:{visible:false,editable:null}},priorityStrategy:'deny-wins',conservativeDeny:true};const normalized=normalizePermissionConfig(config);ok(normalized.valid,'valid');ok(stablePermissionConfig(config)===stablePermissionConfig(normalized.normalized),'stable');ok(!permissionConfigChanged(config,normalized.normalized),'no change');
for(const role of CANONICAL_APP_ROLES)ok(typeof role==='string','canonical role');
let r=resolvePermissionSimulation({config,role:'Client',capability:'visible'});assert.equal(r.allowed,false);checks++;ok(r.reasonCodes.includes('role_deny_dominates'),'specific deny');r=resolvePermissionSimulation({config,role:'Administrateur',capability:'visible'});assert.equal(r.allowed,true);checks++;r=resolvePermissionSimulation({config:{generalRule:{visible:false},roleRules:{Client:{visible:true}}},role:'Client'});assert.equal(r.allowed,false);checks++;ok(permissionContradictions({generalRule:{visible:false},roleRules:{Client:{visible:true}}}).length===1,'conflict');
for(const options of[{role:'Inconnu'},{role:'Client',protectedField:true},{role:'Client',serverAllowed:false},{role:'Client',config:{bad:true}}]){r=resolvePermissionSimulation({config:options.config??config,capability:'editable',...options});assert.equal(r.allowed,false);checks++;}
const sql=read('supabase/V0_13_1_A6_PERMISSION_DRAFT.sql').toLowerCase();for(const token of['security definer','set search_path=pg_catalog','owner to postgres','from public,anon','to authenticated','for update','stale_draft','no_change','permission_draft_saved','relation_field_config_audit','configuration_status=\'draft\''])ok(sql.includes(token),token);for(const forbidden of['truncate ','create role','alter policy','create policy','drop table','execute format(','execute immediate'])ok(!sql.includes(forbidden),forbidden);ok(!/\b(update|insert into|delete from)\s+public\.(?!relation_fields\b|relation_field_config_audit\b)/.test(sql),'write whitelist');
const service=read('src/services/fieldCatalogPermissionWriteService.js');ok(service.includes("supabase.rpc('save_relation_field_permission_draft_v0131a6'"),'rpc only');for(const bad of['.from(','.update(','.insert(','.upsert(','retry'])ok(!service.includes(bad),bad);
const ui=read('src/components/field-catalog/FieldCatalogPermissionTab.jsx');for(const token of['Brouillon sans effet immédiat','politiques RLS','Permissions','deny-wins','Enregistrer le brouillon','Rôle inconnu','Prévisualisation administrative fictive'])ok(ui.includes(token),token);for(const bad of['Activer','Publier','Déployer','Synchroniser'])ok(!ui.includes(bad),bad);
const consumers=['src/main.jsx','src/components/RoleVisibilityAdmin.jsx','src/services/roleVisibilityService.js','src/components/EditableField.jsx','src/services/universalEditorService.js','src/components/TerrainApp.jsx','src/components/Support360Panel.jsx','src/components/RelationsStudio.jsx','src/services/relationService.js'];for(const f of consumers)if(fs.existsSync(path.join(root,f))){const source=read(f);ok(!source.includes('resolvePermissionSimulation')&&!source.includes('PermissionConfig'),`non-consumption ${f}`);}
console.log(`Phase 13.1-A6 : ${checks} contrôles des permissions déclaratives réussis.`);
