// Real React/DOM in Edge; fixtures replace service boundaries. No production client or network.
import {build} from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import http from 'node:http';
import {spawn,execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
const out='docs/stabilization-local';fs.mkdirSync(out,{recursive:true});
const baseline=process.argv.includes('--baseline');
const mocks={
 dashboardService:`export const DASHBOARD_TIMEOUT_MS=4500;export async function loadDashboardSummary(){const f=window.fixture;return {version:1,identity:{user_id:'fixture-'+f.client,role:f.role,client_id:f.client,client_name:f.client===2?'EXO':'Client B'},permission:{visible_tables:f.permissions},kpis:{},sections:Object.fromEntries(['supports','campaigns','photos'].map(section=>[section,{total:75}]))}}`,
 clientAccessService:`export async function getClientPortalIdentity(){const f=window.fixture;return {id:f.client,organization_id:f.client,client_id:f.client,role:f.role,client_name:f.client===2?'EXO':'Client B'}} export async function getCurrentUserVisibleViews(){return {visible_tables:window.fixture.permissions}}`,
 clientPortalService:`export async function listClientPortalSection(section,args={}){const f=window.fixture,client=f.client,fail=f.fail,delay=f.delay;f.calls.push({section,...args,client});await new Promise(r=>setTimeout(r,delay));if(fail)throw Error('Erreur réseau simulée');return {rows:[{id:client,support_id:'SUP-'+client,site:client===2?'EXO':'Client B',nom_campagne:section==='campaigns'?'Campagne fixture':undefined}],total:75,page:args.page||1,page_size:args.pageSize||25}} export async function listAllClientPortalSection(section,args){return (await listClientPortalSection(section,args)).rows} export const listClientPortalSupportContext=listClientPortalSection;export async function createMultiSupportClientRequest(){window.fixture.mutations++;if(window.fixture.fail)throw Error('fixture')}`,
 userProvisioningService:`export async function listManagedUsers(){return [{id:1,courriel:'test@example.test',nom:'Fixture',role:'Installateur',lifecycle_status:'Invitation envoyée'}]} export async function manageUser(){window.fixture.mutations++;await new Promise(r=>setTimeout(r,100));if(window.fixture.fail)throw Error('Erreur simulée');return {message:'Invitation renvoyée'}} export const inviteRealUser=manageUser;export const updateManagedUser=manageUser;`,
 supabaseClient:`export const supabaseConfigured=true;export const supabase={auth:{verifyOtp:async()=>{window.fixture.mutations++;return {error:{code:'otp_expired'}}}}};`,
};
const bundle=await build({entryPoints:['scripts/stabilization-browser-entry.jsx'],bundle:true,write:false,loader:{'.css':'empty'},format:'iife',define:{'process.env.NODE_ENV':'"development"'},plugins:[{name:'offline-fixtures',setup(b){
 if(baseline)b.onLoad({filter:/[\\/](ClientPortal|ClientBusinessGrid|UnifiedDataGrid)\.jsx$/},a=>({contents:execFileSync('git',['show',`HEAD:${path.relative(process.cwd(),a.path).replaceAll('\\','/')}`],{encoding:'utf8'}),loader:'jsx'}));
 b.onResolve({filter:/\/(dashboardService|clientAccessService|clientPortalService|userProvisioningService|supabaseClient)(\.js)?$/},a=>({path:a.path.split('/').pop().replace(/\.js$/,''),namespace:'fixture'}));
 b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:mocks[a.path],loader:'js'}));
 // Map, 360 and export implementations are outside this targeted runtime suite.
 b.onResolve({filter:/\/(InteractiveMap|Support360Panel|ExportsCenter)$/},a=>({path:a.path,namespace:'stub'}));
 b.onLoad({filter:/.*/,namespace:'stub'},()=>({contents:'export default function Stub(){return null}',loader:'js'}));
 b.onResolve({filter:/\/mapService$/},a=>({path:a.path,namespace:'map'}));b.onLoad({filter:/.*/,namespace:'map'},()=>({contents:'export const prepareMapInfrastructureRows=()=>({points:[]})'}));
}}]});
const html='<!doctype html><meta charset="utf-8"><div id="root"></div><script src="/bundle.js"></script>';
const server=http.createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/bundle.js'?'text/javascript':'text/html');res.end(req.url==='/bundle.js'?bundle.outputFiles[0].contents:html)});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'tos-stabilization-edge-'));
const edge=process.env.TOS_TEST_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
const child=spawn(edge,['--headless=new','--disable-gpu','--no-first-run','--disable-background-networking','--disable-component-update','--disable-sync','--remote-debugging-port=0',`--user-data-dir=${temp}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
let socket;const results=[],errors=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
try{
 let port;for(let n=0;n<100;n++){try{port=fs.readFileSync(path.join(temp,'DevToolsActivePort'),'utf8').split('\n')[0];break}catch{}await sleep(100)}if(!port)throw Error('Edge debugging unavailable');
 const targets=await (await fetch(`http://127.0.0.1:${port}/json`)).json();socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>socket.addEventListener('open',r,{once:true}));
 let sequence=0;const pending=new Map();socket.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result)}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text+': '+m.params.exceptionDetails.exception?.description);if(m.method==='Fetch.requestPaused'){const url=m.params.request.url;send(url.startsWith(origin)?'Fetch.continueRequest':'Fetch.failRequest',url.startsWith(origin)?{requestId:m.params.requestId}:{requestId:m.params.requestId,errorReason:'BlockedByClient'}).catch(()=>{})}});
 function send(method,params={}){return new Promise((resolve,reject)=>{const id=++sequence;const timer=setTimeout(()=>reject(Error('CDP timeout '+method+' '+JSON.stringify(params))),20000);pending.set(id,{resolve:v=>{clearTimeout(timer);resolve(v)},reject:e=>{clearTimeout(timer);reject(e)}});socket.send(JSON.stringify({id,method,params}))})}
 async function evaluate(expression){const wrapped=`(()=>{const value=(0,eval)(${JSON.stringify(expression)});return value instanceof Node?true:value})()`;const r=await send('Runtime.evaluate',{expression:wrapped,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
 async function waitFor(expression){for(let n=0;n<150;n++){if(await evaluate(expression))return;await sleep(50)}throw Error('Timeout: '+expression)}
 async function click(text,selector='button'){await evaluate(`(()=>{const b=[...document.querySelectorAll(${JSON.stringify(selector)})].find(b=>b.textContent.trim()===${JSON.stringify(text)});if(!b)throw Error('Missing '+${JSON.stringify(text)});b.click()})()`);await sleep(80)}
 async function test(name,fn){await fn();results.push({name,result:'PASS_LOCAL_BROWSER'});console.log('PASS '+name)}
 await send('Runtime.enable');await send('Fetch.enable',{patterns:[{urlPattern:'*'}]});await send('Page.navigate',{url:origin});await waitFor(`document.querySelector('aside')&&document.body.textContent.includes('EXO')&&!document.querySelector('.client-loading')`);
 await test('Infrastructures: 30 seconds idle, same DOM, no fetch loop',async()=>{await click('Infrastructures','aside button');await waitFor(`document.querySelector('tbody')?.textContent.includes('EXO')`);await evaluate('window.savedGrid=document.querySelector(".client-business-grid");window.savedCalls=fixture.calls.length');await sleep(30000);assert.equal(await evaluate('fixture.calls.length===savedCalls&&savedGrid===document.querySelector(".client-business-grid")'),true)});
 await test('Refresh: data stays mounted, double click, page preserved, error and retry',async()=>{await click('Suivante');await waitFor('fixture.calls.at(-1).page===2');await evaluate('fixture.delay=300;window.savedGrid=document.querySelector(".client-business-grid")');await click('Actualiser');assert.equal(await evaluate('savedGrid===document.querySelector(".client-business-grid")&&document.querySelector("tbody").textContent.includes("EXO")'),true);await waitFor(`document.querySelector('.client-grid-actions button')?.textContent==='Actualiser'`);assert.equal(await evaluate('fixture.calls.at(-1).page'),2);const beforeBurst=await evaluate('fixture.calls.length');await evaluate(`(()=>{const b=document.querySelector('.client-grid-actions button');for(let i=0;i<10;i++)b.click()})()`);await sleep(400);assert.equal(await evaluate('fixture.calls.length'),beforeBurst+1,'Client burst starts one refresh');await evaluate('fixture.fail=true');await click('Actualiser');await waitFor('document.body.textContent.includes("Erreur réseau simulée")');await evaluate('fixture.fail=false');await click('Actualiser');await waitFor(`!document.body.textContent.includes('Erreur réseau simulée')`)});
 await test('Search survives refresh and newer response wins',async()=>{await evaluate(`(()=>{const input=document.querySelector('.searchbar input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'EXO');input.dispatchEvent(new Event('input',{bubbles:true}))})()`);await waitFor(`fixture.calls.at(-1).filters?.search==='EXO'`);await sleep(400);await click('Actualiser');await sleep(400);assert.equal(await evaluate(`document.querySelector('.searchbar input').value`),'EXO');await evaluate('fixture.delay=700');await click('Actualiser');await click('Campagnes','aside button');await evaluate('fixture.delay=15');await sleep(900);assert.equal(await evaluate('document.querySelector("tbody").textContent.includes("Campagne fixture")'),true)});
 await test('Campagnes: 30 seconds idle, no remount or fetch',async()=>{await evaluate('window.savedGrid=document.querySelector(".client-business-grid");window.savedCalls=fixture.calls.length');await sleep(30000);assert.equal(await evaluate('fixture.calls.length===savedCalls&&savedGrid===document.querySelector(".client-business-grid")'),true)});
 await test('Repeated Sommaire / Infrastructure / Campaign navigation',async()=>{for(let i=0;i<3;i++){await click('Sommaire','aside button');await click('Infrastructures','aside button');await sleep(750);await click('Campagnes','aside button');await sleep(750)}await click('Infrastructures','aside button');await sleep(750)});
 await test('Client B scope transition clears EXO and forbidden view',async()=>{await evaluate(`fixture.client=3;fixture.role='Client';fixture.permissions=['Infrastructures'];window.mount()`);await waitFor(`document.querySelector('aside')&&!document.querySelector('.client-loading')`);await click('Infrastructures','aside button');await waitFor(`document.querySelector('tbody')?.textContent.includes('Client B')`);assert.equal(await evaluate(`document.body.textContent.includes('EXO')||[...document.querySelectorAll('aside button')].some(b=>b.textContent==='Campagnes')`),false)});
 await test('Shared grid without optional selection renders nonempty rows',async()=>{await evaluate(`window.mount('grid')`);await waitFor(`document.querySelector('tbody')?.textContent==='EXO'`)});
 await test('Admin preview uses real portal and forbids configured columns',async()=>{await evaluate(`window.mount('portal',{target_user:{id:9,client_id:2,role:'Client-Admin'},visible_tables:['Infrastructures'],visible_columns:{Infrastructures:['support_id']},sections:{supports:{rows:[{id:1,support_id:'SUP-2',site:'FORBIDDEN_COLUMN'}],total:1}}})`);await waitFor(`document.querySelector('aside')`);await click('Infrastructures','aside button');await waitFor(`document.querySelector('tbody')?.textContent.includes('SUP-2')`);assert.equal(await evaluate(`document.body.textContent.includes('FORBIDDEN_COLUMN')`),false);await click('Modifier la grille');assert.equal(await evaluate(`document.querySelector('[role="dialog"]').textContent.includes('site')`),false)});
 await test('Five operational alert buttons navigate to existing modules',async()=>{await evaluate(`window.mount('alerts')`);await waitFor(`document.querySelector('.command-alerts')`);const targets=['Suivi des EDT','Campagnes maîtres','Photos et inventaire','Enjeux des cadres et supports','Rapports finaux'];for(let i=0;i<targets.length;i++){await evaluate(`document.querySelectorAll('.command-alerts button')[${i}].click()`);assert.equal(await evaluate('fixture.target'),targets[i])}});
 await test('Safe Links GET consumes nothing; explicit double click calls once',async()=>{await send('Page.navigate',{url:origin+'/?token_hash=abcdefghijklmnopqrstuvwx&type=invite'});await waitFor('Boolean(window.mount)');await evaluate(`fixture.mutations=0;window.mount('invitation')`);await waitFor(`document.querySelector('.activation-submit')`);await sleep(500);assert.equal(await evaluate('fixture.mutations'),0);await evaluate(`document.querySelector('.activation-submit').click();document.querySelector('.activation-submit').click()`);await waitFor('fixture.mutations===1');assert.equal(await evaluate('fixture.mutations'),1)});
 await test('User resend double click guarded; success remains visible',async()=>{await evaluate(`fixture.mutations=0;window.mount('users')`);await waitFor(`document.body.textContent.includes('test@example.test')`);await evaluate(`(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='Renvoyer');b.click();b.click()})()`);await sleep(300);assert.equal(await evaluate('fixture.mutations'),1);assert.equal(await evaluate(`document.body.textContent.includes('Invitation renvoyée')`),true)});
 assert.deepEqual(errors,[],'Unexpected browser exceptions');
}catch(e){results.push({name:'suite',result:'FAIL',error:e.stack});process.exitCode=1;console.error(e)}finally{fs.writeFileSync(`${out}/${baseline?'baseline-browser-results':'browser-results'}.json`,JSON.stringify({baseline,results,errors,limits:'Service fixtures; no live RLS/Auth/exports/map/360 proof'},null,2));socket?.close();child.kill();server.close();}
