import assert from'node:assert/strict';
import fs from'node:fs';
import{resolveClientPortalViews}from'../src/lib/clientPortalViewRegistry.js';
const read=file=>fs.readFileSync(file,'utf8');
const portal=read('src/components/ClientPortal.jsx'),service=read('src/services/clientAccessService.js'),sql=read('supabase/V1_3_6_CLIENT_ROLE_VIEWS_USER_LINKING_PREPARED.sql');
const admin=resolveClientPortalViews(['Infrastructures','Campagnes et visuels','Rapports EDT']);
const client=resolveClientPortalViews(['Infrastructures','Rapports EDT']);
assert.deepEqual(admin.views.map(x=>x.id),['infrastructures','campaigns','reports'],'EXO Client-Admin');
assert.deepEqual(client.views.map(x=>x.id),['infrastructures','reports'],'EXO Client');
assert.ok(!client.views.some(x=>x.id==='campaigns'),'Campagnes retirée sans code');
assert.equal(resolveClientPortalViews([]).views.length,0,'aucune vue par défaut');
assert.deepEqual(resolveClientPortalViews(['Vue future']).unknown,['Vue future']);
assert.match(portal,/getCurrentUserVisibleViews/);
assert.match(portal,/Aucune vue n’est actuellement autorisée/);
assert.match(portal,/VIEW_NOT_IMPLEMENTED_FOR_CLIENT_PORTAL/);
assert.ok(!portal.includes("const sections="),'ancien routage fixe supprimé');
assert.match(service,/rpc\('current_user_visible_views_v136'\)/);
for(const marker of ['auth.uid()','public.role_ui_permissions','visible_tables','role=public.current_app_role()','revoke all on function public.current_user_visible_views_v136()from public,anon'])assert.ok(sql.includes(marker),marker);
assert.ok(!sql.includes('relation_fields.role_permissions'),'aucune seconde autorité');
console.log('V1.3.6 vues par rôle : EXO, navigation dynamique, retrait sans code, état vide et vue inconnue validés.');
