import assert from'node:assert/strict';import fs from'node:fs';
const read=file=>fs.readFileSync(file,'utf8'),migration=read('supabase/V1_2_1_CONSOLIDATE_CAMPAIGN_OPERATIONAL_TABLES.sql'),sqlCheck=read('supabase/VERIFIER_V1_2_1_CONSOLIDATE_CAMPAIGN_OPERATIONAL_TABLES_READ_ONLY.sql'),service=read('src/services/siteSupportBusinessService.js'),view=read('src/components/SiteSupportAssignmentsView.jsx'),main=read('src/main.jsx'),doc=read('docs/V1_2_1_CONSOLIDATION_MAPPING.md'),module14=read('src/services/module14Service.js'),module17Service=read('src/services/clientPortalService.js'),module17Sql=read('supabase/V1_2_0_MODULE_17_CLIENT_PORTAL_SECURITY_PREPARED.sql');

for(const token of['BEGIN;','LIKE public.campagnes_et_visuels INCLUDING ALL','LIKE public.communications_operationnelles INCLUDING ALL','legacy_id','historical_fingerprint',"'marketing'","'operational_communication'",'ON CONFLICT (id) DO NOTHING','COMMIT;'])assert.ok(migration.includes(token),token);
assert.doesNotMatch(migration,/\b(DROP|TRUNCATE|DELETE)\b/i);
assert.doesNotMatch(migration,/TO\s+authenticated\s+USING\s*\(\s*true\s*\)/i);
assert.match(migration,/REVOKE ALL ON TABLE public\.campagnes_visuels_sites_supports FROM PUBLIC,anon,authenticated/i);
assert.match(migration,/REVOKE ALL ON TABLE public\.communications_operationnelles_sites_supports FROM PUBLIC,anon,authenticated/i);
assert.match(migration,/current_app_role\(\) IN \('Administrateur','Coordonnateur'\)/);
assert.doesNotMatch(migration,/current_app_role\(\).*Client/i);
assert.doesNotMatch(migration,/FOR\s+(INSERT|UPDATE|DELETE|ALL)\b/i);

assert.match(sqlCheck,/^BEGIN READ ONLY;/);assert.match(sqlCheck,/ROLLBACK;\s*$/);const executableSql=sqlCheck.replace(/--.*$/gm,'').replace(/'(?:''|[^'])*'/g,"''");assert.doesNotMatch(executableSql,/\b(INSERT|UPDATE|DELETE|TRUNCATE|ALTER|CREATE|GRANT|REVOKE)\b/i);
for(const metric of['TABLE_PRESENCE','MISSING_HISTORICAL_COLUMNS','OLD_CAMPAIGN_ROWS','NEW_CAMPAIGN_ROWS','MISSING_CAMPAIGN_ROWS','EXTRA_CAMPAIGN_ROWS','MISMATCHED_CAMPAIGN_ROWS','CAMPAIGN_HASH_MISMATCHES','OLD_OPERATIONAL_ROWS','NEW_OPERATIONAL_ROWS','MISSING_OPERATIONAL_ROWS','EXTRA_OPERATIONAL_ROWS','MISMATCHED_OPERATIONAL_ROWS','OPERATIONAL_HASH_MISMATCHES','INVALID_CAMPAIGN_BUSINESS_CONTEXT','INVALID_OPERATIONAL_BUSINESS_CONTEXT','EXO_INFO_WRONG_CONTEXT','CAMPAIGN_JOIN_DUPLICATES','OPERATIONAL_JOIN_DUPLICATES','DANGEROUS_DIRECT_POLICIES','CROSS_CLIENT_STATIC_GUARD'])assert.ok(sqlCheck.includes(metric),metric);
for(const catalog of['information_schema.columns','information_schema.table_constraints','pg_catalog.pg_indexes','pg_catalog.pg_policies','information_schema.role_table_grants','has_table_privilege','aclexplode','relrowsecurity'])assert.ok(sqlCheck.includes(catalog),catalog);
assert.ok(!sqlCheck.includes("has_function_privilege('PUBLIC'"),'PUBLIC doit être contrôlé via les ACL, pas comme un rôle PostgreSQL');
for(const enrichment of['rows_with_site','rows_with_support','rows_with_infrastructure','fully_enriched_rows','partially_enriched_rows','unenrichable_rows','ORPHAN_INFRASTRUCTURES','ORPHAN_CAMPAIGNS'])assert.ok(sqlCheck.includes(enrichment),enrichment);

for(const rpc of['client_portal_identity_v120','client_can_access_campaign_v120','client_portal_list_v120'])assert.ok(module17Sql.includes(rpc),rpc);for(const guard of['auth.uid()','security definer set search_path=public,auth','from public,anon','to authenticated','client_scope_denied','cross_client_denied','client_published','client_visible'])assert.ok(module17Sql.toLowerCase().includes(guard.toLowerCase()),guard);assert.ok(module17Service.includes("rpc('client_portal_list_v120'"));
const canDirectRead=role=>['Administrateur','Coordonnateur'].includes(role);for(const clientRole of['Client','Client-Admin'])assert.equal(canDirectRead(clientRole),false);for(const internalRole of['Administrateur','Coordonnateur'])assert.equal(canDirectRead(internalRole),true);
const clientA={client_id:1},foreignRows=[{kind:'campagne B',client_id:2},{kind:'communication B',client_id:2},{kind:'site B',client_id:2},{kind:'support B',client_id:2},{kind:'visuel B',client_id:2}];assert.deepEqual(foreignRows.filter(row=>row.client_id===clientA.client_id),[],'cross_client_denied');

for(const table of['campagnes_visuels_sites_supports','communications_operationnelles_sites_supports'])assert.ok(service.includes(table),table);assert.ok(!service.includes("from('campagnes_supports')"));for(const token of['Modifier la grille','Recherche globale','Page visible','Sélection','Support / Fiche 360','Visuel','EDT','Photos','Historique','GridPagination','raw_data','legacy_id','business_context'])assert.ok(view.includes(token),token);for(const token of['12 colonnes SQL','16 colonnes SQL','CONSERVÉES OUI','Rollback applicatif'])assert.ok(doc.includes(token),token);
const adminLine=main.split('\n').find(line=>line.includes("? ['Administration'"));assert.equal((adminLine.match(/Campagnes et visuels par site et supports/g)||[]).length,1);assert.equal((adminLine.match(/Communications opérationnelles par site et supports/g)||[]).length,1);assert.ok(!adminLine.includes("'Communications opérationnelles',"));assert.ok(module14.includes('getMarketingAssignmentsBySiteAndSupport'));assert.ok(module14.includes('getOperationalCommunicationAssignmentsBySiteAndSupport'));console.log('V1.2.1: RLS interne, refus Client direct, contrôles cross-client et vérificateur SQL complet validés.');
