import assert from 'node:assert/strict';import fs from 'node:fs';import{offlineBrowser}from'./lib/offlineBrowser.mjs';const records=[];const pass=name=>records.push({name,result:'PASS'});
await offlineBrowser('scripts/fixtures/report-portal-entry.jsx',async({evaluate,waitFor,exceptions,consoleErrors})=>{
 await evaluate('mount(true)');await waitFor("Array.from(document.querySelectorAll('main button')).some(e=>e.innerText.includes('Télécharger le rapport'))");assert.equal(await evaluate("document.querySelector('.client-title h1').innerText"),'Rapports');pass('Authorized email deep link opens Reports');
 const click="Array.from(document.querySelectorAll('main button')).find(e=>e.innerText.includes('Télécharger le rapport')).click()";
 await evaluate('hold=true;'+click+';'+click);await waitFor("pending.length===1");assert.equal(await evaluate("calls.filter(c=>c.name==='downloadEdtReport').length"),1);pass('Double click starts one private report download');
 assert.equal(await evaluate("calls.find(c=>c.name==='downloadEdtReport').args[0].report_path"),'EDT-1/private.pdf');pass('Download uses report selected from authorized list');
 await evaluate('hold=false;pending.splice(0).forEach(r=>r())');await waitFor("!Array.from(document.querySelectorAll('main button')).some(e=>e.innerText.includes('Téléchargement…'))");pass('Download finishes and unlocks');
 await evaluate('deny=true;'+click);await waitFor("document.body.innerText.includes('Rapport privé inaccessible')");pass('Denied download shows recoverable error');
 await evaluate('deny=false;'+click);await waitFor("!document.body.innerText.includes('Rapport privé inaccessible')");pass('Download retry clears error');
 await evaluate('mount(false)');await waitFor("Array.from(document.querySelectorAll('aside button')).some(e=>e.textContent==='Photos')");assert.equal(await evaluate("Array.from(document.querySelectorAll('aside button')).some(e=>e.textContent==='Rapports')"),false);assert.equal(await evaluate("document.body.innerText.includes('Télécharger le rapport')"),false);pass('Deep link cannot enable a disallowed Reports view');assert.deepEqual(exceptions,[]);assert.deepEqual(consoleErrors,[]);
});fs.mkdirSync('docs/stabilization-local/certification/remote/final-resume',{recursive:true});fs.writeFileSync('docs/stabilization-local/certification/remote/final-resume/report-portal-browser.json',JSON.stringify({at:new Date().toISOString(),records,limits:'Actual React components; mocked authorized list and download service.'},null,2));console.log(records.length+' report portal browser cases PASS');
