import assert from'node:assert/strict';import fs from'node:fs';
import{createReportDraft,duplicateLogicalRows,parseRecipients,uniqueReportSupports,validateReportIntegrity}from'../src/lib/module15ReportModel.js';
const read=path=>fs.readFileSync(path,'utf8'),ui=read('src/components/Module15Reports.jsx'),service=read('src/services/reportDataService.js'),pdf=read('src/services/finalReportService.js'),sql=read('supabase/V1_3_2_MODULE_15_REPORT_EDITOR_PREPARED.sql'),edge=read('supabase/functions/send-edt-completion-email/index.ts');
for(const count of[1,25,500]){const supports=Array.from({length:count},(_,index)=>({edt_id:8,site:`Site ${index}`,support_id:`S${index}`,campaign_id:2,visual_id:index,installation_status:'Complété'})),draft=createReportDraft({edt:{id:8,no_edt:'EDT-8'},supports,photos:[],issues:[]});assert.equal(draft.source_support_count,count);assert.equal(draft.supports.length,count);assert.deepEqual(validateReportIntegrity(draft),{valid:true,sourceCount:count,reportCount:count,duplicateLogicalRows:0,message:''})}
const duplicate=[{edt_id:1,site:'A',support_id:'S1',campaign_id:2,visual_id:3},{edt_id:1,site:'A',support_id:'S1',campaign_id:2,visual_id:3}];assert.equal(uniqueReportSupports(duplicate).length,1);assert.equal(duplicateLogicalRows(duplicate),1);
const recipients=parseRecipients(' TEST@EXAMPLE.COM;test@example.com, second@example.org\ninvalid');assert.deepEqual(recipients.valid,['test@example.com','second@example.org']);assert.deepEqual(recipients.invalid,['invalid']);
for(const label of['Créer un nouveau rapport','Modifier','Prévisualiser','Télécharger','Envoyer','Renvoyer','Résumé des travaux','Emplacements d’installation','Photos','Enjeux / écarts','Conclusion','Nombre d’emplacements'])assert.ok(ui.includes(label),label);
for(const marker of["from('edt_supports')","from('infrastructures')","from('support_photos')","from('enjeux_terrain')",'validateReportIntegrity','save_edt_report_draft_v132','finalize_edt_report_v132','request_edt_report_email_v132'])assert.ok(service.includes(marker),marker);
for(const marker of['generateEdtReportPdf','snapshot.section_order','snapshot.supports','Aucune photo sélectionnée','doc.addPage()'])assert.ok(pdf.includes(marker),marker);
for(const marker of['content_snapshot jsonb','support_count integer','recipient_emails text[]','report_missing_edt_supports','jsonb_array_length','save_edt_report_draft_v132','finalize_edt_report_v132','request_edt_report_email_v132','security definer'])assert.ok(sql.includes(marker),marker);
assert.ok(!/\b(drop table|truncate|delete from)\b/i.test(sql),'migration additive uniquement');assert.ok(edge.includes('job.report_id')&&edge.includes('job.recipient_emails')&&edge.includes('recipients.map(address'));
assert.ok(!ui.includes('Supprimer'),'Historique non destructible');assert.ok(ui.includes("['Administrateur','Coordonnateur'].includes(role)"),'Permissions de gestion');assert.ok(ui.includes('loading="lazy"'),'Photos lazy');
console.log('Module 15 V1.3.2 : création, édition, preview/PDF communs, 1/25/500 supports, versions, photos, email multiple, permissions et historique validés sans réseau.');
