import fs from 'node:fs';import assert from 'node:assert/strict';import {offlineBrowser} from './lib/offlineBrowser.mjs';const records=[];
await offlineBrowser('scripts/fixtures/strict-grid-entry.jsx',async({evaluate,waitFor,sleep,exceptions,consoleErrors})=>{
for(const [surface,role,client] of [['admin','Administrateur',2],['admin','Coordonnateur',2],['client','Client',2],['client','Client-Admin',2],['client','Client',9],['client','Admin Preview',2]])for(const label of ['CSV résultats','Excel résultats','Excel sélection','PDF']){
await evaluate('mount('+JSON.stringify(surface)+',0,'+JSON.stringify(role)+','+client+')');await sleep(100);await waitFor('!!document.querySelector("tbody tr")');const button='[...document.querySelectorAll("button")].find(n=>n.textContent.includes('+JSON.stringify(label)+'))';
if(label==='Excel sélection'){assert.equal(await evaluate(button+'.disabled'),true);await evaluate('document.querySelector("tbody input[type=checkbox]").click()');await sleep(30)}
if(label==='CSV résultats'){await evaluate('strictGrid.failExport=true;'+button+'.click()');await waitFor('document.body.textContent.includes("STRICT_EXPORT_ERROR")||document.body.textContent.includes("Export impossible")');assert.equal(await evaluate('strictGrid.files.length'),0);await evaluate('strictGrid.failExport=false')}
await evaluate('const b='+button+';b.click();b.click()');await waitFor('strictGrid.files.length>0');await sleep(250);assert.equal(await evaluate('strictGrid.files.length'),1,role+' '+label+' double click');assert.ok(await evaluate('strictGrid.files[0].size>0'));records.push({surface,role,client,label,result:'PASS_LOCAL',tests:'actual generated artifact|CSV error/retry|double click one file|selection disabled when empty'});
}
assert.deepEqual(exceptions,[]);assert.ok(consoleErrors.every(e=>e.includes('Client export failed')&&e.includes('STRICT_EXPORT_ERROR')));fs.writeFileSync('docs/stabilization-local/certification/strict/grid-exports-results.json',JSON.stringify({records,exceptions,consoleErrors},null,2));},{exposeMain:true,realServices:['roleVisibilityService.js','mapService.js']});console.log(records.length+' strict grid export cases PASS');
