import assert from 'node:assert/strict';
import fs from 'node:fs';
import {offlineBrowser} from './lib/offlineBrowser.mjs';
const cases=[];const certification=process.argv.includes("--certification");
await offlineBrowser('scripts/fixtures/auth-form-entry.jsx',async({evaluate,waitFor,sleep,exceptions})=>{
 const fill=async(selector,value)=>{await evaluate(`(()=>{const n=document.querySelector(${JSON.stringify(selector)});Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(n,${JSON.stringify(value)});n.dispatchEvent(new Event('input',{bubbles:true}))})()`);await sleep(30)};
 if(!certification){await evaluate('mount()');await waitFor("Boolean(document.querySelector('form'))");await evaluate("document.querySelector('button[type=submit]').click()");assert.equal(await evaluate('authFixture.calls.length'),0);cases.push('login required fields block empty values');
 await fill('input[type=email]','bad-email');await fill('input[type=password]','LocalFixture!234');await evaluate("document.querySelector('button[type=submit]').click()");assert.equal(await evaluate('authFixture.calls.length'),0);cases.push('login invalid email blocked');
 await fill('input[type=email]','local@example.test');await evaluate("authFixture.fail=true;document.querySelector('button[type=submit]').click()");await waitFor("document.body.textContent.includes('AUTH_FIXTURE_ERROR')");assert.equal(await evaluate("document.querySelector('input[type=email]').value"),'local@example.test');cases.push('login error keeps values');
 await evaluate("authFixture.fail=false;authFixture.calls=[];const b=document.querySelector('button[type=submit]');b.click();b.click()");await sleep(250);assert.equal(await evaluate("authFixture.calls.filter(x=>x==='signInWithPassword').length"),1);cases.push('login retry double click one Auth call');
 await evaluate("authFixture.fail=true;document.querySelector('.link-button').click()");await waitFor("document.body.textContent.includes('AUTH_FIXTURE_ERROR')");
 await evaluate("authFixture.fail=false;authFixture.calls=[];const b=document.querySelector('.link-button');b.click();b.click()");await waitFor("document.body.textContent.includes('réinitialisation a été envoyé')");assert.equal(await evaluate("authFixture.calls.filter(x=>x==='requestPasswordReset').length"),1);cases.push('password reset error/retry/double click one mocked request');
 }
 for(const role of certification?['Administrateur','Coordonnateur']:['Client','Client-Admin','Installateur']){
  await evaluate(`mount('activation','ready',${JSON.stringify(role)})`);await sleep(80);await waitFor("Boolean(document.querySelector('.activation-submit'))");assert.equal(await evaluate("document.querySelector('.activation-submit').disabled"),true);
  await fill('input[type=password]','LocalFixture!234');await fill('label:nth-child(2) input[type=password]','Mismatch!234');assert.equal(await evaluate("document.querySelector('.activation-submit').disabled"),true);await fill('label:nth-child(2) input[type=password]','LocalFixture!234');
  await evaluate("authFixture.fail=true;document.querySelector('.activation-submit').click()");await waitFor("document.body.textContent.includes('AUTH_FIXTURE_ERROR')");assert.equal(await evaluate("document.querySelector('input[type=password]').value"),'LocalFixture!234');
  await evaluate("authFixture.fail=false;authFixture.calls=[];const b=document.querySelector('.activation-submit');b.click();b.click()");await waitFor("document.body.textContent.includes('Activation fixture complete')");assert.equal(await evaluate("authFixture.calls.filter(x=>x==='updateUser').length"),1);assert.equal(await evaluate("authFixture.calls.filter(x=>x==='invoke:invite-user').length"),['Client','Client-Admin'].includes(role)?1:0);cases.push(role+' activation validation/error/retry/double click/complete');
 }
 for(const state of certification?[]:['expired','invalid','activated']){await evaluate(`mount('activation','${state}')`);await sleep(80);assert.equal(await evaluate("Boolean(document.querySelector('form'))"),false);assert.equal(await evaluate('authFixture.calls.length'),0);cases.push(state+' invitation notice makes no mutation')}
 assert.deepEqual(exceptions,[]);fs.writeFileSync(certification?'docs/stabilization-local/certification/auth-role-results.json':'docs/stabilization-local/followup/auth-form-results.json',JSON.stringify({cases,result:'PASS_LOCAL_BROWSER',remote:'Real Auth/token expiry/24h/mail not tested'},null,2));
},{realServices:['accountActivationService.js'],supabaseSource:`export const supabaseConfigured=true;export const supabase={auth:{getSession:()=>window.authApi('getSession'),updateUser:()=>window.authApi('updateUser'),signInWithPassword:()=>window.authApi('signInWithPassword')},rpc:name=>window.authApi('rpc:'+name),functions:{invoke:name=>window.authApi('invoke:'+name)}};`});
console.log(`${cases.length} Auth form contracts PASS; no real Auth or mail`);
