import assert from 'node:assert/strict';
import fs from 'node:fs';
import {offlineBrowser} from './lib/offlineBrowser.mjs';
const cases=[];
await offlineBrowser('scripts/fixtures/refresh-lifecycle-entry.jsx',async({evaluate,waitFor,sleep,exceptions})=>{
 await evaluate('mount()');await waitFor('Boolean(window.startRead)');
 await evaluate("void startRead('too late',180)");
 await waitFor("document.querySelector('[role=alert]').textContent.includes('trop de temps')");
 assert.equal(await evaluate("document.querySelector('[data-busy]').dataset.busy"),'false');
 await evaluate("void startRead('retry',5)");await waitFor("document.querySelector('output').textContent==='retry'");
 await sleep(200);
 assert.equal(await evaluate("document.querySelector('output').textContent"),'retry');
 cases.push('timeout releases loading; retry wins over late resolution');
 await evaluate("void startRead('old scope',60);mount('B')");await waitFor("document.querySelector('[data-scope]').dataset.scope==='B'");
 await sleep(100);
 assert.equal(await evaluate("document.querySelector('output').textContent"),'retry');
 assert.equal(await evaluate("document.querySelector('[role=alert]').textContent"),'');
 cases.push('scope change rejects pending data and clears loading');
 await evaluate("void startRead('stale error',60,true);void startRead('new data',5)");
 await waitFor("document.querySelector('output').textContent==='new data'");await sleep(100);
 assert.equal(await evaluate("document.querySelector('[role=alert]').textContent"),'');
 cases.push('superseded failure cannot replace current success');
 await evaluate("void startRead('unmounted',60);unmount()");await sleep(100);
 assert.equal(await evaluate("document.querySelector('#root').textContent"),'');
 assert.deepEqual(exceptions,[]);
 cases.push('unmount invalidates pending read');
 fs.writeFileSync('docs/stabilization-local/followup/refresh-lifecycle-results.json',JSON.stringify({cases,exceptions,result:'PASS_LOCAL_BROWSER'},null,2));
});
console.log(`${cases.length} refresh lifecycle cases PASS`);
