import assert from 'node:assert/strict';
import {isPhotoReviewItem,photoReviewState} from '../src/lib/photoReview.js';
import {formatTimeHHMMSS,isTimeOnlyColumn} from '../src/lib/businessTime.js';
import {compareCampaigns,compareVisuals} from '../src/lib/gridSorting.js';
import {normalizeEdtNumber,projectCampaignHistory,summarizeCampaignHistory,reconcileVisualCampaigns} from '../src/lib/campaignHistory.js';
for(const status of [null,'TO_REVIEW','À_VALIDER','UNIDENTIFIED','SUPPORT_TO_REVIEW','EDT_TO_REVIEW','VISUAL_TO_REVIEW','TYPE_TO_REVIEW','error','unmatched'])assert(isPhotoReviewItem({source:'mass_import',review_status:status}));
assert(isPhotoReviewItem({statut_validation:'À valider'}));assert(!isPhotoReviewItem({statut_validation:'Validée'}));
assert.equal(photoReviewState({source:'mass_import',statut_validation:'Validée'}),'pending');
assert.equal(photoReviewState({source:'mass_import',import_finalized_at:'2026-09-19'}),'validated');
assert.equal(photoReviewState({source:'mass_import',review_status:'ignored'}),'ignored');
for(const [input,expected] of [['08:15:00','08:15:00'],['17:42:31','17:42:31'],['08:15:00.000','08:15:00'],['08:15:00+00','08:15:00'],['2026-09-19T08:15:00.000-04:00','08:15:00'],['8:15','08:15:00'],[null,''],['24:01:00',''],['08:60:00','']])assert.equal(formatTimeHHMMSS(input),expected);
assert(isTimeOnlyColumn('heure_installation'));assert(!isTimeOnlyColumn('date_heure_installation'));assert(!isTimeOnlyColumn('created_at'));
assert.deepEqual([{id:10,nom_campagne:'Campagne 10'},{id:2,nom_campagne:'Campagne 2'},{id:1,nom_campagne:'Z',statut:'Active'}].sort(compareCampaigns).map(c=>c.id),[1,2,10]);
assert.deepEqual([{id:10,nom_visuel:'Visuel 10'},{id:2,nom_visuel:'Visuel 2'}].sort(compareVisuals).map(v=>v.id),[2,10]);
assert.equal(normalizeEdtNumber(' edt – tos – 09 '),'EDT-TOS-9');assert.notEqual(normalizeEdtNumber('EDT-TOS-22-A'),normalizeEdtNumber('EDT-TOS-22'));
const campaigns=[{id:1,client_id:2,nom_campagne:'A',business_context:'marketing'},{id:2,client_id:2,nom_campagne:'B',business_context:'marketing'},{id:3,client_id:2,nom_campagne:'C',business_context:'operational_communication'}];
const base={client_id:2,campagne:'A',visuel:'V',no_edt:'EDT-TOS-09',date_installation:'2026-09-01',date_retrait:'2026-09-15'};
const rows=projectCampaignHistory([{...base,id:1,support_id:'S1'},{...base,id:2,support_id:'S1'},{...base,id:3,support_id:'S2'},{...base,id:4,client_id:3,support_id:'S3'}],{campaigns});
const summary=summarizeCampaignHistory(rows);assert.equal(summary.length,2);assert.equal(summary[0].nombre_supports,2);assert.equal(summary[1].business_context,null);
const visual={id:1,nom_visuel:'V',client_id:2,campagne_id:1},link={visual_id:1,edt_id:1};
assert.equal(reconcileVisualCampaigns([visual],[link],[{id:1,client_id:2,campagne_id:2}],campaigns)[0].action,'ASSOCIER');
assert.equal(reconcileVisualCampaigns([visual],[link],[{id:1,client_id:2,campagne_id:3}],campaigns)[0].action,'À VALIDER');
assert.equal(reconcileVisualCampaigns([visual],[link,{visual_id:1,edt_id:2}],[{id:1,client_id:2,campagne_id:2},{id:2,client_id:2,campagne_id:1}],campaigns)[0].action,'À VALIDER');
console.log('PASS: review states, time-only values, natural ordering, EDT normalization, distinct supports, tenant/context reconciliation');
