-- TOS Display Manager V1.3.10
-- Moteur d'automatisations transactionnel, états persistants et réparation UTF-8.
-- Additif : préserve les 15 définitions et les 7 relation_rules historiques.

begin;

alter table public.automation_definitions
  drop constraint if exists automation_definitions_status_check;
alter table public.automation_definitions
  add constraint automation_definitions_status_check
  check (status in ('draft','pending_validation','active','inactive','paused'));

-- Les identifiants sont stables : corriger les valeurs en place sans recréer les modèles.
-- Le trigger déclaratif est suspendu pour que cette réparation canonique ne révoque pas
-- les approbations existantes.
alter table public.automation_definitions disable trigger prepare_automation_definition_v0131;
with canonical(id,name,description,actions,executable) as (values
 ('13900000-0000-4000-8000-000000000001'::uuid,'Installation d’un visuel','Prépare les étapes de suivi après une installation terrain.',jsonb_build_array('Mettre à jour le visuel actif','Ajouter l’intervention à l’historique'),true),
 ('13900000-0000-4000-8000-000000000002'::uuid,'Retrait d’un visuel','Prépare la mise à jour du support après le retrait d’un visuel.',jsonb_build_array('Archiver le visuel précédent','Mettre à jour la fiche du support'),true),
 ('13900000-0000-4000-8000-000000000003'::uuid,'Inspection','Centralise les suites à donner après une inspection.',jsonb_build_array('Consigner le résultat','Planifier la prochaine inspection'),true),
 ('13900000-0000-4000-8000-000000000004'::uuid,'Déclaration d’un enjeu','Prépare le suivi et les avis associés à un nouvel enjeu.',jsonb_build_array('Créer le suivi','Aviser les responsables'),true),
 ('13900000-0000-4000-8000-000000000005'::uuid,'Création d’un EDT','Prépare le suivi d’un nouvel EDT.',jsonb_build_array('Initialiser le suivi'),true),
 ('13900000-0000-4000-8000-000000000006'::uuid,'Modification d’un EDT','Harmonise les informations liées lorsqu’un EDT change.',jsonb_build_array('Mettre à jour les éléments concernés'),true),
 ('13900000-0000-4000-8000-000000000007'::uuid,'Bon de travail terminé','Prépare la clôture et la traçabilité du bon de travail.',jsonb_build_array('Consigner la date de fin','Ajouter au suivi'),true),
 ('13900000-0000-4000-8000-000000000008'::uuid,'Réouverture d’un BT','Prépare la reprise d’un bon de travail.',jsonb_build_array('Réactiver le suivi'),true),
 ('13900000-0000-4000-8000-000000000009'::uuid,'Nouvelle campagne','Prépare les activités associées à une nouvelle campagne.',jsonb_build_array('Préparer les visuels'),true),
 ('13900000-0000-4000-8000-000000000010'::uuid,'Changement de campagne','Prépare le remplacement coordonné d’une campagne.',jsonb_build_array('Actualiser les supports concernés'),true),
 ('13900000-0000-4000-8000-000000000011'::uuid,'Téléversement d’une photo','Prépare le classement d’une nouvelle photo.',jsonb_build_array('Classer la photo','Actualiser la miniature'),true),
 ('13900000-0000-4000-8000-000000000012'::uuid,'Suppression d’une photo','Prépare la traçabilité après une suppression autorisée.',jsonb_build_array('Actualiser la galerie','Consigner l’action'),true),
 ('13900000-0000-4000-8000-000000000013'::uuid,'Nouvelle requête client','Prépare le traitement d’une nouvelle demande client.',jsonb_build_array('Créer le suivi','Aviser le coordonnateur'),true),
 ('13900000-0000-4000-8000-000000000014'::uuid,'Inventaire faible','Prépare un avis lorsque le seuil minimal est atteint.',jsonb_build_array('Créer un avis'),false),
 ('13900000-0000-4000-8000-000000000015'::uuid,'Mise à jour du prochain EDT','Actualise l’information opérationnelle du prochain EDT.',jsonb_build_array('Actualiser le prochain EDT'),true)
)
update public.automation_definitions a
set name=c.name,
    definition=jsonb_set(
      jsonb_set(
        jsonb_set(jsonb_set(a.definition,'{description}',to_jsonb(c.description),true),'{actions}',c.actions,true),
        '{configuration_only}',to_jsonb(not c.executable),true
      ),'{engine_applicable}',to_jsonb(c.executable),true
    ),
    updated_at=now()
from canonical c where a.id=c.id;
alter table public.automation_definitions enable trigger prepare_automation_definition_v0131;

create table if not exists public.automation_resource_states (
  id bigint generated by default as identity primary key,
  resource_type text not null check (resource_type in ('module','table','view')),
  resource_key text not null,
  display_name text not null,
  status text not null default 'active' check (status in ('active','inactive')),
  client_id bigint references public.clients(id) on delete cascade,
  updated_by uuid,
  updated_at timestamptz not null default now()
);
create unique index if not exists automation_resource_states_scope_uidx
  on public.automation_resource_states(resource_type,resource_key,coalesce(client_id,0));
alter table public.automation_resource_states enable row level security;
drop policy if exists automation_resource_states_admin_read_v1310 on public.automation_resource_states;
create policy automation_resource_states_admin_read_v1310 on public.automation_resource_states
  for select to authenticated using (public.current_app_role()='Administrateur');
revoke all on public.automation_resource_states from public,anon,authenticated;
grant select on public.automation_resource_states to authenticated;

insert into public.automation_resource_states(resource_type,resource_key,display_name,status)
values
 ('module','infrastructures','Infrastructures','active'),('module','campaign_history','Historique des campagnes','active'),
 ('module','inspections','Inspections','active'),('module','issues','Enjeux','active'),
 ('module','notifications','Notifications','active'),('module','edt','EDT','active'),
 ('module','work_orders','Bons de travail','active'),('module','campaigns','Campagnes','active'),
 ('module','visuals','Visuels','active'),('module','photos','Photos','active'),
 ('module','poster_inventory','Inventaire d’affiches','inactive')
on conflict do nothing;

insert into public.automation_resource_states(resource_type,resource_key,display_name,status)
values
 ('view','tos-view-active-campaign','Campagne active','active'),
 ('view','tos-view-previous-campaign','Campagne précédente','active'),
 ('view','tos-view-next-edt','Prochain EDT','active'),
 ('view','tos-view-recent-photos','Photos récentes','active'),
 ('view','tos-view-campaign-history','Historique complet','active'),
 ('view','tos-view-active-issues','Enjeux actifs','active'),
 ('view','tos-view-visual-inventory','Inventaire','inactive'),
 ('view','tos-view-edt-progress','Progression EDT','active'),
 ('view','tos-view-work-orders','Bons de travail','active'),
 ('view','tos-view-last-inspection','Dernière inspection','active')
on conflict do nothing;

create table if not exists public.automation_bindings (
  id bigint generated by default as identity primary key,
  automation_definition_id uuid not null references public.automation_definitions(id) on delete cascade,
  trigger_type text not null,
  source_table text not null,
  operations text[] not null,
  source_id_field text not null default 'id',
  target_resource_key text not null,
  relation_rule_id bigint references public.relation_rules(id) on delete set null,
  handler text not null default 'observe_canonical_workflow',
  status text not null default 'active' check (status in ('active','inactive','paused')),
  predicate jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(automation_definition_id,source_table,trigger_type,target_resource_key)
);
alter table public.automation_bindings enable row level security;
drop policy if exists automation_bindings_admin_read_v1310 on public.automation_bindings;
create policy automation_bindings_admin_read_v1310 on public.automation_bindings
  for select to authenticated using (public.current_app_role()='Administrateur');
revoke all on public.automation_bindings from public,anon,authenticated;
grant select on public.automation_bindings to authenticated;

insert into public.automation_bindings
 (automation_definition_id,trigger_type,source_table,operations,target_resource_key,relation_rule_id,predicate)
values
 ('13900000-0000-4000-8000-000000000001','installation_completed','support_photos',array['INSERT','UPDATE'],'infrastructures',null,'{"new":{"is_current_visual":true}}'),
 ('13900000-0000-4000-8000-000000000002','data_removed','support_photos',array['DELETE','UPDATE'],'infrastructures',null,'{"changed":"deleted_at"}'),
 ('13900000-0000-4000-8000-000000000003','inspection_completed','inspections_terrain',array['INSERT','UPDATE'],'inspections',47,'{}'),
 ('13900000-0000-4000-8000-000000000004','issue_reported','enjeux_terrain',array['INSERT'],'issues',null,'{}'),
 ('13900000-0000-4000-8000-000000000005','edt_started','suivi_des_edt',array['INSERT'],'edt',null,'{}'),
 ('13900000-0000-4000-8000-000000000006','data_updated','suivi_des_edt',array['UPDATE'],'edt',null,'{}'),
 ('13900000-0000-4000-8000-000000000007','data_updated','bons_de_travail',array['UPDATE'],'work_orders',null,'{"new_status":["termine","terminé","ferme","fermée"]}'),
 ('13900000-0000-4000-8000-000000000008','data_updated','bons_de_travail',array['UPDATE'],'work_orders',null,'{"old_status":["termine","terminé","ferme","fermée"]}'),
 ('13900000-0000-4000-8000-000000000009','campaign_selected','campagnes_maitres',array['INSERT'],'campaigns',null,'{}'),
 ('13900000-0000-4000-8000-000000000010','campaign_selected','campagnes_maitres',array['UPDATE'],'campaigns',1,'{}'),
 ('13900000-0000-4000-8000-000000000011','photo_taken','support_photos',array['INSERT'],'photos',null,'{}'),
 ('13900000-0000-4000-8000-000000000012','data_removed','support_photos',array['DELETE','UPDATE'],'photos',null,'{"changed":"deleted_at"}'),
 ('13900000-0000-4000-8000-000000000013','data_updated','requetes_clients',array['INSERT'],'work_orders',null,'{}'),
 ('13900000-0000-4000-8000-000000000015','data_updated','suivi_des_edt',array['INSERT','UPDATE'],'infrastructures',null,'{}')
on conflict (automation_definition_id,source_table,trigger_type,target_resource_key) do update
set operations=excluded.operations,target_resource_key=excluded.target_resource_key,
    relation_rule_id=excluded.relation_rule_id,predicate=excluded.predicate,updated_at=now();

alter table public.relation_execution_logs
  add column if not exists automation_definition_id uuid references public.automation_definitions(id) on delete set null,
  add column if not exists trigger_type text,
  add column if not exists source_id text,
  add column if not exists target_table text,
  add column if not exists target_id text,
  add column if not exists started_at timestamptz,
  add column if not exists finished_at timestamptz,
  add column if not exists error_message text,
  add column if not exists initiated_by uuid,
  add column if not exists correlation_id uuid,
  add column if not exists execution_depth integer not null default 0,
  add column if not exists idempotency_key text,
  add column if not exists payload jsonb not null default '{}'::jsonb;
create unique index if not exists relation_execution_logs_automation_idempotency_uidx
  on public.relation_execution_logs(automation_definition_id,idempotency_key)
  where automation_definition_id is not null and idempotency_key is not null;
create index if not exists relation_execution_logs_automation_recent_idx
  on public.relation_execution_logs(automation_definition_id,created_at desc);

alter table public.relation_test_logs
  add column if not exists automation_definition_id uuid references public.automation_definitions(id) on delete set null,
  add column if not exists initiated_by uuid,
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists result jsonb not null default '{}'::jsonb;

drop policy if exists relation_execution_logs_read on public.relation_execution_logs;
drop policy if exists relation_execution_logs_admin_read_v1310 on public.relation_execution_logs;
create policy relation_execution_logs_admin_read_v1310 on public.relation_execution_logs
 for select to authenticated using (public.current_app_role()='Administrateur');
drop policy if exists relation_test_logs_anon_read on public.relation_test_logs;
drop policy if exists relation_test_logs_authenticated_read_v075 on public.relation_test_logs;
drop policy if exists relation_test_logs_admin_read_v1310 on public.relation_test_logs;
create policy relation_test_logs_admin_read_v1310 on public.relation_test_logs
 for select to authenticated using (public.current_app_role()='Administrateur');
revoke all on public.relation_execution_logs from public,anon,authenticated;
revoke all on public.relation_test_logs from public,anon,authenticated;
grant select on public.relation_execution_logs to authenticated;
grant select on public.relation_test_logs to authenticated;

create or replace function public.set_automation_status_v1310(p_automation_id uuid,p_status text)
returns public.automation_definitions language plpgsql security definer set search_path='' as $$
declare v_row public.automation_definitions%rowtype;
begin
 if auth.uid() is null or public.current_app_role()<>'Administrateur' then raise exception 'ADMIN_REQUIRED'; end if;
 if p_status not in ('active','inactive','paused') then raise exception 'INVALID_AUTOMATION_STATUS'; end if;
 select * into v_row from public.automation_definitions where id=p_automation_id for update;
 if not found then raise exception 'AUTOMATION_NOT_FOUND'; end if;
 if p_status='active' and (v_row.approved_by is null or v_row.approved_at is null) then
   raise exception 'AUTOMATION_APPROVAL_REQUIRED';
 end if;
 update public.automation_definitions set status=p_status,updated_by=auth.uid(),updated_at=now()
 where id=p_automation_id returning * into v_row;
 return v_row;
end$$;

create or replace function public.set_automation_binding_status_v1310(p_binding_id bigint,p_status text)
returns public.automation_bindings language plpgsql security definer set search_path='' as $$
declare v_row public.automation_bindings%rowtype;
begin
 if auth.uid() is null or public.current_app_role()<>'Administrateur' then raise exception 'ADMIN_REQUIRED'; end if;
 if p_status not in ('active','inactive','paused') then raise exception 'INVALID_RELATION_STATUS'; end if;
 update public.automation_bindings set status=p_status,updated_at=now() where id=p_binding_id returning * into v_row;
 if not found then raise exception 'AUTOMATION_BINDING_NOT_FOUND'; end if;
 return v_row;
end$$;

create or replace function public.set_automation_resource_status_v1310(p_resource_id bigint,p_status text)
returns public.automation_resource_states language plpgsql security definer set search_path='' as $$
declare v_row public.automation_resource_states%rowtype;
begin
 if auth.uid() is null or public.current_app_role()<>'Administrateur' then raise exception 'ADMIN_REQUIRED'; end if;
 if p_status not in ('active','inactive') then raise exception 'INVALID_RESOURCE_STATUS'; end if;
 update public.automation_resource_states set status=p_status,updated_by=auth.uid(),updated_at=now()
 where id=p_resource_id returning * into v_row;
 if not found then raise exception 'AUTOMATION_RESOURCE_NOT_FOUND'; end if;
 return v_row;
end$$;

create or replace function public.tdm_automation_predicate_matches_v1310(
 p_predicate jsonb,p_operation text,p_old jsonb,p_new jsonb
) returns boolean language plpgsql immutable security invoker set search_path='' as $$
declare v_changed text; v_status text;
begin
 if p_predicate='{}'::jsonb then return true; end if;
 v_changed:=p_predicate->>'changed';
 if v_changed is not null and (p_old->v_changed) is not distinct from (p_new->v_changed) then return false; end if;
 if p_predicate ? 'new' and coalesce(p_new @> (p_predicate->'new'),false)=false then return false; end if;
 if p_predicate ? 'new_status' then
  v_status:=lower(coalesce(p_new->>'statut',''));
  if not (p_predicate->'new_status' ? v_status) then return false; end if;
 end if;
 if p_predicate ? 'old_status' then
  v_status:=lower(coalesce(p_old->>'statut',''));
  if not (p_predicate->'old_status' ? v_status) then return false; end if;
 end if;
 return true;
end$$;

create or replace function public.execute_automation_event_v1310(
 p_source_table text,p_operation text,p_old jsonb,p_new jsonb,p_event_id text default null,
 p_correlation_id uuid default gen_random_uuid(),p_depth integer default 0
) returns jsonb language plpgsql security definer set search_path='' as $$
declare b record; v_source jsonb:=case when p_operation='DELETE' then p_old else p_new end;
 v_source_id text; v_key text; v_log_id bigint; v_results jsonb:='[]'::jsonb; v_resource_status text;
begin
 if p_depth>5 or pg_trigger_depth()>5 then return jsonb_build_object('status','blocked','reason','MAX_EXECUTION_DEPTH'); end if;
 for b in
  select x.*,a.status automation_status,a.definition,r.status resource_status
  from public.automation_bindings x join public.automation_definitions a on a.id=x.automation_definition_id
  left join public.automation_resource_states r on r.resource_type='module' and r.resource_key=x.target_resource_key and r.client_id is null
  where x.source_table=p_source_table and p_operation=any(x.operations)
 loop
  if not public.tdm_automation_predicate_matches_v1310(b.predicate,p_operation,p_old,p_new) then continue; end if;
  v_source_id:=coalesce(v_source->>b.source_id_field,'unknown');
  v_key:=coalesce(p_event_id,p_source_table||':'||p_operation||':'||v_source_id||':'||encode(extensions.digest(coalesce(p_old,'{}')::text||coalesce(p_new,'{}')::text,'sha256'),'hex'));
  insert into public.relation_execution_logs(
   operation_id,rule_id,automation_definition_id,trigger_type,source_table,source_id,
   destination_table,status,message,context,created_by,started_at,finished_at,error_message,
   initiated_by,correlation_id,execution_depth,idempotency_key,payload
  ) values(
   p_correlation_id,b.relation_rule_id,b.automation_definition_id,b.trigger_type,p_source_table,v_source_id,
   b.target_resource_key,
   case when b.automation_status<>'active' then 'Ignorée'
        when b.status<>'active' then 'Ignorée'
        when coalesce(b.resource_status,'inactive')<>'active' then 'Bloquée'
        when b.handler<>'observe_canonical_workflow' then 'Échec' else 'Succès' end,
   case when b.automation_status<>'active' then 'Modèle inactif ou en pause'
        when b.status<>'active' then 'Relation inactive ou en pause'
        when coalesce(b.resource_status,'inactive')<>'active' then 'Destination inactive'
        when b.handler<>'observe_canonical_workflow' then 'Gestionnaire inconnu'
        else 'Événement résolu; effet métier délégué au workflow canonique' end,
   jsonb_build_object('binding_id',b.id,'resource_status',coalesce(b.resource_status,'missing'),'client_id',v_source->>'client_id'),
   auth.uid(),clock_timestamp(),clock_timestamp(),
   case when b.handler<>'observe_canonical_workflow' then 'UNKNOWN_HANDLER' end,
   auth.uid(),p_correlation_id,p_depth,v_key,
   jsonb_build_object('operation',p_operation,'old',coalesce(p_old,'{}'),'new',coalesce(p_new,'{}'))
  ) on conflict (automation_definition_id,idempotency_key) where automation_definition_id is not null and idempotency_key is not null
    do nothing returning id into v_log_id;
  v_results:=v_results||jsonb_build_array(jsonb_build_object('automation_id',b.automation_definition_id,'inserted',v_log_id is not null));
  v_log_id:=null;
 end loop;
 return jsonb_build_object('ok',true,'correlation_id',p_correlation_id,'results',v_results);
exception when others then
 return jsonb_build_object('ok',false,'correlation_id',p_correlation_id,'error',sqlerrm);
end$$;

create or replace function public.tdm_automation_source_trigger_v1310()
returns trigger language plpgsql security definer set search_path='' as $$
declare v_old jsonb:=case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else '{}'::jsonb end;
 v_new jsonb:=case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else '{}'::jsonb end;
begin
 perform public.execute_automation_event_v1310(tg_table_name,tg_op,v_old,v_new,null,gen_random_uuid(),pg_trigger_depth());
 return case when tg_op='DELETE' then old else new end;
end$$;

create or replace function public.test_automation_definition_v1310(p_automation_id uuid,p_payload jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare a public.automation_definitions%rowtype; v_bindings jsonb; v_result jsonb;
begin
 if auth.uid() is null or public.current_app_role()<>'Administrateur' then raise exception 'ADMIN_REQUIRED'; end if;
 select * into a from public.automation_definitions where id=p_automation_id;
 if not found then raise exception 'AUTOMATION_NOT_FOUND'; end if;
 select coalesce(jsonb_agg(jsonb_build_object('binding_id',b.id,'trigger',b.trigger_type,'source',b.source_table,
  'destination',b.target_resource_key,'relation_status',b.status,'would_execute',a.status='active' and b.status='active' and r.status='active')),'[]')
 into v_bindings from public.automation_bindings b left join public.automation_resource_states r
  on r.resource_type='module' and r.resource_key=b.target_resource_key and r.client_id is null
 where b.automation_definition_id=p_automation_id;
 v_result:=jsonb_build_object('dry_run',true,'automation_status',a.status,'bindings',v_bindings,'business_changes',0);
 insert into public.relation_test_logs(automation_definition_id,status,message,details,initiated_by,payload,result)
 values(p_automation_id,'Réussi','Simulation sans effet métier permanent.',v_result,auth.uid(),p_payload,v_result);
 return v_result;
end$$;

do $$declare t text;begin
 foreach t in array array['support_photos','inspections_terrain','enjeux_terrain','suivi_des_edt','bons_de_travail','campagnes_maitres','requetes_clients'] loop
  execute format('drop trigger if exists tdm_automation_v1310 on public.%I',t);
  execute format('create trigger tdm_automation_v1310 after insert or update or delete on public.%I for each row execute function public.tdm_automation_source_trigger_v1310()',t);
 end loop;
end$$;

revoke all on function public.set_automation_status_v1310(uuid,text) from public,anon;
revoke all on function public.set_automation_binding_status_v1310(bigint,text) from public,anon;
revoke all on function public.set_automation_resource_status_v1310(bigint,text) from public,anon;
revoke all on function public.execute_automation_event_v1310(text,text,jsonb,jsonb,text,uuid,integer) from public,anon,authenticated;
revoke all on function public.tdm_automation_predicate_matches_v1310(jsonb,text,jsonb,jsonb) from public,anon,authenticated;
revoke all on function public.tdm_automation_source_trigger_v1310() from public,anon,authenticated;
revoke all on function public.test_automation_definition_v1310(uuid,jsonb) from public,anon;
grant execute on function public.set_automation_status_v1310(uuid,text) to authenticated;
grant execute on function public.set_automation_binding_status_v1310(bigint,text) to authenticated;
grant execute on function public.set_automation_resource_status_v1310(bigint,text) to authenticated;
grant execute on function public.test_automation_definition_v1310(uuid,jsonb) to authenticated;

comment on table public.automation_bindings is 'Liaisons exécutables V1.3.10 entre modèles et événements métier.';
comment on table public.automation_resource_states is 'État persistant des destinations contrôlées par le moteur.';

commit;
